### ISSUE TITLE
Accessories show no response on some iOS devices while working fine on others

### ISSUE THREAD

**Issue by jyen** [nfarina/homebridge#1030]
I have an iphone & ipad. Sometimes home app works fine on both but sometimes for example, iphone home app would show no response while ipad home app still works fine or vice versa. Does anyone else experience similar issue?

Usually if I remove homebridge and reconnect through the home app, both ipad and iphone would work fine; however, after awhile one of them would become no response while the other one continues to work.

**Comment by kevinwestby** [comment]
I am seeing/having the same issue.

**Comment by jenskastensson** [comment]
My experience : Elgato Eve seems to work much better.

**Comment by misanthrophy** [comment]
I have the same issue. My iPhone works perfect, but my iPad is not able to "connect" properly with Homebridge (HomeKit devices are working). The same issue is on my girlfriends iPhone and iPod. So only my iPhone is working as expected!

**Comment by toshibochan** [comment]
Happens to me 2 days and I was using eve app to add accessories but I  reset my home and I use iOS Home app to add and work okay.

**Comment by jeremyvanp** [comment]
I also have this problem. 
With my ipad (ios 9 and Elgato Eve app) it works perfect, but with my iphone (ios10 and Home app) suddenly there is no response. I can solve this problem for a couple of minutes/hours  with turning the wifi from my iphone off and on.

I have seen that the mdns service disappears on my iphone, but don't know how to solve this. is it because of the homebridge or bug at ios10?

**Comment by skywalker1979** [comment]
Try to upgrade to latest IOS. This solved it for me.

**Comment by kevinwestby** [comment]
I’m already on the latest iOS version ☹.  I just reconfigured everything and an going to run a while using only my iPhone to see how it goes


Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>
http://www.westbydigitalmedia.com

Take pictures…in 20 years, you’ll be glad you did.

**Comment by jyen** [comment]
My setup only gets fixed after I reconnect the homebridge to homekit. It'll be fixed for awhile but then some device would stop working after awhile. All devices area already the latest version of iOS.

**Comment by kevinwestby** [comment]
Is there a trick to forcing that reconnect?

Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>

________________________________

**Comment by jyen** [comment]
Unfortunately, when i said reconnect, I meant I had to remove homebridge, go to my server to remove /persist folder, change mac address for homebridge, restart homebridge, reconnect to homekit, which in term lose all the settings. If anyone else have better solution or workaround than this please do share!

**Comment by kevinwestby** [comment]
Bummer….same process as I have to do today ☹


Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>
http://www.westbydigitalmedia.com

Take pictures…in 20 years, you’ll be glad you did.

**Comment by pierrenicolasr** [comment]
Same on my side, and not sure to figure out the reason. I initially thought the problem was related to installing latest iOS 10.2.2 beta as one iPad running 10.2.1 always works ok while the one running 10.2.2 beta or the iPhone on the beta also fails, but today (after reconfiguring everything after latest beta has been released.. sigh...) the iPhone lost connectivity while both iPads are ok.

Only solution seems to be to reconfigure everything but it takes a couple of hours and lasts a few days only :(.

**Comment by snowdd1** [comment]
I see this frequently on my :apple: watch: Siri and home app there tell me that devices do not respond, though on the iPhone which the watch is bound to, at the same, the home app shows all accessories with correct status and they are responding good. HomeKit is still a kind of beta...

**Comment by vaficionado** [comment]
I'm having this same issue. Everything is working great via Homebridge on my own iPhone and iPad, and my wife's iPhone is fine - but her iPad shows every accessory as "No Response". Clearly that's not the case as it works for all the other devices. What could possibly be causing this?

**Comment by jonathanweinberg** [comment]
@Vaficionado - on her iPhone, maybe try going to Settings - iCloud - Turn off "Home".

Shut the phone completely off.

Turn on device, turn "Home" on again. Verify device status.

**Comment by vaficionado** [comment]
@jonathanweinberg Good tip - but no love there. It's weird - when I make changes to the home config (add a new device, etc) it's reflected on her iPad no problem. But all of the devices just say 'not responding'

FWIW, I am on 0.5.0 of Homebridge - I see that 0.5.1 is released but when I sync the git repo to my SmartApps it tells me that the current is 0.5.0

**Comment by vaficionado** [comment]
Actually, I raised a question for myself there. How do I update the Homebridge server itself? I've tried sudo npm update homebridge but nothing is returned.

**Comment by Yardco** [comment]
@vaficionado try `sudo npm update -g homebridge`

**Comment by vaficionado** [comment]
@Yardco Thanks - I figured out what I was doing wrong. I was treating npm like rpm and didn't realize I needed to run it from the directory where the package was installed. 

Ultimately, I completely purged all my HomeKit homes from all 4 iOS devices and iCloud, upgraded the Homekit server and plugins, and recreated the homes from scratch and now things are working again. For now. The new direct update model also caused me some problems - not sure why 3600 seconds was the default polling interval, as any automation run directly by SmartThings/IFTTT/any external source was causing disconnects between actual status and HomeKit displayed status. I had to dial that down to about 10 seconds to make it usable.

**Comment by cben0ist** [comment]
I am having the same issue for 1 day or 2. it has been working perfectly for months and I did not change anything lately. I update my iOS to 10.3.1 recently, not sure that is the reason why...
No errors in the log...

**Comment by cben0ist** [comment]
It looks like this is coming since the latest ios update as it is still working on my wife's phone who did not update yet. It also not specific to homebridge-smartthings as I have the same issue on the homebridge-smartthings-routines for example.

**Comment by bwoodruff** [comment]
I am having the same issue. Homebridge connected accessories appear on and can be interacted with from my iPhone, but not from any other devices (Apple Watch, iPad, Apple TV). Any resolution other than removing and re-adding? What causes it to get into this state?

**Comment by timokli** [comment]
I have the same problem now, everything is working fine on 2 devices, on 2 other devices I get "no answer" from devices. All devices are on the same latest iOS version.

I have noticed one interesting aspects: My Foscam device integrated by homebridge-foscamcamera plugin is still working on all devices, but all other devices do have the problem (for example homebridge-homematic and homebridge-philipshue).

As a test I integrated Hue devices directly with homekit instead of homebridge which works on all devices.

**Comment by jparchem** [comment]
Also having the exact same issue.  After some period of time (usually around a week), Home on my iPhone will show that Homebridge devices have stopped responding, while Hue devices (the official integration) continue to work on the iPhone.  My iPad continues to work with both.  

I'm going to try an simplify things by taking Hue out of the equation for now, and then limiting Homebridge to work with just a couple of simple devices.

**Comment by jparchem** [comment]
So after about 10 days after removing everything but zwave light switches from Homebridge, things are working perfectly so far.  I am beginning to suspect that it might be device related, with a particular suspicious eye towards two Schalge z-wave locks in my case.  Usually by now I'd have seen the bug.  I will try to update in a few weeks.  I will continue to keep the config simple by only including the handful of zwave switches.

**Comment by jyen** [comment]
@jparchem That is an interesting theory but I have had it running as short as 1 day and as long as 3 weeks flawlessly. Also another thing I've noticed is that when 'things' especially schlage connect stop responding to commands, they still show notifications. For example, when schlage stop locking/unlocking from my command, when I manually lock and unlock on the physically lock, I still receive notification from homekit; however, by this point, I'm unable to control anything anymore.

**Comment by gee4vee** [comment]
@jparchem I think you are on to something. I have a Schlage Sense deadbolt and that is the only device that shows not responding on my wife’s phone. It shows up fine on my phone until I leave the house and my WiFi network. Then it shows up as not responding. Surprisingly the Homebridge is more reliable and shows up as available on all our devices. I think Schlage devices are having issues. In fact before the recent firmware upgrade it was much more reliable.

**Comment by gee4vee** [comment]
At least for me I might have narrowed it down to the new Apple TV 4k I just got. I was using it as the sole hub after disconnecting the older 4th gen Apple TV from HomeKit. So I tried removing the deadbolt with the Schlage Sense app, reconnecting the 4th gen Apple TV to HomeKit, and re-adding the lock. The older Apple TV has a status of “standby” instead of “connected”, not sure why, but now I no longer get “not responding” for the lock status when I’m not at home. And I can control it successfully anywhere. It seems that the newer Apple TV has some issues with Schlage devices as a hub.

**Comment by rehafer** [comment]
I have 3 Apple TVs at home. At any given time, only one of the will be connected, the others on Standby.

**Comment by toshibochan** [comment]
Try to not use multiple Apple TV as hub! I have same problems when I had 4 Apple TV as hub! Now I only use one! HomeKit is stable now! 
First i make only one Apple TV as hub.
Second I reset HomeKit and redo all pearling again! Now all device is connect to only one Apple TV hub.

**Comment by jparchem** [comment]
I promised to follow-up after several weeks of testing.  In my particular case, I am confident getting the not responding on some devices (albeit not all) is somehow related to one or more of my Schlage locks.  I cannot speak as to why it continued to work on some devices but not others, but since removing those locks I have had absolutely zero issues.  The locks have also been problematic even outside of HomeBridge. sometimes exhausting battery in a short period of time or going unresponsive for hours at a time, and then coming back online.

So I think for those of you who are also running into this issue, I would try to simplify your configuration and devices and gradually add devices and plug-ins back in to help troubleshoot what might be causing the issue for you.

**Comment by xiaohk** [comment]
Also having the same issue. Does anyone solve it?

**Comment by mcfl33go** [comment]
I have never used Homebridge in my setup, but I can tell you this problem is maddening and it happens a lot. I have 49 HomeKit controlled devices, a HomePod, AppleTV4, and a few iPhones, iPads etc. On any given day at any given time, two devices side by side will be showing different accessories not responding.

I've done just about everything - except completely starting over by deleting/recreating the "home" and re-pairing all my devices.  I'm stubborn that way I guess, but that would take a long time to do 49 devices. But I'm about to do that as a last resort before throwing it ALL in the ebay dumpster.

I can see all the mdns IP multicasts getting to the client device, so device discovery isn't the issue. It has to be a bug in the client code or hub code...don't really know for sure. I just downloaded the HAP Specification for non-commerical use on the Apple developer site. I'm going to start reading it but I don't know if I'll understand enough to figure out what's going on. I know how to use wireshark, but not sure what I'm looking for.

At any rate, I thought I would share this here since its one of the only places people are actually talking about this issue in a thoughtful manner.  And this guy's take on it pretty much sums up my feeling about it:  HomeKit is a sh*tstorm!

https://www.macobserver.com/columns-opinions/editorial/alexa-beats-homekit/

**Comment by coxfrederic** [comment]
I also read that there are known problems with Orbi routers which I need to investigate further (search for orbi homekit issues on google). So that might help to understand the problem further.

**Comment by mcfl33go** [comment]
There are a few things I've discovered that help stability of HomeKit accessories. Make sure each device has a solid WiFi connection (well duh, but still...) Look at RSSI for each device - I try to shoot for an absolute minimum of -74dBm. If you have multiple APs like I do, make sure HomeKit devices aren't roaming ("flapping") excessively between 2 APs. At night (because RF travels further at night), you might see an increase in interference from neighboring APs - be sure to pick non-overlapping channels with the least amount of interference.  Disable CCK (older 802.11b modulation) on your router if you can, and impose a minimum of 6Mbps OFDM only modulation. Ensure mDNS (224.0.0.251:5353) is getting sent between your 2.4GHz HomeKit devices and any 5GHz clients - use wireshark, tcpdump, or another tool like Bonjour Browser (now renamed to Discovery http://www.tildesoft.com/ - for Mac/iOS only) to verify this. In my case, I had a 5GHz backhaul from 2 of the APs and it wasnt passing mDNS -- I fixed this by using powerline ethernet adapters (YMMV).
