### ISSUE TITLE
Question:  SmartThings Hub and Homebridge

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1037]
If I have a SmartThings Hub can it be used with Homebridge?  

And just to confirm, a SmarThings plugin for Homebridge makes the hub not necessary at all.   Is that correct?

I have an opportunity to get a free SmartThings hub but not sure if there is an advantage to having it or if a physical hub would even work with Homebridge.

Thank you.

**Comment by tannebil** [comment]
You need the hub as Homebridge plug-in talks to the SmartThings hub, not the individual devices

**Comment by ehusar** [comment]
I've only been working with 433MHz devices and sending the signals using a 433MHz transmitter from the RPi.   I guess I need to start thinking about deciding on the right hub to buy to expand the system to other devices.

**Comment by ehusar** [comment]
After reading about the SmartThings hub I am shocked that anyone would even use it.  The security issues are pretty scary to say the least.  Can any one recommend a hub that is not cloud based and once installed his secure behind my home network?

**Comment by tannebil** [comment]
No idea as to the number of SmartThings hubs in the world but I'd guess it's a order of magnitude more than anyone else. Most of the complaints have been about reliability rather than security. I do recall one high profile vulnerability that got fixed fairly quickly. It's not something I worry too much about as SmartThings appears to have the motivation and resources to do a decent job.

The only local "hubs" I know about that work with Homebridge are OpenHAB, HAI/Omni, and Home Assistant. Just keep in mind that every program and network has vulnerabilities. I'm not sure I'd place much faith in "secure behind my home network" except unless the home network was deigned and maintained by a security professional.

HomeKit itself uses iCloud so it is not a local solution either.

if you are super concerned about security, I'm not sure that Homebridge is a good approach as it's not a certified part of HomeKit and therefore could create a point of vulnerability in your HomeKit environment.

**Comment by ehusar** [comment]
I ran across the Aeon Labs
Aeotec by Aeon Labs ZW090 Z Stick last night. From what I can it allows you to control SmartThings devices. I think it essential replaces  theSmartThings hub and is the same thing as the Rasberry board just in a USB drive. Give you Z-Wave control.  The reviews from Raspberry users is pretty impressive on Amazon. If this does what I think it does I'll test it out with a Z-Wave outlet.

**Comment by gijoecool** [comment]
You're completely right except for the SmartThings devices. I believe the SmartThings hub will talk to ZigBee devices as well as Z-Wave devices. RaZberry and Z Stick only talk to Z-Wave.
