### ISSUE TITLE
iOS Home app scenes fail but do work

### ISSUE THREAD

**Issue by m3lvn** [nfarina/homebridge#1040]
Hi, I am relatively new to programming but I think that I have managed to set up my RPi the way it should. Both my Nest and Sonos are working but I have an issue:

- I can control my Nest (turn on/off, change temp., etc) but as soon as I create a scene in the iOS Home app the scene suddenly stops loading and says: "Failed". However, the strange thing is that it does change the temperature (as per the scene). So the scene is loading and this is also stated in the debug file from Homebridge.

This is applicable to every type of scene I have created with all combinations of platforms/accessories.

Any ideas?

Thanks,
Melvin

**Comment by ehusar** [comment]
I get this with Automation. Anytime I try to create an automation the app crashes.  I think this is a Home issue and not Homebridge.  I say this because I can use the EVE app and create automations.  Once I do this they show up in the Home app.  

Not a ton of help but it might give you a work around.
