### ISSUE TITLE
Homebridge stopped after undetermined time

### ISSUE THREAD

**Issue by Schnittcher** [nfarina/homebridge#1059]
Hello,

at first, sorry for my bad english.
I have a question regarding the homebridge, when I start the Hombridge all is fine, my iPhone found it and can use it.
But after a while, the iPhone lost the connection to the Homebridge, but the server on the Pi is runnig without errors. 
Has anybody else the problem or a solution?

**Comment by Pytr** [comment]
Same problem often. Always stopped homebridge and restarted it but sometimes it doesn't reconnect either. Today I rebooted the Iphone and instantly reconnected.

**Comment by entmike** [comment]
I have this same issue. I've tested on a Windows and Ubuntu OS, same problem.  After a seemingly random amount of time (sometimes 30 minutes, sometimes a day and a half), homebridge will just cease to recognize any longer on HomeKit.  All devices show 'No Response'.

Here's the weird thing, though...  I have a Kwikset Smart Lock and even when HomeKit gets in this unresponsive state, I still get Home notifications on my iPhone when that lock is unlocked or locked.  To me, this means that HomeKit is still somehow communicating with homebridge, however the device states are getting hung up somehow.  Not sure if this helps, but that's my experience.

My homebridge logs do not show anything out of the ordinary.

**Comment by TLCary** [comment]
Same.  RPi V3, Jessie, Node.JS via apt-get, only running the mqtt-switch plugin.  Generic, plane Jane.
Odd.  Frustrating that I don't see a log entry or any hit as to how to debug this.  Suggestions?

**Comment by entmike** [comment]
I'm wondering if this is working stable (as in for weeks) for anyone?  If so, I'm wondering also if this has something to do with my network configuration.  It's quite basic, just a Wifi setup, no bridge etc...

I should add a little more information, too.

I'm wondering if Bonjour and my router are to blame.  I am using a Linksys WRT1900AC and have a separate problem that began when I switched from my Airport Extreme to Linksys.  AppleTV after about half a day no longer sees my iTunes library and I have to restart iTunes on that computer for it to pick it back up.

On a hunch, I Googled WRT1900AC and Bonjour and got a lot of hits that seemed partially related.  Is anyone else who is having this issue using a Linksys router by chance?

**Comment by snowdd1** [comment]
Hi @entmike ,
my homebridge is running stable for 2 month now (see https://github.com/nfarina/homebridge/issues/874#issuecomment-272702806) without major problems. Minor problem: though home app on the phone and on the ipad shows all services with their states, my apple watch often claims they are unreachable/no answer. This usually goes away with closing and reopening the home app on the watch, is annoying anyhow.

**Comment by entmike** [comment]
Thanks, @snowdd1.  What router do you use?  Based on your link, perhaps I should go back and re-visit all my plugins again and rule them out one-by-one.  It'll be a tedious process, since homebridge will run for a time before the Home app on iOS stops communicating with it.

To give more information, here are the plugins I am using:

- homebridge-wink
- homebridge-pivot-power-genius  (patched version to prevent unrelated crashing issue with 2 quirky power strips)
- homebridge-simplisafe-home-security-system
- homebridge-cmdswitch2
- homebridge-server

**Comment by snowdd1** [comment]
@entmike You might try to put them into different instances of homebridge, so you can easily monitor them failing, because you see which homebridge vanishes or becomes unresponsive.

**Comment by Pytr** [comment]
Hi @entmike, I have a Technicolor modem and the same problems with Homebridge and the no longer maintained Homewizard plugin. To lose contact with your itunes library is common and there is a lot to be found on that problem. Do you think it is related? If it's a Bonjour issue then what about the notifications about Bonjour when one starts Homebridge?

**Comment by gijoecool** [comment]
I am using Apple routers with my FiOS router and I don't have this problem. I really think this is network related.

When you say "working stable" do you mean that homebridge stops running, or that you can no longer communicate with homebridge?

**Comment by snowdd1** [comment]
@entmike for the router (access points, in fact): I use an ancient D-LINK DIR-645 as access point in my living room, and AVM "Fritz!Wlan" (yes, I am German...) Repeaters in kitchen and study configured as access points, on a TP-link TL-SG1024 switch as backbone; outside connectivity is a "Fritz!Box 7490" DSL router. 
Homebridge is running on a Raspberry Pi2B 24/7 with APC power backup (which includes the switch and the dsl modem, but not the access points).  

As said, that seems to be a very stable set up.  

Ah, and I am only using my own homebridge plug-in, so I cannot say anything about other plug-ins, other than what I've read here.

**Comment by entmike** [comment]
@snowdd1 - That's a good idea.  I actually did something similar last night before bed.  I put homebridge-cmdswitch2 on my Windows homebridge last night, and the rest were running on Ubuntu.  When I woke up this morning, both bridges were no longer responding.  The Ubuntu instance is a small enough VM, that I can clone it a number of times to see if certain homebridges fail before others, or all at once.

@Pytr - My iTunes dropping issue coincided with my router change, so I suspected that it had something to do with Bonjour, only because this seems to be a very specific Apple-specific issue that I am facing with both iTunes and HomeKit...  On a related note, the reason I have the homebridge-cmdswitch2 plugin is so that I can lazily kill and restart iTunes via the Home app instead of Remoting into that machine :)

@gijoecool - When I mean working stable, I mean that the Home->HomeKit->homebridge communication is consistent.  From the logs, homebridge is not crashing out, at least not visibly).

Also, just a few minutes ago, I install Hesperus (free iOS HomeKit app) on my phone while homebrige/HomeKit is in this 'Not Responsive' state.  It was able to pull back the list of devices and their last state, however I suspect it may just have gotten that from HomeKit/iCloud and not made it all the way back to homebridge...

**Comment by gijoecool** [comment]
You should see in the homebridge logs if Hesperus was contacting homebridge or not.

**Comment by entmike** [comment]
@gijoecool I don't think it was.  I can tell when the Home app does, because the SimpliSafe plugin logs a status polling entry.  Plus, I cannot toggle the lights on/off.  It gives a brief loading progress but then flips back to prior state.  I think it basically just got iCloud (or my AppleTV acting as the HomeKit hub maybe?)'s last state.  I also tested this my switching off a light that was on this morning, and my Wink app sees the new state, however this Hesperus app still reflects the "frozen" state (on) from overnight.

Perhaps I can narrow this down to the Apple TV "hub" being the issue rather than homebridge...  Perhaps the restarting homebridge is knocking something loose in the hub.  Or I could just be making stuff up at this point, I dunno. :)

**Comment by entmike** [comment]
Just an update, to rule out Apple TV being the weak link, I've set it to never go to sleep (temporarily, not an ideal solution) to see if there's some sort of issue there.  I've also got it plugged into ethernet now, as I noticed the cable wasn't plugged in for some reason so it was also on Wifi.  I'll let it run and report back if it drops again.

**Comment by Dirtrunner702** [comment]
any update on this? did the updated apple tv configuration solve the problem?

**Comment by entmike** [comment]
No, it continues to drop intermittently. I am out of ideas and have given up more or less. The only thing I know to do is switch out my router as a desperate last choice. I've moved to Home Assistant for now until I can find the root cause of my issue with my setup.

**Comment by Dirtrunner702** [comment]
Hello, I just commented on another thread regarding a similar issue. 

I was experiencing device statuses showing "updating" for an eternity until toggling off wifi to LTE or waking the ipad up, which was my homekit hub, or sporadic not responding messages. 

I recently purchased an Apple TV 4th gen and hard wired it to my LAN ( no WIFI) , which is the same LAN my Homebridge VM is connected to. 

I removed everything homekit on all my iOS devices before promoting the Apple TV to be a homekit hub. I then promoted the Apple TV to be the only HomeKit hub, went to the Homekit app on my iPhone and paired it with Homebridge. my two accessories showed up fine and I even created a scene. 

I no longer have the long "Updating" issues or not responding messages as before. Accessories now update immediately upon pulling up the iPhone card for homekit or the homekit app. Doesn't matter if my iPhone is on my home on wifi or on LTE. It just works now! Siri works great now too. no more inconsistencies. 

I currently use the chamberlain garage door and Samsung tv modules in Homebridge. Using a Google OnHub as my router that is connected to an HP 24 port switch. I also created DHCP reservations for my Windows 10 HomeBridge server and the Apple TV so the IP does not. No special network configs other than DHCP. I have Homebridge reboot nightly via Task Scheduler. Apple TV is set to never go to sleep. 

If you want more detail on something just let me know! I have my theories on there being an issue with Bonjour and the ipad being wireless and homebridge on Ethernet and routing getting thrown off.

**Comment by Tiger519** [comment]
@entmike Did you ever get this resolved? I've been having a similar issue. Randomly it worked for over a month straight, but I'm back to it dropping intermittently. I've noticed that my iTunes sharing does the same thing, but here's the weird part...restarting iTunes fixes both iTunes sharing AND HomeBridge! So to me it seems like somehow the Bonjour service is "going to sleep", and restarting iTunes wakes it up somehow. But the PC itself is set to never sleep, and no changes were made from when it worked continuously for over a month. So I'm at a loss...

**Comment by entmike** [comment]
Disabling IPv6 on my router seems to have resolved it, oddly.

**Comment by peaz** [comment]
Just wanted to add also that disabling IPv6 on my router made the homebridge connection a whole lot more stable.
