### ISSUE TITLE
Homebridge "ghosting" randomly

### ISSUE THREAD

**Issue by inzlabs** [nfarina/homebridge#1061]
Hello,

First of all,l thank you for taking your time to help. 

During this week homebridge started to quit itself randomly. I notice because the Home app says: "no response". Then I log into the RPi, do a "Screen -r" and nothing. Then I run again Homebridge, all happiness but some time later, the same thing.

I am sorry there is no much information I can give now. But if this happens to someone maybe we can share situation to see how to fix it?

This is the current situation with the versions:
```
hap-nodejs   😎  NEW VER!  NonSemver update available. https://github.com/KhaosT/HAP-NodeJS
                          npm install --global hap-nodejs@0.4.21 to go from 0.4.17 to 0.4.21

homebridge   😎  NEW VER!  NonSemver update available. https://github.com/nfarina/homebridge#readme
                          npm install --global homebridge@0.4.16 to go from 0.4.11 to 0.4.16

node-gyp     😎  MINOR UP  Minor update available. https://github.com/nodejs/node-gyp#readme
                          npm install --global node-gyp@3.5.0 to go from 3.4.0 to 3.5.0

npm          😎  MAJOR UP  Major update available. https://docs.npmjs.com/
                          npm install --global npm@4.0.5 to go from 3.10.9 to 4.0.5
```

I know it looks silly to complain if I am not up to date, but maybe updating will get it worst?

**Comment by NorthernMan54** [comment]
Can you share the homebridge logs?  It will provide the detail around why homebridge is exiting.   The actual error should be close to the bottom of the file.

**Comment by NorthernMan54** [comment]
Just looking at the the log, and the homebridge plugin failed when trying to talk to 192.168.1.13, where it didn’t respond fast enough and caused homebridge to exit.   From the log fragment it isn’t obvious which plugin caused the error, does the error block continue and does it have lines with ‘homebridge’ in it.  Those are critical in determining exactly where the problem occurred.  From this I can suggest 2 courses of action.

1) Raise an issue with the plugin developer, saying that timeout errors are causing homebridge to exit, and ask them to catch these errors to prevent hombridge from exiting.

2) Take a look at on your network as to why the device at .13 isn’t responding.   Is it a connectivity issue or ??

3) Setup homebridge to autostart in the event of a failure using systemd https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd <https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd>

This is the preferred startup method, rather than init.d as it will restart homebridge in the event of a failure.

**Comment by inzlabs** [comment]
@NorthernMan54 Thank you so much for your time, I just post this issue on the plug-in Github. 

You were right, *.13 is the TV, that when is running the plug-in works great, but once it is off -let's say while sleeping- the plug-in triggers the crash.

I will follow your advice on step 3. Thanks again.
