### ISSUE TITLE
Refresh Temperature Sensor in Eve

### ISSUE THREAD

**Issue by Schnittcher** [nfarina/homebridge#1067]
Hello,
at first sorry for my bad englisch.
when i refresh the Eve App with pull to refresh, than my temperature sensor shows 0 degree Celsius.
Is there a function for pull to refresh, which i must use in the development?
I hope anyone can help me.

**Comment by NorthernMan54** [comment]
Which plugin are you using, or are you writing your own?

If you are writing your own, take a look at my bme280 plugin

https://github.com/NorthernMan54/homebridge-bme280/

I have implemented refresh and polling so that the values are updated every minute by the plugin to eve.

**Comment by Schnittcher** [comment]
I am devlop my own plugin.
You refresh every minute but what is when yo refresh in the eve app by hand?

**Comment by Schnittcher** [comment]
Ohhhh, thanks i have found my mistake. :)

**Comment by Schnittcher** [comment]
Now i must look for another solution, because when i have a lot of devices in the bridge, the polling chrashes my server. Is there another function to update the devices?

**Comment by snowdd1** [comment]
@Schnittcher  
Kai, what do you mean by "a lot of devices"?  
Ususally even hundreds of polls per minute shouldn't have an effect on the server stability. You might want to reduce the frequency of polling, or implement some polling broker that bundles the requests to the outside world.  
If you have processes that handle outside events (instead of actively polling devices) you could use sockets in your plugin to have those processes talk to them. Example here: https://github.com/nfarina/homebridge/issues/1085#issuecomment-275904174
