### ISSUE TITLE
after removing homebridge I cannot add it later again  

### ISSUE THREAD

**Issue by Geraldf** [nfarina/homebridge#1070]
I jave removed homebridge using the hope app on IOS, I cannot add it again anymore. 
any ideas, what I could do?
Gerald

**Comment by andyrooo82** [comment]
Try changing the pin in the config file

**Comment by jsmeyers** [comment]
My iOS App Can't Find Homebridge

Two reasons why Homebridge may not be discoverable:

Homebridge server thinks it's been paired with, but iOS thinks otherwise. Fix: deleted persist/ directory which is next to your config.json.

iOS device has gotten your Homebridge username (looks like a MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your username in the "bridge" section of config.json to be some new value.

**Comment by desertsilver** [comment]
I was having some issues and removed Homebridge from iOS and now having issues re-adding also.  I have tried changing PIN, deleting persist folder and changing username, all at the same time, and Home app is still not finding Homebridge.

Any other troubleshooting suggestions?

**Comment by skymike** [comment]
http://www.miniwebtool.com/mac-address-generator/ 
Generate a new MAC address  in Colon format (:). Then update you config and replace the MAC with new one and restart homebridge.

**Comment by B1tMaster** [comment]
This was really helpful today. 
Question: Where does it store the ID? (the mac address). I had to generate a new ID as it cached it someplace. Just deleting persist directory was not enough.
