### ISSUE TITLE
not registered by any plugin error

### ISSUE THREAD

**Issue by livefeed** [nfarina/homebridge#1083]
I am getting this after a plugin install 

/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");

how do I fix this?

**Comment by mgoblue01** [comment]
Same problem after reinstalling today. Was working earlier, but had a problem with a particular plugin and tried a re-install. Since then, NO plugin shows as registered. I can run with just Homebridge and Http, but no plugins will register.

Have tried homebridge-platform-wemo
homebridge-harmonyhub
homebridge-weather

When running directly, it reports an invalid json.

**Comment by mgoblue01** [comment]
For me, there was a package.json FOLDER in C:\Users\xxx\AppData\Roaming\npm\node_modules.  Threw up an EISDIR error.  When I renamed the folder to something else, then the Homebridge loaded and stayed.
