### ISSUE TITLE
Multiple Homes

### ISSUE THREAD

**Issue by jbsolutios** [nfarina/homebridge#1087]
Homekit supports multiple "homes". Is there any way that a single instance of Homebridge can support this please as at present I have to put everything in to different rooms instead?

Many thanks

**Comment by snowdd1** [comment]
Welcome on GitHub!

No, because homebridge currently uses **one bridge device**.   
And that belongs to **one home**.

You can start multiple homebridge instances on one machine though, use `-U path` to specify a separate directory for the *config.json, persist and accessories* data.

**Comment by VeniceNerd** [comment]
@snowdd1 Can you run multiple homebridge instances on OSX? I don't want to create separatehomes but I'd like to run my Logitech Harmony plugin and my ISY-JS plugin in separate instances since the Harmony plugin crashes a lot and takes everything down. 

Do you have any more details on how to do this?

**Comment by snowdd1** [comment]
I have to admit that I don't know about MacOS, I am a Raspi Linux and PC Windows user.

**Comment by GatoPharaoh** [comment]
what would the files` homebridge` and `homebridge.service` for systemd have to look like to load mutliple instances on an Raspi?
