### ISSUE TITLE
Plugins working problem

### ISSUE THREAD

**Issue by marithpl** [nfarina/homebridge#1089]
Hi,

I've got problem with homebridge plugins. I installed a few plugins like: wemo-platform, cmdswitch2, server, weather from wunderground.
The thing is only wemo-platform is working... during start i have also a few errors/warnings and information about config.json file "Not found config.json file in /root/.homebridge/config.json
I put config file into /pi/root/.homebridge/config.json

Please help with that, before RaspberryPi I had homebridge on MacOS and everything works fine

**Comment by mgoblue01** [comment]
Same problem after reinstalling today.  Was working earlier, but had a problem with a particular plugin and tried a re-install.  Since then, NO plugin shows as registered.  I can run with just Homebridge and Http, but no plugins will register.

Have tried homebridge-platform-wemo
homebridge-harmonyhub
homebridge-weather

When running directly, it reports an invalid json.

**Comment by metbosch** [comment]
Which is the user launching the homebridge service?
The `config.json` must be `/home/<username>/.homebridge/config.json`. You can use the command `whoami` to obtain the current username.

**Comment by snowdd1** [comment]
You shouldn't start homebridge as root.
