### ISSUE TITLE
Any change of a homey plugin?

### ISSUE THREAD

**Issue by Sillec123** [nfarina/homebridge#1127]
Hello,
unfortunately i could not find a good tutorial for develop plugins. Maybe someone with a homey can write a plugin? Maybe, if  we can find enough people, who will spend money for writing a plugin.

Get zones:
curl -H "Authorization: Bearer 0123456789abcdef0123456789abcdef " -H "Content-Type: application/json" http://10.0.0.208/api/manager/zones/

Get all devices:
curl -H "Authorization: Bearer 0123456789abcdef0123456789abcdef " -H "Content-Type: application/json" http://10.0.0.208/api/manager/devices/

Get all devices within a zone:
curl -H "Authorization: Bearer 0123456789abcdef0123456789abcdef " -H "Content-Type: application/json" http://10.0.0.208/api/manager/devices/?zone=01234567-89ab-cdef-0123-456789abcdef

**Comment by swttt** [comment]
Not sure if this fits in the issues here, and might be more relevant in the Homey forum.
Crowd funding this is a great idea tho, but homey isn't that well adopted as a home automation controller.

There is more to it then just these 3 api requests, every device has it's own capabilitie (onoff, dim, rgb etc.) There aren't any docs for it at the moment, and getting al the api endpoints mean you will need to have a homey. (and check the network tab / sniff the api requests)

**Comment by Sillec123** [comment]
That's right! But the homedash shows the possibility of this.

**Comment by bm480** [comment]
I'm interested in this as well. Unfortunately I currently have no time to dive into this further, but want to co-operate if someone feels the urge to get started on a minimally working plugin. ;)

**Comment by CelticWebSolutions** [comment]
Did anybody ever look further in to this?  I've received a homey today and would like to get it working with home bridge, I was surprise dot discover that a decide that was designed purely with the idea of integration, wasn't able to integrate with Apple HomeKit.

**Comment by bm480** [comment]
Officially Apple does not support Homekit with multi-vendor domotica hubs like Homey. This is due to security constraints and prevention of bad user experience. The HomeBridge open source project is an unofficial approach to bridging this GAP. Although Apple will never support this they might consider not changing their API, certificates, protocol so that more people will see the benefits from using Homekit. But they could change things whenever they want which renders HomeBridge related integrations useless. It is unlikely that Athom will ever support HomeKit via HomeBridge but they might try to convince Apple that integrating multi-vendor devices via Homey to HomeKit does not impose security threads and/or bad user experience issues or whatsoever.
