### ISSUE TITLE
Couldn't connect Homebridge

### ISSUE THREAD

**Issue by natedlee** [nfarina/homebridge#1139]
I hate to post another issue about this, but I've tried everything from the similar issues I've read and I still can't complete setup in iOS (10.2.1). 

I'm unning Homebridge on OSX Sierra. Homebridge starts with no errors. I've started with and without platforms and accessories, makes no difference. 

When I enter the code on my phone it circles for a while and ultimately says it couldn't connect. Please advise.

**Comment by 1337bacon** [comment]
Hey, 
have you tried:
1. Homebridge server thinks it's been paired with, but iOS thinks otherwise. Fix: deleted persist/ directory which is next to your config.json.

2. iOS device has gotten your Homebridge username (looks like a MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your username in the "bridge" section of config.json to be some new value.

**Comment by natedlee** [comment]
I have tried both of these and it still doesn't work. I've also changed the port to 36631, just to see if that would work. 

I'll also not that "scanning" the code from my app also doesn't work. I get the box and so on, but it ends up going to a screen to manually input the code, which I do and then it tries to pair for ~1 min before telling me it couldn't add Homebridge.

**Comment by natedlee** [comment]
I got this working on another Mac in Sierra vs El Cap. I have **no** idea why it wasn't working on the other machine. Now I'm trying to get it running in the background -- see t[his issue](https://github.com/nfarina/homebridge/issues/1141).
