### ISSUE TITLE
Accessing plugins outside Home bridge network

### ISSUE THREAD

**Issue by bachoo786** [nfarina/homebridge#1146]
Hi

I have forwarded the port of Home bridge in the hope to access it outside my WiFi network and it seems to fail. Has anyone managed to do this so far?is it possible?

Thanks.

**Comment by ebaauw** [comment]
You cannot expose HomeKit accessories outside your network.  You need to setup an AppleTV or iPad as Home Hub for remote access, see https://support.apple.com/en-us/HT207057.

**Comment by grinsekatze003** [comment]
@ebaauw That's not quite right. Apple released a new protocol with iOS 9 that allows to control devices without an AppleTV via iCloud. I've read that the manufacturs have to use the new protocol for their devices so that it works. Can we make use of that in homebridge too? @nfarina https://discussions.apple.com/thread/7530451?start=0&tstart=0

**Comment by KhaosT** [comment]
@grinsekatze003 Yeah there is a protocol enhancement in iOS 9 that allows iOS device communicate directly with accessory via iCloud without Apple TV or iPad. However, that part of the protocol is not available anywhere online (covered under NDA) and requires MFi chip in the accessory in order to establish the connection to iCloud. There is no way for homebridge to add this.
