### ISSUE TITLE
WindowCovering accessory does not respond when loaded from cache

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1154]
If I use no cache (a la `rm -r accessories`), both my lights and my blinds work. I can turn then on and off, and view their state.
However, if the devices are loaded from cache (which is normal behaviour), my lights work perfectly, while my blinds just say "No Response" and show a loader.

How can I fix this behaviour? I do not want to remove cache every time, as I am using hundreds of devices

**Comment by KhaosT** [comment]
You need to tell plugin developer to fix this.

Best Wishes,
Tian Zhang

**Comment by AmitMY** [comment]
I am the plugin's developer :) I just wrote it, and I don't understand why this behaviour happens

**Comment by KhaosT** [comment]
When a plugin calls ``registerPlatformAccessories``, homebridge will cache the accessory plugin sent. And after homebridge restarts, instead of having plugin to call ``registerPlatformAccessories`` again on all previously registered accessories, homebridge will invoke ``configureAccessory`` on plugin to give it a chance to set up event handlers. Please refer to the [sample platform](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L70) for more details.

**Comment by AmitMY** [comment]
Great! I didn't realise that this is how it works, I actually did wonder though.
I now create a new service if it doesn't exist, or set listeners for the service if it does.

Thanks.
