### ISSUE TITLE
Can't find RPI Homebridge on network

### ISSUE THREAD

**Issue by samuelandersson** [nfarina/homebridge#1169]
Hi!

I am going to try to provide as many details as possible so that someone can help me with this problem.

Let's begin with the problem, I can't find the home bridge accessory when opening the "Home" app. I have tried using "Discovery - Bonjour Browser" along with "Fing" but I can't see the home bridge - so clearly this is a networking issue, eh?

The router I am using is the airport express, no problems with it before. Have never tried something out of the ordinary with it.

I have tried to disable IPV6 on my raspberry pi using other issues on this forum but it does not seem to help. 

I have tried to delete accessories and persist folders.

I have a raspberry pi 2 with a connection to ethernet. The ethernet cable is connected to a switch which is connected to the airport express.

Yet I cant get home bridge to work.

Help?

**Comment by snowdd1** [comment]
I hope the Airport Express is actually an Access Point, not a router - mDNS ("Bonjour") protocol isn't routable.   

Looks like a network issue, because you should at least see the `_hap._tcp` entry in Discovery. Probably the switch isn't forwarding the multicast addresses. It's an unmanaged switch, or can you configure it?
