### ISSUE TITLE
Device state is not updating, until close and reopen

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1178]
I have a bridge running, with 97 devices.
I store 1 variable globally, of all states of the devices, so the `get` of `Characteristic.On` just uses that variable, no server request required.

In my main run, I have this: `setInterval(update, 500);` which updates the global states variable every half a second. (It works)

So as I understand it, if a device was on and is turned off for example, I should see an update on my iPhone in maximum 500ms, or lets even say 10 seconds, but I don't. Instead, to get a device state updated, I minimize the Home app, and then open it again. Everything says "Updating..." and after like a second everything shows the correct state.

If I turn something on, off, or to a state (window covering / dimmer), from the device itself, it updates in real time.

- Is this a bug?
- If not, Is there a way to ask for the accessories to have an update cycle of 0.5 seconds?

**Comment by AmitMY** [comment]
I believe this is also related:
Out of all of the devices, 2 or 3 window coverings are "Not Responding". If I press on them, it says: "40% open. This accessory is not responding"

But how wouldn't it respond? everything responds as a package, it either should say nothing responds, or everything does. Furthermore, all blinds use the same initialisation function, so why one and not the other?

![image](https://cloud.githubusercontent.com/assets/5757359/23513725/be0b3fd8-ff6d-11e6-8e9f-8a61b911f297.png)

**Comment by snowdd1** [comment]
I think you just overloaded it. 97 accessories updating every 0.5 seconds, that's trying to send 194 events to any listening device per second.  

Try just to update the characteristic value if the value changes.  
Something like (coding single handed with no IDE!)
```JavaScript
newValue = someFunctionToGetMyUpdateFrom();
if (newValue!==characteristic.value) {
    characteristic.updateValue(newValue);
}
```
[you might look at my code for a real world example](https://github.com/snowdd1/homebridge-knx/blob/v0.3.9/lib/knxaccess.js#L350-L359)   

And, btw, you don't need to cache the characteristic value, homebridge is taking care of that. Just don't implement any 'get' listeners, then the default behavior (sending the value from characteristic.value) is used. I do that all the time. Don't have any 'get' listener functions in my platform!

**Comment by AmitMY** [comment]
Thanks!
Back a bit, I am not sending 194 events per 0.5 seconds, I am actually not sending any `updateValue`, I was looking for such function and couldn't find one.. (every 0.5 seconds there is a poll from server)

Anyway, just to get this clear:
This line: `var characteristic = chrKNX.getHomekitCharacteristic();`
Where does it get the characteristic from? is chrKNX an accessory object?

**Comment by SkyJohn** [comment]
Where are those 3 blinds in relation to each other?

Are they random blinds throughout the house or are they all in one area and maybe out of range of whatever you have controlling them?

**Comment by AmitMY** [comment]
@SkyJohn They are all around the house, but there is no range factor. All devices are wired to a main server, and I control them via commanding that server.

I thing @snowdd1 suggested approach (If I can get it right) could solve it as well, as it will send an update, which clearly defies the meaning of "No response"
I'll wait for his response..

**Comment by snowdd1** [comment]
Hi @AmitMY ,
you need to store the characteristic references in your controller object. I implemented a class chrKNX to wrap around the homebridge-API-characteristic object, to put more data and methods to it without changing its prototype (kind of extended the object, but inheritance wasn't really there when I started).

So basically I [generate a **new service**](https://github.com/snowdd1/homebridge-knx/blob/v0.3.9/lib/service-knx.js#L127), like a blinds (aka WindowCovering) service (and store a reference to that in my object),  
then I [grab the characteristics (or add them)](https://github.com/snowdd1/homebridge-knx/blob/v0.3.9/lib/characteristic-knx.js#L40-L50) (and store the reference in my object)  

later I add the event listeners I need to listen on (in my case KNX bus message events) to react to outside changes. That is where your routine to poll comes into play. When it detects a change, it invokes the `updateValue(newValue)` method of the stored characteristic object. [In my code, when a fitting bus message arrives to change the value.](https://github.com/snowdd1/homebridge-knx/blob/v0.3.9/lib/characteristic-knx.js#L170-L176)

*Don't let yourself get confused by the mass of code I used. I just tried to make it as flexible as possible. It's supposed to impersonate any defined Homekit service, that's why there's never a reference to any* **specific** *service or characteristic*

**Comment by AmitMY** [comment]
Thanks @snowdd1 !
It's super confusing when there is no clear API for homebridge, and working with no types, but this does clear up some things.

So is this ok?
I have an accessory called `accessory`.
It has a service `WindowCovering`, which has a characteristic "CurrentPosition".
So is what I need to do is this?
```
accessory
    .getService(Service.WindowCovering)
    .getCharacteristic(Characteristic.CurrentPosition)
    .updateValue(newVal, undefined, "what here?")
```

And what is the 3rd parameter for `updateValue`?

I feel like I'm asking dumb questions that would be answered by any doc/wiki, but I can't find any doc/wiki.

Thanks again!

**Comment by snowdd1** [comment]
> And what is the 3rd parameter for updateValue?
It's a context object you can use to pass additional information to any listeners to the 'change' events. Unlike `setValue()` the `updateValue()` method will not emit a 'set' event. 

The context can be used to differentiate sources of data changes. I use the context 'fromKNXBus' to see in the events that I do not need to send that change back to the bus, because it came from there. Is the context different, the change came from Homekit and I need to propagate it to the bus wire.

The documentation is in the code:  
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L191

**Comment by snowdd1** [comment]
Once you've dug so deep into homebridge you need to accept it's a nice framework for the hap-nodeJS where the magic is buried inside.  
There are the definitions for [Service](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js), [Characteristic](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js) and of course the [Homekit types](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js)

**Comment by AmitMY** [comment]
@snowdd1 It took me a while, but I refactored my entire accessories management, and now it updates live, and nothing has "No Response" and everything is great.
So thanks a lot!

Not related, I have a question you might be able to answer:
I have 97 devices as mentioned above. Changing the plugin and playing with the bridge (removing/adding devices) makes me lose valuable information - which room is the accessory on.
I have this data in the plugin, but I saw there is no way to pre-define a room.
Is there a solution you can recommend for me to not need to define rooms each time I remove devices or does such things?

**Comment by snowdd1** [comment]
Hi @AmitMY,  
I recommend to users of my platform that they bundle services into "room accessories". So if you have 4 lights and two blinds in a room, you define 1 accessory containing 6 services.  
Two major advantages:  
- You probably never hit the 99 accessory limit  
- Much less work in case things went south and you have to do all the re-assignments  

Of course, if you set up a lot of automation (trigger and such) it's vain anyhow. But users of the KNX bus system usually have the logic elsewhere and use HomeKit as an extra way of controlling the switches and such, and visualization.

**Comment by AmitMY** [comment]
@snowdd1 Ok... But with having each room as an accessory, will I be still able to create scenarios?
Is there a way to export/import home settings, such as rooms, or scenarios (turn this light on at 6pm)? If so, Ill set everything up and then export.

I too have a system that manages everything, and at first just wanted to make an interface for the iPhone, but that system is super dumb, and I think I can replace it with my own, that's why I need so many things saved to make sure Home will not "break" after a while.

**Comment by snowdd1** [comment]
Accessories have - since iOS 10 - just one purpose: define physical location of services. Everything else is up to the services.  
All you see in Home App are services, not the accessories.
