### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by samuelemarazzita** [nfarina/homebridge#1254]
Hello there, it looks like automation on Homekit doesn't work unless I open the app. I have some devices connected on my homebridge raspberry pi 3 that may turn on and off in some conditions that doesn't work with automation. No errors on terminal. I tried to update homebridge npm, all homebridge plugin and so on, but nothing. Of course I've also tried to reboot my raspi and network connection. Any help?

**Comment by NorthernMan54** [comment]
With homebridge and automation being driven by events from the plugins it depends on the plugin being written to properly support events, homekit itself properly supporting events or notifications for that service type, and having a Apple TV 4 or iPad.

Can you supply more details on your setup and what your attempting to automate?

**Comment by samuelemarazzita** [comment]
Thank you for answering. Well for example I’ve installed the YEELIGHT strip led controlled by homebridge-yeelight plugin and it does’t work. At the same time I have some Philips Hue strip led controlled by Philips Bridge that works perfectly.
Same thing for D-Link smart plug.

> Il giorno 20 apr 2017, alle ore 12:18, NorthernMan54 <notifications@github.com> ha scritto:
> 
> With homebridge and automation being driven by events from the plugins it depends on the plugin being written to properly support events, homekit itself properly supporting events or notifications for that service type, and having a Apple TV 4 or iPad.
> 
> Can you supply more details on your setup and what your attempting to automate?
> 
> Sent from my iPad
>

**Comment by maragelis** [comment]
I have noticed that using a hue bridge with homekit enabled and homebridge there is a issue with automations.

**Comment by samuelemarazzita** [comment]
So maybe it's better to use only homebridge to take control of Hue? In this case I'm going to lose zigbee technology instead of web API?

**Comment by maragelis** [comment]
Its when the Philips-hue app updates homekit that the problem occurs, I just disable and enable the automation and it works good again.

**Comment by kapps7** [comment]
I experienced some reliability issues  right at the start using the Phillips Hue app with HomeKit even before Homebridge implementation. Right away I removed the hue app and everything worked very reliably. This has continued after Homebridge implementation

**Comment by samuelemarazzita** [comment]
Ok, I'm going to try both case: disabling and enabling automations and removing hue app. Back to you as soon as I have an answer.

**Comment by samuelemarazzita** [comment]
Hello there. Unfortunately the automation still doesn't work. Any other suggestion?

**Comment by NorthernMan54** [comment]
If you think it is caused by the homebridge-hue plugin, I suggest opening an issue there and closing this.

**Comment by samuelemarazzita** [comment]
I didn't install the hue plugin. So this is an homebridge automation bug I suppose.

**Comment by ebaauw** [comment]
> So this is an homebridge automation bug I suppose.

In my experience, HomeKit automation is flaky at times, irrespective of what HomeKit accessories or homebridge plugins you use...

> Its when the Philips-hue app updates homekit that the problem occurs

...especially after changing your HomeKit configuration.

> it looks like automation on Homekit doesn't work unless I open the app.

I've experienced the same, and I've had similar reports from some of my homebridge-hue users.  I suspect this is caused by the AppleTV having lost the connection to the HomeKit accessory (be it the Hue bridge or homebridge), so it does't see the changed accessory state that should trigger the automation.  When a HomeKit app is active, it syncs the changed accessory state over iCloud to the AppleTV, which now does see the change and triggers the automation.  
If you're lucky, logging out of iCloud on your AppleTV and logging back in again fixes this issue.  If unlucky, you'll need a complete reset of your HomeKit configuration.

> I have noticed that using a hue bridge with homekit enabled and homebridge there is a issue with automations.

I've also experienced that automations don't get triggered at all, both while using the v2 Hue bridge with HomeKit next to homebridge as well as while using only homebridge (I never tried automations with only the Hue bridge).  I suspect this is caused by the HomeKit configuration not being synced correctly to the AppleTV.  Usually, this is fixed by disabling all automations, waiting for these changes to be propagated to your other iOS devices, re-enabling them, and again waiting for these changes to appear on the other iOS device.  If unlucky... see above.

> So maybe it's better to use only homebridge to take control of Hue?

I've disabled HomeKit on my v2 Hue bridge and have been running homebridge-hue solo for months.  I'm probably biased, but I have a feeling this setup is somewhat less complex and somewhat more stable.    If you have a v1 Hue bridge, this is your only option.  
You need to be wary of the 99 accessory limit per HomeKit bridge though, although there's a bit more room, since I support the Hue motion sensor as a single accessory with three services, rather than as three accessories.  Also, you lose the ability to sync (light assignments to) rooms between the Hue bridge and HomeKit using the Hue app.  If you run homebridge-hue in tandem with the v2 Hue bridge, even the room assignments of the non-Philips lights exposed by homebridge-hue are synced by the Hue app.

>  In this case I'm going to lose zigbee technology instead of web API?

The v2 Hue bridge talks ZigBee to the lights (and sensors and switches) and provides the REST API regardless whether it's used for HomeKit.  In fact, so does the v1 bridge, which doesn't support HomeKit at all.

> With homebridge and automation being driven by events from the plugins it depends on the plugin being written to properly support events  
> If you think it is caused by the homebridge-hue plugin

I'm not saying I'm incapable of making mistakes, but I took great care to setup events properly in homebridge-hue.

**Comment by samuelemarazzita** [comment]
Thank you @ebaauw. I'm not using homebridge-hue to control my Philips HUE strips, but the Philips HUE bridge with HomeKit. Right now the problem is not the HUE but the Yeelight and the DLINK w215 that are not HomeKit ready. The automation doesn't work until I open the Home app on my device. Right now I have an iPad controlling all the accessories in my home and on this device there is no HUE app installed.
I'm testing right now automations with Elgato EVE app. I'll let you know if this fixes my problem.

**Comment by samuelemarazzita** [comment]
No way, this morning automation didn't work again: only one yeelight switched on (with wrong color) and the dlink smart plug didn't turn on (no toast for me :( ).

Philips hue lighting works perfectly because they are controlled by hue bridge (maybe). Everything controlled by homebridge seems to have problems with automation. My raspberry command line tells me there were some errors with a yeelight but no detail of any kind. 

I decided to try changing my router, hope this may help.

Note: Yesterday I checked on my iPad, switching off and on automations as you suggested me.

**Comment by samuelemarazzita** [comment]
Sorry, just another note: using IFTTT to take control of yeelight or dlink seems to work perfectly.
Stay tuned and reply with any suggestion!

**Comment by ebaauw** [comment]
> Philips hue lighting works perfectly because they are controlled by hue bridge 

Yes, Hue bridge rules are far more reliable than HomeKit automation.  I've automated my lights using only the Hue bridge.  I only use HomeKit to automate non-Hue accessories: my Sonos speakers and Eve energy plugs.

> Everything controlled by homebridge seems to have problems with automation.

That's Apple: it just works... in 95% of the cases.  In the other 5% they give you no clue whatsoever how to determine the problem, let alone fix it.

> My raspberry command line tells me there were some errors with a yeelight but no detail of any kind.

Double-check that the changes are reflected in the Home app (or Eve).  If so, the problem is with HomeKit automation; if not the problem is with the plugin.

> No way, this morning automation didn't work again: only one yeelight switched on (with wrong color) and the dlink smart plug didn't turn on

That sounds like a communication glitch between the AppleTV and homebridge.

> I decided to try changing my router, hope this may help.

Before changing routers, I strongly recommend to use wired ethernet connections between the Raspberry Pi running homebridge, the Hue bridge (which doesn't support WiFi anyway), and the AppleTV.  No WiFi, no PowerLAN, see https://github.com/ebaauw/homebridge-hue/issues/15#issuecomment-282446732.  Also, if possible, use a lower channel (1 or 6) for your WiFi and set the ZigBee channel on your Hue bridge to 25, to minimise interference in the 2.4GHz range between WiFi and ZigBee.
 
> Yesterday I checked on my iPad, switching off and on automations as you suggested me.

That might help if (some) HomeKit automation doesn't get triggered at all, not if the automation (for some accessories) only gets triggered when a HomeKit app is open, see my above post.

**Comment by samuelemarazzita** [comment]
Hello there, just an update: the problem was my router. I bought an highest quality product that lets me create priority IP rules so, when the router restarts itself for any reason, the IOT gets the correct IP configured on homebridge.

DLINK w215 plug continue not working with automation (the command line log continues saying ERROR when trying to turn it on with automation) but the yeelight solution works fine. I think this may be a plugin problem, I'm going to report it to the developer.

Thank you for your support!
I'm going to leave the issue open to let you know any improvement on the DLINK w215 bug.
