### ISSUE TITLE
Recommendations for Hue plugin with Switches

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1260]
I am considering a purchase of either the Phillips Hue tap switch Or the dimmer.

I want each of the buttons on them to be able to execute a Home Kit scene and wondering if people are currently using it this way and which of the plugins people are have success with.
Thanks.

**Comment by KhaosT** [comment]
Check https://github.com/ebaauw/homebridge-hue

**Comment by macbisho** [comment]
I have recently purchased the Dimmer switch so that friends who aren't iOS users can use my HomeKit setup when they house sit.

I've got a really simple setup, with only 3 of the 4 buttons configured. 

1. Turn on a set of lights (the standard "on" button)
2. Tap button 2 - sets a dinner time scene
`[4/25/2017, 10:29:05 AM] [Hue] Hue dimmer switch Dim Up: homekit button single press
[4/25/2017, 10:29:05 AM] [WeMo Platform] Dining room - Set state: On
[4/25/2017, 10:29:05 AM] [WeMo Platform] Living room - Set state: On
[4/25/2017, 10:29:06 AM] [WeMo Platform] TV - Set state: On
[4/25/2017, 10:29:06 AM] [WeMo Platform] Living room - Set brightness: 51%
[4/25/2017, 10:29:06 AM] [WeMo Platform] Dining room - Set brightness: 100%
`
3. Long press button 2 - sets movie time scene 
`[4/25/2017, 10:29:45 AM] [Hue] Hue dimmer switch Dim Up: homekit button long press
[4/25/2017, 10:29:46 AM] [WeMo Platform] Dining room - Set state: On
[4/25/2017, 10:29:46 AM] [WeMo Platform] Living room - Set state: On
[4/25/2017, 10:29:46 AM] [WeMo Platform] TV - Set state: On
[4/25/2017, 10:29:46 AM] [WeMo Platform] Dining room - Set brightness: 5%
[4/25/2017, 10:29:46 AM] [WeMo Platform] Living room - Set brightness: 15%`
4. Tap button 4 - all off.

I'd set up more with the other buttons if I needed it, but it's so simple it's perfect.

There is a ~3 second time lapse from button press to action across my Hue and Wemo hardware - but that may be because I'm on WiFi instead of being on ethernet.

I love the simplicity of it, and it works brilliantly.

**Comment by kapps7** [comment]
> Check https://github.com/ebaauw/homebridge-hue
Thanks I had seen this, and search result showed a few others which is why....

> I have recently purchased the Dimmer switch so that friends who aren't iOS users can use my HomeKit setup when they house sit.

Brilliant, was hoping that would work. The dimmer switch is much cheaper and has an extra button than the tap. Although it is on batteries, seems that it will last a while. I also have one wemo device which I will integrate into the scene, so when I have it working, I'll report back on latency.

Thanks guys!

**Comment by ebaauw** [comment]
> There is a ~3 second time lapse from button press to action across my Hue and Wemo hardware - but that may be because I'm on WiFi instead of being on ethernet.

You might want to increase the heartrate at which homebridge-hue polls the Hue bridge.

**Comment by kapps7** [comment]
> There is a ~3 second time lapse from button press to action across my Hue and Wemo hardware
Just wanted to report back that my wemo switch responds in normal time. Heartrate is set to 5.

**Comment by ebaauw** [comment]
The Hue bridge doesn't support notifications, so homebridge-hue needs to poll the bridge (like any other Hue app).  homebridge-hue retrieves the state from the Hue bridge, every `heartrate` seconds.  With a heartrate of 5, it might take up to 5 seconds, before homebridge-hue sees that a button has been pressed and notifies HomeKit.
