### ISSUE TITLE
Autostart Homebridge(systemctl succeed sometimes)-Urgent

### ISSUE THREAD

**Issue by brendanlim1995** [nfarina/homebridge#1275]
Is there any help for this issue,
I didn't do anything but keep entering the following command:"sudo systemctl status homebridge -l"

Why does this happened? Is there anyway to solve this problem?
But the "homebridge" didn't actually start.

![screenshot from 2017-05-04 01-39-51](https://cloud.githubusercontent.com/assets/22288227/25696072/a055c9a8-306a-11e7-9433-67125cb2ac91.png)

**Comment by snowdd1** [comment]
There is something wrong 
- either with your configuration (homebridge.service), such as wrong parameters or so,
- or with the configuration of the plugins you are using.

Your homebridge is starting, crashing, restarting, crashing, and so on. Your `sudo systemctl status homebridge -l` just shows the Desaster, it's not causing it.

If you want to get any further help:
- Tell us which plugins you've installed
- post your `config.json` (dont forget to enclose the file contents in three back tick lines (\`\`\`) otherwise it becomes completely unreadable and no one will care to read it. [See this help](https://github.com/snowdd1/homebridge-knx/issues/61)
- post your `homebridge.service` file

Good luck!
