### ISSUE TITLE
Accessory shows "no answer"

### ISSUE THREAD

**Issue by bhutzler** [nfarina/homebridge#1278]
I'm trying to write a blind plug-in for Homebridge. I am using Service.WindowCovering. The blind reacts as desired. However, the controlpanel sometimes shows me the correct position in the accessory (e.g., 50%). Mostly "no answer" sometimes also an exclamation mark. In other HomeKit apps (e.g., Elgato Eve), the values ​​are always displayed correctly. Why not at Apple directly?
I see that the functions getPosition and getTargetPosition are called one after the other. For an open blind, the values ​​100 are returned.
Does anyone have a tip, why HomeKit mostly shows “no answer"? When I enter the detailed view of the blind, the correct position is displayed.

**Comment by NorthernMan54** [comment]
If you are returning illegal values, the Home app doesn't like that.  Could you be returning values it doesn't like?

Another thought, run homebridge in debug mode, and it will show the communications into homebridge from the Home app.  You might see something squirrelly there.

**Comment by bhutzler** [comment]
The values ​​are not illegal. I've compared them with those of another blind plug-in which works. Same values. How to start the homebridge in debug mode. Spontaneously I found nothing. Thank you for the feedback.

**Comment by GvnCampbell** [comment]
I recently wrote a plugin for my powerview blinds.  I remember running into a similar issue and it was mainly due to understanding how the asynchronous operation works.  The function could be returning to the caller before it actually has the value ready to go.  It took me a while to get my head around it.  If your code is up on github for that function I can take a look or pm me (if thats possible here) and I can take a look.

There are also a few blind and windowcovering examples that you can look at that will give you an idea.

**Comment by bhutzler** [comment]
I have started the homebridge in debug mode: The first 4 accessory entries are from my plugin. The second 4 entries from the working plug-in. I do not see any differences. But with my plugin, HomeKit displays an exclamation mark.
I tried to look elsewhere. I just can not get to the solution. I try to rebuild an already existing plugin for my purposes.
 

EventedHTTPServer [fe80::1815:bf6b:eeab:7d38] HTTP request: /characteristics?id=5.9,5.10,4.9,4.10 +1m
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=5.9,5.10,4.9,4.10 +2ms
  Accessory [Homebridge] Getting value for Characteristic "Current Position" +2ms
  Accessory [Homebridge] Got Characteristic "Current Position" value: 50 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Target Position" +1ms
  Accessory [Homebridge] Got Characteristic "Target Position" value: 50 +1ms

  Accessory [Homebridge] Getting value for Characteristic "Current Position" +0ms
  Accessory [Homebridge] Got Characteristic "Current Position" value: 50 +2ms
  Accessory [Homebridge] Getting value for Characteristic "Target Position" +0ms
  Accessory [Homebridge] Got Characteristic "Target Position" value: 50 +2ms
  EventedHTTPServer [fe80::1815:bf6b:eeab:7d38] HTTP Response is finished +1ms

**Comment by NorthernMan54** [comment]
I'm stumped, I thought debug would have shown something to explain the no answer.  Can you retry and try to capture debug when the Home app starts saying no answer?  This might explain further.

I have seen odd behavior like this around the startup of homebridge, that was resolved by having the plugin send the current values as part of the plugin startup.  Is it possibly this?

**Comment by IMNotMax** [comment]
I have the same behaviour since the last update (I made the update yesterday)... all the homebridge devices are in "update" or "no answer". No error log... just after the update, the homebridge-envisalink and the homebridge-script2 plugins went in "error". The error was "index.js" missing. These plugins never had a index.js... I had to copy the plugin-name.js file to index.js in the plugin directory to go through the error... but now not a single device works...

**Comment by bhutzler** [comment]
The debug log shows the state when the home app does display no response. I have not the latest update of the Homebridge. The NooLite HTTP blinds plugin works without problems (second debug entry). I can't recognize a difference in the source.
Sorry, I'm not a Homebridge / Node.js expert yet. I must first find out how I send the current values ​​with the plugin startup.

**Comment by IMNotMax** [comment]
I found my error was due to the homebridge-envisalink pluging. I had to downgrade to 0.1.6.
Everything works good for me now
