### ISSUE TITLE
iPhone no longer sees homebridge

### ISSUE THREAD

**Issue by gstevenson** [nfarina/homebridge#1313]
Hey,

I use homebridge with homebridge-homeassistant. Unfortunately I'm not sure exactly when, but my Home app no longer sees the devices it should. All are showing with the status of 'No Response'. 

If I run `debug=* homebridge -D` I see state changes of devices on my network so I know the integration with homebridge to homeassistant is working, but there seems to be an issue with the homebridge->homekit/iPhone part of the process.

Can anyone give me any hints or tips for where to begin debugging? At first I thought the process might not even be running, but that's not the case; my config still exists in `/etc/systemd/service/homebridge.service` and `systemctl status homebridge` shows me:

> pi@raspberrypi:/etc/init.d$ systemctl status homebridge
> ● homebridge.service - Node.js HomeKit Server
>    Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
>    Active: active (running) since Wed 2017-05-31 20:33:35 BST; 3min 21s ago
>  Main PID: 27621 (homebridge)
>    CGroup: /system.slice/homebridge.service
>            └─27621 homebridge
>

**Comment by rooi** [comment]
I saw something similar. I @brutella's home app I noticed the the homebridge homekit accessory was blocked. Initially I could unblock it in the app, but after a while this did not work anymore. I had the impression that the evohome plugin was causing this (I recently switched off my thermostat due to summer), but wasn't sure. To tackle the problem and promote a mre stable homebridge, I separated my homebridge accessories into different instances of homebridge. The same thing happened, but just for the evohome instance. So, now I identified the faulty plugin, I can try to solve it (when I have time since other plugins remsin to work fine) and homebridge is much more responsive.
Perhaps this a method you can apply as well?

**Comment by Patrick1610** [comment]
Hi, I am also having this problem. Sometimes my iPhone just sees no response. Without bestrating the homebridge it sometimes just works and stops working. It it completely random. 
I don't use evohome so that can's be the problem. 

How do i run multiple instanties of homebridge to test it? 

Regards Patrick

**Comment by rooi** [comment]
You can run:
homebridge -U path/to/specific/config/location
Put in a config file which just uses one plugin at that location, do the same for other plugins and you're set. You can also apply this to the autostart scripts (remember to use the full path)

**Comment by peteakalad** [comment]
I end up having to restart homebridge to get it working when they stop responding in the home app.  No changes to config just a restart..

**Comment by gstevenson** [comment]
That doesn't seem to work for me unfortunately. I've restarted, rebooted, but still they report as no response. 😕

**Comment by islesailor** [comment]
See #1324 for a solution

**Comment by gstevenson** [comment]
Nice spot! Seems feasible. Can't say for sure it was after an iOS upgrade but I am definitely on 10.3.2 so I'll give it a go when I'm back at my pi.

**Comment by epadillac** [comment]
Anybody testing homebridge on iOS 11?

I cannot make it to work on this version :(
