### ISSUE TITLE
Official Dev Kit

### ISSUE THREAD

**Issue by erfinb** [nfarina/homebridge#1328]
Could this help us develop further? 

https://www.appleworld.today/blog/2017/6/7/apple-opens-homekit-protocol-specification-to-all-developers

**Comment by ankushg** [comment]
Link to official spec: https://developer.apple.com/homekit/specification/

**Comment by justme-1968** [comment]
never expected this to happen :)

there is a Color Temperature characteristic documented that is not included in HomeKitTypes.js from HAP-NodeJS. unfortunately it is not useable if a light also supports Hue and Saturation :(

the new services and characteristics that should appear in iOS 11 are not yet included in the document.

**Comment by ooii** [comment]
> Could this help us develop further?
> 
> https://www.appleworld.today/blog/2017/6/7/apple-opens-homekit-protocol-specification-to-all-developers
Maybe I'm wrong but I think this makes homebridge useless.

**Comment by erfinb** [comment]
@ooii only for those who can understand how to build it from the ground up.  For the rest of us, we can help contribute by troubleshooting but depend on developers to create necessary plugins for items like wemo devices, nest integration, existing security systems, people occupation via pings, etc.  :) I think this just helps build homebridge in a stronger and more understood way with help from Apple Documentation :D

**Comment by ooii** [comment]
You're probably right. Maybe it will make homebridge better.

**Comment by AppleTechy** [comment]
I think it will make Homebridge better for the most part or B) totally remove the need of Homebridge since more Companies would be willing to adopt HomeKit protocols.

**Comment by RXM307** [comment]
Now if only they'd release the airplay/airplay2 spec!

Cheers,

Anthony

**Comment by ankushg** [comment]
It's important to note that this spec is for non-commercial use, so the fact that it's released doesn't necessarily fix all the issues that device manufacturers have with HomeKit.

It does seem to be designed to allow tinkerers (i.e., us) to build things that properly work with HomeKit without relying on reversed engineered hacks, or having to go through the commercial licensing steps.

Either way, seems to be a step in the right direction toward making community projects like Homebridge more feature-complete :)

**Comment by Hedda** [comment]
@RXM307 Apple have published AirPlay 2 API to make the client-side available for third parties

https://developer.apple.com/airplay/

Server-side of AirPlay is of course still fully closed and its encryption not been reverse engineered since iOS9.

**Comment by mrose17** [comment]
@nfarina - may i request that this issue be closed and that people are asked to continue the discussion at https://github.com/KhaosT/HAP-NodeJS/issues/457 ??? thanks!

**Comment by AppleTechy** [comment]
Please continue discussion at KhaosT/HAP-Nodejs#457 as this is not an issue specific to Homebridge rather the underlying protocol system,HAP

**Comment by devbobo** [comment]
@justme-1968 that's not true about ColorTemperatute. I've implemented it for my LIFX platform and it works perfectly if Hue and Saturation are also defined.

**Comment by justme-1968** [comment]
@devbobo that is good to hear. but the documentation clearly says otherwise. where did you get the uuid from? as far as i can see it is currently not included in HAP-Nodejs HomeKitTypes.js.

**Comment by devbobo** [comment]
@justme-1968 I generated a new HoneKtTypes.js myself after downloading the latest HomeKit simulator

**Comment by Hedda** [comment]
https://www.theverge.com/2017/6/8/15761800/apple-homekit-updates-ios-11-easier-build-requirements-wwdc-2017

"On top of these updates to make building HomeKit devices easier, Apple is also expanding what HomeKit can do in ways that consumers will notice. It's adding two new categories of supported products, sprinklers and faucets, and it's adding a bunch of new ways to trigger actions at home.

One of the simpler updates, but a favorite of mine, is an enhancement to the sunrise and sunset triggers. Those can now be offset by some amount of time, so you could, for instance, have the lamps in your home turn on shortly before the sun goes down at night.

Apple is adding temperature triggers, too, so that events can be kicked off when the temperature goes above or below a certain point. And it's getting better at tracking when people are in the house. It'll now track specific people, instead of individual devices, and use that to better tell you when someone leaves or arrives home. In iOS 11, that'll allow HomeKit users to set things to happen when the last person leaves the house or when someone's arriving home to an empty house.

There will also be a way to temporarily turn on certain devices. Apple gave the example of opening a door at night and having outside lights turn on for just a few minutes, instead of turning on and staying on as they’d have to currently."

Nice!

**Comment by Hedda** [comment]
FYI; @pdlove  updated the HomeKitTypes.js on his fork last night: https://github.com/pdlove/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

That look to have everything that is new from Apple's Homekit Accessory Simulator. What the values actually mean are in their public documentation. Color temperature is in Mires and not Kelvin. The conversion is in their doc.
