### ISSUE TITLE
Homenbridge No go after node.js update

### ISSUE THREAD

**Issue by neoTUGA** [nfarina/homebridge#1373]
Hello there,
Trying to get a plugin going that needs node.js  7.6.0, (broadlink em pro plugin) after I update/upgrade node.js to that version, o can’t start homebridge at all. 
Can I get some help please?

**Comment by starlessblack** [comment]
My experience with upgrading nodejs is that you then have to uninstall and reinstall homebridge and all homebridge plugins so they're compiled to run with the correct, new version of nodejs. Probably would want to remove homebridge from Homekit/Home app first, then uninstall homebridge/plugins, then probably delete accessories and persist folders, then probably reinstall the plugins, re-add Homebridge to Homekit/Home app, etc. A bit of a hassle but, that's been my experience the twice I've done it.

**Comment by neoTUGA** [comment]
Oh... :(
Do you know of any good Ubuntu guide to follow then? My install was kind of trying stuff until I got it working. 
Thanks for your help btw.

**Comment by starlessblack** [comment]
Just the reverse of how you installed Homebridge, minus the uninstall/reinstall of nodejs/npm. You'll want to look at the homebridge log/startup to make sure that's why it's failing, but you'll probably see something along the lines of "such and such plugin expected node build 58 but you have 57 installed" or something to that effect. If that's the case, just go through and `sudo npm -g uninstall homebridge-nameofplugin`
`sudo npm -g uninstall homebridge`
`sudo rm -r ~/homebridge/accessories`
`sudo rm -r /var/homebridge/persist`
Then turn right around and reinstall homebridge NPM package and all related plugins. Your config.json is untouched so should still be there. But consider removing homebridge from Homekit/Home app before doing all that, as I've seen it go a little haywire when trying to remove and re-add after the fact.

**Comment by neoTUGA** [comment]
Thanks for all your help, but now when i try to install homebridge after the update and all uninstall i get the error:

`neo@ubuntu:~$ sudo npm install -g homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> ed25519@0.0.4 install /usr/local/lib/node_modules/homebridge/node_modules/ed25519
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge/node_modules/ed25519/build'
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neo/.npm/_logs/2017-07-03T17_57_32_180Z-debug.log
`

Any idea?

**Comment by starlessblack** [comment]
Hmmm, that kind of looks familiar, too. I might've encountered something like that when I tried to upgrade npm from 4.x to 5.x. I think I ended up fixing it by installing an older version of node and then back up to the current version I'd been on.
At this point, you might try downgrading nodejs to a previous version of nodejs. I've had good luck and stability with v7.10.0.
