### ISSUE TITLE
'identify' called upon adding new accessories

### ISSUE THREAD

**Issue by tagyoureit** [nfarina/homebridge#1387]
I'm seeing `accessory.on('identify', function ...` called automatically when adding new platform accessories through Home.  Previously, this wasn't called unless the Identify button was pressed on the screen.

This is a minor challenge because my identify logic takes 4 seconds to cycle lights on/off.  The easy answer would be to keep a count of calls to identify and only run the logic on 2+.  Just want to know if this new change is expected behavior or a bug.

**Comment by ebaauw** [comment]
It's a "feature" of the Home app when adding accessories.  It issues `Identify` when displaying the dialogue to setup the accessory.  I'm afraid other HomeKit apps are copying this behaviour...

Instead of ignoring the initial `Identify`, you might want to call the callback earlier in your `.on('identify')` function, so Home can continue, while the 4-second cycle continues to run in background.

**Comment by tagyoureit** [comment]
Brilliant!  Love it.  Thanks for the tip.
