### ISSUE TITLE
Rooms and Zones

### ISSUE THREAD

**Issue by fritz-fritz** [nfarina/homebridge#14]
I recently got homebridge to work using the Insteon+ app with my Belkin WeMo's. I can directly control my switches (but not my LED Lights due to the library used) with homekit. However, I cannot tell Siri to turn on or off all the lights in a particular room or zone. Siri tells me it cannot find any lights. Is this specific to the WeMo implementation or is there some identifier that the accessories are missing?

I also can't seem to get scene's to work correctly with the Insteon+ app though this is most likely a separate issue.

**Comment by nfarina** [comment]
Hm, unfortunately I don't have any lights myself that are connected to homebridge. And I haven't really tested rooms and zones. So you can control individual switches using Siri but not groups of any kind?

Also I did get scenes working once, the trick was the language - if the scene name is "Movie Time", you can't say "Hey Siri, it's Movie Time!" like you'd want - you have to say "Hey Siri, turn on Movie Time"

**Comment by joepv** [comment]
I setup rooms in the Insteon+ app and Siri understands that. I can ask her: "Turn the kitchen lights on" and she turns on the lights (at full power) in the room called "kitchen". When I ask her to dim the kitchen lights Siri acts random. Sometimes the kitchen lights are set at 30% and sometimes at 0% (off).

Scenes are also working. When I setup a scene I get an app error. But they are available in the Insteon+ dashboard. But at random a light wil not turn on.

I think this is due to the fact that HomeBrigde is unaware of the actuator state. When I control everything with the Insteon+ app it works a little bit better. Or Apple HomeKit is just buggy.

**Comment by alistairg** [comment]
Room and Zone support is actually part of HomeKit, so wouldn't be affected by homebridge.

However, joepv is likely right - the fact that state can change outside of homebridge could well cause problems. This would need developer support on each shim, where possible and/or necessary, to "pull" the external state of a device when requested by HomeKit (Siri) to ensure it's correct....

**Comment by nfarina** [comment]
Closing this for now, as the original question (Rooms and Zones) is answered by it being part of HomeKit :)
