### ISSUE TITLE
ALL of my devices intermittently turning on!

### ISSUE THREAD

**Issue by ahwman** [nfarina/homebridge#1423]
Everything seems to be working well with one major exception that's causing me great frustration. Intermittently, either Siri or Homebridge/Homekit goes crazy and will turn on most if not all of my devices instead of just the device I trigger via Siri. At first I thought that perhaps Siri had misunderstood me and tried to turn on my entire home or room so I purposely changed the name of my home and room to be sure, however this issues continues. Any ideas?

Thanks!

**Comment by snowdd1** [comment]
Try giving better distinguishing service names. If Siri does not recognize the room or service name it usually switches all services of that type. 
EG if you say "turn off the light downstairs" and Siri does not match downstairs to a room or area, it turns off all lights in the home. 

Had that several times, very low WAF.

**Comment by ahwman** [comment]
So based on what you're suggesting, this isn't a homebridge/HomeKit issue but rather related to how Siri matches requests to device names?  That said, I haven 48 devices most of which control my IR devices such as TV, DVR, etc. all belonging to the same room.  Coming from the Amazon Echo which doesn't behave this way, I'm trying to understand what particular commands Siri is getting confused by as there's nothing worse than asking Siri to "Set Comercial Skip" and every light in the house goes on.

**Comment by snowdd1** [comment]
Did you encounter anything like that when using the Home app on the phone/pad? If yes, it might rather be a plugin issue. 
Siri does only react to Service names, not to Accessory names, but that's something the plugins should take care of. Which plugins do you use?

**Comment by ahwman** [comment]
I haven't noticed this issue occur when using the Home app directly from either my iPhone or iPad to trigger devices.  That said, I'm using the ISY-Maker (only plugin I've installed). I'm still unclear by what you mean by "service"  would you please explain?

Thanks for your help! 
Chuck

**Comment by snowdd1** [comment]
When programming plugins, you can/must define names for each "Accessory" (representing a physical device) and each "Service" (representing a capability) , but only the service names are recognized by Siri. That might not be you're issue since you're not programming your own plugin, but are using an existing one.

You should contact the author of your plugin, as I don't think it's a general homebridge issue.

**Comment by ahwman** [comment]
Fortunately it doesn't happen very often, however I will try to report this to the author of this plugin.  I appreciate your help!

**Comment by federic0** [comment]
I have a similar issue, from time to time when I am giving a command to Siri I will pause and when siri just gets the command "switch", then all my devices switch, lights that were ON go OFF and vice versa. This is s small problem unless you also happen to have your garage door controlled by siri...
I am running V0.4.28 and run homebridge openhab and a samsung plugin.

**Comment by mitnits** [comment]
Happens to me all the time (because I speak a little unclear) so what happens, is "Siri, switch mumble mumble mumble" causes Siri to switch everything on....

The only plugin I use is cmdSwitch2 - that is, I have 4 "switches" defined and every one of them can be  turned on/off based on settings in main config.js

I wonder if with homebridge I can limit the "default" behavior only to certain switch or maybe to no switches at all...

**Comment by simonrb2000** [comment]
That would be handy! I have a loud household (lots of kids) and sometimes it thinks it hears turn all lights on instead of Wall Lights for example.

However I think that this is a Siri/HomeKit thing and not a Homebridge issue. I hope I’m wrong and something can be implemented, but I’m doubtful.

Cheers

On 19 Feb 2018, at 09:48, mitnits <notifications@github.com<mailto:notifications@github.com>> wrote:


Happens to me all the time (because I speak a little unclear) so what happens, is "Siri, switch mumble mumble mumble" causes Siri to switch everything on....

The only plugin I use is cmdSwitch2 - that is, I have 4 "switches" defined and every one of them can be turned on/off based on settings in main config.js

I wonder if with homebridge I can limit the "default" behavior only to certain switch or maybe to no switches at all...
