### ISSUE TITLE
Feature request: Custom services and characteristics

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#1453]
Hi,
One easy way is to expand `HomeKitTypes.js` I'm using:

1. build a file `HomeKitTypes-Custom.js` with your custom characteristics and services e.g.:

```js
var inherits = require('util').inherits;
var Characteristic = require('../Characteristic').Characteristic;
var Service = require('../Service').Service;


/**
  * Characteristic "Current Air Pressure"
  */

Characteristic.CurrentAirPressure = function() {
  Characteristic.call(this, 'CurrentAirPressure', '00000102-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT16,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.CurrentAirPressure, Characteristic);

Characteristic.CurrentAirPressure.UUID = '00000102-0000-1000-8000-0026BB765291';

/**
 * Service "Air Pressure Sensor"
 */

Service.AirPressureSensor = function(displayName, subtype) {
  Service.call(this, displayName, '00000101-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.CurrentAirPressure);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
};

inherits(Service.AirPressureSensor, Service);

Service.AirPressureSensor.UUID = '00000101-0000-1000-8000-0026BB765291';
```

2. copy HomeKitTypes-Custom.js into the same hap-nodejs folder as HomeKitTypes.js
(`/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/gen`)

3. add this line a the end of HomeKitTypes.js
```js
var HomeKitTypesCustom = require('./HomeKitTypes-Custom');
```

4. restart homebridge

The disadvantage using this method: you have to copy/edit the files after updating homebridge/hap-nodejs.
A user friendly solution would be to be able to store `HomeKitTypes-Custom.js` inside `.homebridge`. 

Any other suggestions?

**Comment by pdlove** [comment]
Custom Characteristics are very easy. There is no reason to put your custom characteristics in the HAP-NodeJS project.
Here is an example of my custom characteristic file used in Homebridge-smartthings:
https://github.com/pdlove/homebridge-smartthings/blob/master/lib/customCharacteristics.js
You can see where I require it to my plugin here: https://github.com/pdlove/homebridge-smartthings/blob/0b20eae7448a928fa97ad5df2f5566994aec600f/accessories/smartthings.js#L14
And I'm using a characteristic here: https://github.com/pdlove/homebridge-smartthings/blob/0b20eae7448a928fa97ad5df2f5566994aec600f/accessories/smartthings.js#L348

The downside is that Home doesn't typically know what to do with these.
You can also create a custom service the same way.

**Comment by cflurin** [comment]
@pdlove Thanks for your reply.

Sure it's easy if you build a specific plugin.
I'd like to add a flexible solution in my plugin https://github.com/cflurin/homebridge-mqtt
Just now there is a mqtt API for all the functions.
The idea is to provide an easy solution for users to define characteristics and services.
I could extent the mqtt API but that isn't easy to do.

**Comment by pdlove** [comment]
I can't give more detailed advice without being more familiar with the MQTT API, but it is possible to build your characteristics and services on the fly based on the information you get from MQTT and store the UUIDs you use to persist so that new characteristics.... persist. If you have a good API reference I can help further.

**Comment by cflurin** [comment]
OK thanks. I understand that a general homebridge solution isn't easy but imagine homebridge could integrate such a feature, all plugin developers would profit. :-)

**Comment by bohtho** [comment]
HomeKit supports custom characteristics and services, just not necessarily Home.app (yet), but other apps can use them.

Is there any development on this since last comment?

**Comment by justme-1968** [comment]
you can use custom characteristics and services since forever.

even completely end user configurable as used in homebridge-fhem for example.

**Comment by bohtho** [comment]
Sorry for not being clear. I was thinking of a built in API in Homebridge for easily applying custom characteristics and services.

**Comment by justme-1968** [comment]
what kind of api do you want?

you can use exactly the same existing addCharacteristic, setProps, on get/set functions as you would with 'standard' characteristics.

**Comment by iangray001** [comment]
My understanding is that Homebridge currently defines a set of supported accessories and the characteristics that they may contain ahead of time in [a single typescript file](https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts). Yes, plugins could add to this, but it is still a "fixed ahead of time" model.

From [HomeKit.ts](https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts), unless I misunderstand something, a Lightbulb must have the `On` characteristic, and may have **at most one of** `Brightness`, `Hue`, etc. 

However, if you play with Apple's Homekit Accessory Simulator you'll see that in reality you can arbitrarily add and remove custom parameters at runtime from a Lightbulb. [Here is the Eve app showing a standard Lightbulb accessory](https://imgur.com/a/VViuT1q) but with additional boolean, int and string characteristics. This is all standard Homekit.

Am I right in understanding that Homebridge does not support this?

**Comment by nfarina** [comment]
Homebridge should allow you to do anything you can do in HomeKit Accessory Simulator - including adding custom characteristics to your heart's content. Note that although Homebridge won't "reject" any crazy configuration you come up with, Siri/HomeKit on the phone might!

**Comment by iangray001** [comment]
Thanks for the reply. Again, please excuse if I've made an error, but I _think_ I'm correct.

As far as I can see, there is no "Custom" characteristic in `HomeKit.ts` so there appears to be no interface with which to actually add these characteristics to my accessory. I painstakingly crawled that file a few weeks ago looking for some characteristic that would take an 8 bit integer which I could repurpose, but didn't notice one.

Indeed over in `homebridge-mqtt` where people are looking at this issue (or in this very thread in fact!), the conclusion is that one needs to write a homebridge plugin which extends `HomeKit.ts`. Is this not the case?

**Comment by NorthernMan54** [comment]
Ian,

For sample plugins that do this today look for ones that support the eve historical graphing functions like my mcuiot and dht plugins there are numerous examples

But to Nick’s point the custom characteristics are kinda useless unless the HomeKit client app supports it.  The home app from Apple is pretty rigid in regards to what data it displays.  Unexpected characteristics are not shown

**Comment by iangray001** [comment]
@NorthernMan54 `Home.app` does not, but the Eve app shows them perfectly fine when added by the Accessory Simulator, as I exampled in my initial comment. 

So to clarify, you're saying that Homebridge does not support Homekit Custom characteristics without being extended with a plugin?

**Comment by nfarina** [comment]
OK so it's been a while but I believe that you can just "extend" the base `Characteristic` class the same way all the stuff in `HomeKit.ts` does. Just generate your own random UUID value and write something similar to any of the other `Characteristic` subclasses in `HomeKit.ts`. For instance, here's a custom characteristic for "shield levels" on a starship (if you have one laying around):

```ts
export class ShieldLevel extends Characteristic {

  static readonly UUID: string = '000000CE-0000-1000-8000-0026ABCDEF01'; // random

  constructor() {
    super('Shield Level', ShieldLevel.UUID);
    this.setProps({
      format: Formats.UINT32,
      maxValue: 100,
      minValue: 0,
      minStep: 1,
      perms: [Perms.READ, Perms.WRITE, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}
```

**Comment by iangray001** [comment]
Again, thanks so much for the quick replies, but I think you're answering from a very different perspective.

In Homekit, **the accessory itself** can make up its custom characteristics on the fly. Play with the Simulator and see.

In Homebridge, it is looking to me that all potential accessories and characteristics **are defined ahead of time**, and new things require one to edit source code, or to write a plugin which extends Homebridge. 
i.e. Homebridge doesn't actually support all of Homekit.

**Comment by nfarina** [comment]
Ah, I see what you mean. So Homebridge behaves exactly like HomeKit Accessory Simulator (or any other HomeKit client), except that you need to restart it before any changes to accessories/services/characteristics will be "published". This is how HomeKit is intended to be used: your accessory publishes a JSON definition of everything it supports, and that definition (services and characteristics) is not expected to change - although HomeKit _does_ support changes to it, and that's what the HomeKit Accessory Simulator is doing.

I don't see what the use case would be for changing services/characteristics on the fly? Maybe it would help to understand what kind of end user experience you desire?

**Comment by iangray001** [comment]
It not about **dynamic** characteristics, and more about **custom** ones, as defined by the accessory.

I have built an animated lighting system. It exposes itself as an accessory with a `Lightbulb` service and therefore can have `On`, `Hue`, `Saturation`, and `Brightness` characteristics. I want to expose further custom characteristics to control animation parameters. Homekit allows for Custom characteristics that have a name, data type, min/max values etc. As far as I can see, Homebridge does not.

It should not be required to edit the code of Homebridge to do this, because Homekit devices do this all the time. Yes, access to these custom characteristics requires that the user use a more capable app than `Home.app`, but this is how Eve and others work.

**Comment by nfarina** [comment]
Just to be totally clear - you're trying to add a new kind of Lightbulb service without writing a plugin?

**Comment by iangray001** [comment]
No. In Homekit, accessories can support standard services but which have custom, device-defined characteristics. I'm trying to make use of them.

A device can say, for example, that it supports a `Lightbulb` service, but with in addition to the normal characteristics, a `bool` characteristic, a `uint8` characteristic, and a `string` characteristic. [Here is what such a device looks like when viewed in Eve.](https://imgur.com/a/VViuT1q)

Notice I did not have to edit Apple's code running on my Apple TV for this to work.

It seems that Homebridge has forgotten about these custom characteristics and has defined services to be immutable and defined at (Homebridge) compile time. 

Again, yes, Homekit supports these things appearing and disappearing dynamically but I don't need that. I _do_ need for when a device registers its services for it to be able to include its custom characteristics.

**Comment by nfarina** [comment]
OK, thank you for clarifying. I would ask you to take a closer look at the first answer to the original question up top. Plugins can for sure expose custom characteristics. You don't have to "hack" Homebridge or HAP-NodeJS itself to do this. Characteristics are just objects with UUIDs and some essential properties, like the ones you mention, `uint8` or `string` etc.

You don't even have to subclass Characteristic to make your own stuff. Just make a new instance of the Characteristic class and pass in your UUID and set the properties, then add it to a Service like any other characteristic. Example (untested) code:

```ts
class ShieldLevel extends Characteristic {

  static readonly UUID: string = '000000CE-0000-1000-8000-0026ABCDEF01'; // random

  constructor() {
    super('Shield Level', ShieldLevel.UUID);
    this.setProps({
      format: Formats.UINT32,
      maxValue: 100,
      minValue: 0,
      minStep: 1,
      perms: [Perms.READ, Perms.WRITE, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}

class StarshipAccessory {
  constructor(log, config) {
    this.shieldService = new Service.Switch("Shields");
    this.shieldService.addCharacteristic(ShieldLevel);
  }

  getServices() {
    return [this.shieldService];
  }
}
```

**Comment by iangray001** [comment]
Sorry Nick, I really do appreciate you taking time here, but I don't think you're engaging with what I'm saying. 

I'm not aiming to, and shouldn't have to, touch the code of Homebridge. I'm an accessory developer trying to use Homekit features that it appears are not supported by Homebridge.

I think the source of the confusion here is that you seem to be under the misapprehension that `Lightbulb` may only ever contain the four characteristics. This is not true. `Lightbulb` may contain any number of characteristics. One mandatory, three defined optional, **and as many other custom ones as the accesssory defines**.

It is possible for an accessory to talk to an **entirely standard** Homekit server and say "I support a Lightbulb but it has a `uint8` parameter called `WhateverIWant`". 

People keep telling me to edit Homebridge, but this makes no sense because what I want to do is standard Homekit.

**Comment by nfarina** [comment]
You should not be editing Homebridge - I apologize if it seems like I'm asking you to do that. The code I pasted is plugin code. If you are developing a custom accessory and wishing to expose it to HomeKit, then you need to either run your own HAP-NodeJS server inside your accessory, or write a plugin for Homebridge so that other end-users can use your accessory by way of Homebridge.

You can make a `Lightbulb` contain as many characteristics as you want—custom or otherwise—provided you are writing a plugin for Homebridge, you can define your accessory to be whatever you'd like.

So there are three pieces here:

  - Homebridge, the open source platform that end-users must install and run themselves
  - Homebridge Plugin, which the end-user must install and set up themselves
  - Your hardware accessory (lightbulb), which the end-user gets (somehow) and sets up themselves.

Provided that the user sets up those three components, your plugin can do whatever it wishes within the known limits of the HomeKit API.

Am I making sense or just making things more confusing?

**Comment by nfarina** [comment]
I'm on Slack for the next hour btw - it might be easier to chat there! You can find the link from the Homebridge README.

**Comment by HSkul** [comment]
Apologies for bringing this back from the (almost) dead but I'm about to try to implement the approach @nfarina suggested here above for Airthings Wave radon detector (I'm a bit surprised that Apple hasn't defined radon concentration characteristics in Homekit, that's a big oversight) using homebridge-bluetooth for communication.  So the reason I'm writing is that I'm not sure this is the approach Apple had in mind.  Apple says that "manufacturers can create custom **types**" [link](https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types)
 Isn't that different from creating a custom characteristic?  I'm not an expert on this but doesn't that mean that you just use some sort of a 'generic' characteristic for the value and that you just define it with the custom type?  This should work with the Home app as Apple wouldn't suggest to manufacturer to do something custom that then wouldn't work with the Home app.  Or maybe I'm completely interpreting this wrong.
P.S. Thanks for a fantastic project.  I haven't had this much fun with computers since my BBC B.

**Comment by ebaauw** [comment]
> as Apple wouldn't suggest to manufacturer to do something custom that then wouldn't work with the Home app

Where did you get that idea?  In fact they actually suggest just that: the manufacturer needs to supply their own HomeKit app to handle the custom characteristics.  Even worse: Home doesn’t even support all standard characteristics.
