### ISSUE TITLE
Externally provided scenes

### ISSUE THREAD

**Issue by JonSilver** [nfarina/homebridge#1458]
Hue has the ability to export its own scenes to HomeKit so that HomeKit can activate them. Would it be possible to add this kind of external scene support to Homebridge so that a plugin like homebridge-mqtt could tell, for example, a Node-Red flow to set a particular scene?

To illustrate further, I might have a node-red flow that switches everything off last thing at night, which I already access in various ways. I don't want to have to duplicate the scene in HomeKit, so I "import" the scene using homebridge & homebridge-mqtt, giving me Siri support and enabling me to set this external scene through the HomeKit apps.

**Comment by pdlove** [comment]
The reason Hue can do it is because the app on the phone has access to your HomeKit database. If an iPhone app were written to interact with your HomeKit database on your phone then it would be possible. The Hesperus app was written to interact with Homebridge but I don’t think it supports anything like this.
