### ISSUE TITLE
sudo systemctl status showing "Line 1-x/x (END)" and I have to type "wq" to exit

### ISSUE THREAD

**Issue by guagsak** [nfarina/homebridge#1465]
I have installed new homebridge and autorestart with systemd. When I type sudo systemctl status, this time there is always "Line 1-x/x (END)" all the time while there was no problem in previously install.

Anyone know how to get rid of this, since I have to type "wq" to exit all the time.
![show-line-1-x](https://user-images.githubusercontent.com/27913997/29759827-26664a34-8be9-11e7-908d-712dba7fc65a.jpg)

**Comment by sendorm** [comment]
If you use the right arrows you can see the whole message displayed. That is a plus, but it's rather annoying that it won't quit itself. I use ctrl+c  to close the lines. I would like to learn a solution to this also.

**Comment by SummerFrog** [comment]
I saw you already added the homebridge as a system service, this is the command that I use which will give me the correct output with no `lines XX/XX`, the command is `sudo systemctl status -l homebridge@homebridge.service`. Since I run homebridge as the homebridge user I created, so you might wanna change that.

**Comment by hasantahsinakin** [comment]
I was searching this on internet and found the solution here: https://unix.stackexchange.com/questions/356753/bash-always-outputs-to-less-how-can-i-turn-this-off

Simply add this to **/etc/profile**:

`export SYSTEMD_PAGER=cat`
