### ISSUE TITLE
homebridge stops when internet down ?

### ISSUE THREAD

**Issue by roe1974** [nfarina/homebridge#1486]
My homebridge is running perfect. Only when the internet is down, homebridge (4.0.22) stops immediatly ... plugins are homematic, nuki und tado-ac
any idea ?
richard

**Comment by nxtpl** [comment]
Similar here. Homebridge works great until Netatmo fails to connect to its external API.
Would be great to have some fallback for such cases.

**Comment by SummerFrog** [comment]
I believe when the internet is down, your internal network is down, too. So your homebridge loses it connection immediately to all your connected devices, which are connected by the internal network. Unless you have a stable internal network, otherwise it will down whenever your network is down. (Just my own opinion by tested it several times)

**Comment by mr-reamer** [comment]
That doesn't sound right. An internal network should be independent of the internet...

**Comment by SummerFrog** [comment]
Not sure about this, but when I shut down my external network, the internal network is down too.
