### ISSUE TITLE
synergies with homestar and iotDB

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#149]
I wonder if there are any synergies that can be made between homebridge, homestar and iotDB

they are other projects with similar bridge to accessory frameworks..

take a look at their rather impressive line up of accessories...

https://www.npmjs.com/~dpjanes

**Comment by SphtKr** [comment]
Tricky. Giving it a cursory glance, one of two things might make sense to pursue:

1. Build a platform in Homebridge for IoTDB
2. Home Star to integrate Homebridge as another front-end

Really both of these are the same, it's just a question of which project/repo it's done it. Looks to me like Home Star is a user front-end to IoTDB, so Homebridge+HomeKit apps could be another front-end. Or, with option 1, you would have the option of implementing device support in IoTDB instead of with an accessory or platform in Homebridge.

The downsides: I don't know all the API surface of IoTDB, but from my experience working on the ZWay server platform, it seems to me that IoTDB, HomeKit, and the ZWay vDev interface (among others) are all trying to solve the same problem: unify differing device APIs and capabilities into a single API/format. But doing that has tradeoffs. For instance, working with the ZWay vDev API, it breaks up all the sensors in a single device into separate virtual devices (great for generalizing device function). But in HomeKit, it makes more sense to have all those sensors associated with a single accessory--so I had to figure out how to reassemble the original device. Going through two layers of abstraction you'll lose some options, or make things more difficult...just a question of where.
