### ISSUE TITLE
How to use MQ-2 Sensor?

### ISSUE THREAD

**Issue by V1ntex** [nfarina/homebridge#1499]
Please tell me how to use the sensor MQ-2  + arduino + RPI3? Its Real?

**Comment by mrose17** [comment]
the first question is simple, but has a very complex answer.

if you had an MQ-2 sensor and wanted to export it via homebridge, you would need to do two things:

first, you need to find the appropriate homekit characteristics that allow you to model the sensor. here is the ["standard' list](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js) ... if you can't find what you need, feel free to submit an issue to the ["non-standard list of extensions"](https://github.com/homespun/hap-nodejs-community-types/blob/master/types.js) repository.

in the case of the MQ-2 sensor, your best bet is to call it an [air quality sensor](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2560-L2584) because as the "Note" says on the [page](http://wiki.seeed.cc/Grove-Gas_Sensor-MQ2/):

         The sensor value only reflects the approximated trend of gas concentration in a
         permissible error range, it DOES NOT represent the exact gas concentration.
         The detection of certain components in the air usually requires a more precise and
         costly instrument, which cannot be done with a single gas sensor. If your project is
         aimed at obtaining the gas concentration at a very precise level, then we don’t
         recommend this gas sensor.

your job would be to decide how to map the voltage reported by the sensor to an [air quality value](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L114-L136). or perhaps you can use the `Rs/R0` ratio as the basis for the calculation. the key thing is to understand how to model the sensor using the characteristics and services available via homekit, preferably using the standard objects rather than the non-standard ones.

second,  you just need to have something that periodically reads the sensor and then updates a plugin. depending on your hardware, you may have to do this in two steps

find a way of getting periodic readings from the sensor. the grove seed sites suggests using an arduino and that's a good way of doing it. the only problem is that you're not going to be running homebridge on an arduino, so you're going to need a way of getting it to a system capable of running homebridge. you can look at [homespun-arduino](https://github.com/homespun/homespun-arduino) to see one way of doing that.

two years ago i started, but never finished, work on [homespun-grovepi](https://github.com/homespun/homespun-grovepi) which talks to a [grove shield for the RPi](https://www.seeedstudio.com/GrovePi%2B-Starter-Kit-for-Raspberry-Pi-A%2B%2CB%2CB%2B%26amp%3B2%2C3-%28CE-certified%29-p-2572.html). the basic idea again is to talk to the sensor. both of these repos read from the sensor and then send out a multicast UDP packet using a format called TSRP.

finally, you need to have a way of receiving the sensor reading over the network. you don't have to use TSRP, knowing that it came from an MQ-2 and then implementing a plugin that corresponds to the sensor.

doable, but not simple. good luck!
