### ISSUE TITLE
Best Practice to host Shims?

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#151]
@nfarina
Traditionally HomeBridge hosts Accessory as well as Platform Shims.
However separating Shims from HomeBridge could be more flexible and practicable. One solution could be to collect all the Shim-Links of the repositories in the Homebridge-Wiki. This way it would be easier for the authors and for you to maintain the Shims.

What's your opinion?

**Comment by nfarina** [comment]
So first step in my opinion is the move shims into their own npm modules so that Homebridge users aren't forced to download all possible requirements. There's a small discussion about this in the [roadmap](https://github.com/nfarina/homebridge/wiki/Roadmap#real-plugin-architecture).

Once that's done, we'd just need a simple npm-based discovery mechanism and we could write a little Javascript thing for the website.

**Comment by cflurin** [comment]
npm modules will be great. With ````npm outdated```` I've got this output:
`````
ad2usb                   1.0.3     git     git  ad2usb
elkington                0.1.0     git     git  elkington
hap-nodejs             MISSING     git     git  hap-nodejs
harmonyhubjs-discover    1.0.1     git     git  harmonyhubjs-discover
request                 2.49.0  2.49.0  2.61.0  request
unofficial-nest-api      0.1.4     git     git  unofficial-nest-api
wink-js                  0.0.5   0.0.5   0.0.9  wink-js
xmldoc                   0.1.4   0.1.4   0.3.1  xmldoc
````
Most of these aren't needed for my application.

**Comment by snowdd1** [comment]
I just checked the npm node package and found a rather simple to use api for dynamically installing packages. 
Maybe I can make an example from the KNX platform with a dynamic stub loader later today as a discussion showcase.

**Comment by cflurin** [comment]
@snowdd1: cool, I've installed homestar https://github.com/dpjanes/iotdb-homestar.
They already use an install for pugins, I think this is the way we should go.

**Comment by snowdd1** [comment]
According to their readme, the end user has to install the plugins himself.

>Here's how you make your Home☆Star / IOTDB installation talk to WeMos.
>$ homestar install homestar-wemo
>Need to talk to something else? See docs/modules.md for a list of current modules.

I think that would be ok from a usability perspective, but from the discussions (#41) I thought we wanted to go a step further and load the packages upon finding a platform in config.json, or in the next iteration, if the user clicks a flashy icon in the web interface to enable the platform.
And the npmi package is exactly the thing I intended to write, so I don't have to after all!

**Comment by snowdd1** [comment]
> Maybe I can make an example from the KNX platform with a dynamic stub loader later today as a discussion showcase.

And I did:
https://github.com/snowdd1/homebridge/tree/dynamic-platform
and the npm packaged shim: homebridge-knx which gets automatically installed and loaded upon server start
(https://github.com/snowdd1/homebridge-knx)

**Comment by cflurin** [comment]
@snowdd1: Thanks for your example. Did you see the "npm install programmatically" [here] (https://docs.npmjs.com/api/install) ?
I didn't try yet but it seems, we can install packages using npm.

**Comment by snowdd1** [comment]
@cflurin 
Yes I saw it, and the [npmi package](https://github.com/maxleiko/npmi) I used is using exactly these API calls, just neatly wrapped so you do not have to car about the details.

It works very nicely (with https://github.com/snowdd1/homebridge-knx V.0.0.3), I just have an issue with peerDependency to hap-nodejs as it is no package/not npm listed, just a repo (that's why 0.0.4 isn't starting the first time, and does the second time when https://github.com/snowdd1/homebridge-knx is already installed by the first attempt).

**Comment by cflurin** [comment]
Ok, let's see what @nfarina decides to go ahead.

**Comment by dpjanes** [comment]
Have you guys seen my HomeStar project? It handles a lot of the things you guys are talking about, especially modularizing installation. The "secret sauce" is that all Things are described semantically using IOTDB, so instead of thinking about "let's manipulate a WeMo" it's "I'm manipulating a switch" or even "I'm manipulating a coffee machine" by updating the metadata. This seems like a natural fit for what you're trying to accomplish here.

https://github.com/dpjanes/iotdb-homestar

Note: Windows support is crap, working on that right now.
