### ISSUE TITLE
New iOS11 warnings in device page

### ISSUE THREAD

**Issue by maragelis** [nfarina/homebridge#1516]
Has anyone  else seen these warnings, or have I done something wrong ? 
The accessory was created after the update to iOS11.

[https://photos.app.goo.gl/eWXVSeCjlX4CWYfL2](https://photos.app.goo.gl/eWXVSeCjlX4CWYfL2)

**Comment by maragelis** [comment]
The device wouldn't show up in the home app, I had to add it by first giving the app the pass code then I was able to add it. But its showing that error .

**Comment by Tiger519** [comment]
It is causing any issues with functionality? I haven't updated yet and am wary of doing so. I do recall I got that message when adding the bridge in iOS10, but it doesn't appear on the bridge screen within the Home app like in your picture. Since it's not a true HomeKit device, the warning is expected and as long as it's not causing you any functional issues you definitely don't need to worry about it.

**Comment by maragelis** [comment]
no its not causing any issues. just wanted to mention it

**Comment by tvillingett** [comment]
I don't have the photos to back it up, but something similar was written in iOS 10 as well

**Comment by NathanDai** [comment]
it also happened in my ipad in ios10,after taken homebridge ,the icon became grey,and the homebride didn't work

**Comment by eruizdechavez** [comment]
I am using a Wink hub in my installation and any of my devices is HomeKit certified. I do get those messages but I am able to control everything without any issues.
