### ISSUE TITLE
No Response on all devices

### ISSUE THREAD

**Issue by jack-hub** [nfarina/homebridge#1520]
Homebridge and plug-ins all start and seem to be running normally. I've tried on my Mac and on my Rpi3 (primary). AppleTV shows connected. But iPhones all show No Response on every accessory.

I would assume this is related to iOS 11 and the new tvOS, but I can't be sure.

I updated homebridge and the plug-ins (Smartthings and Wink) just to see if that would help, with no change in results. I'm stumped usually rebooting everything solves issues, but not this time.

**Comment by broux2** [comment]
I am seeing the same thing after updating to iOS 11. I see homebridge is gathering data correctly in terminal. I am also getting notifications from the home app when my door unlocks yet I am getting no response on all devices.

I just tried other HomeKit app such as EVE and Hesperus and they are working fine. Seems to be an issue with the Home app only.

**Comment by 13mralex** [comment]
I'm also having the same issue. I can verify that Homebridge is working properly, since the Alexa plugin is working perfectly. I'm currently running iOS 11.1 Beta 1, and the Home app is pretty much useless. It will sometimes work, but it is terrible slow. It's either stuck on updating or it just says No Response. I have Eve as well, same thing. I also recently updated to tvOS 4, so I'm not sure if that's what's causing the issue.
I don't know if it's something that needs a quick patch in Homebridge, or if it's a bug in Apple's Home app.

**Comment by Lemongrass3110** [comment]
I've got the same issue.
On my iOS 11 devices all accessories are shown as "no repsonse". When I use my iPhone on iOS 10(still have 32 bit apps that were not updated yet) everything works properly.

Judging from your updated comment @13mralex I also have one accessory that goes missing all the time. I did not find out why yet though as everything in the raspberry's process looks fine. It says 7 devices mapped, but Home app only shows 6 after some time. How were you able to fix your broken accessory?

**Comment by picnicbob** [comment]
I don't have much to add except that I have this problem too. I think it was fine until I updated to iOS 11.0.1.

**Comment by Lemongrass3110** [comment]
It is happening on iOS 11.0.0 and 11.0.1 for me. 10.3.3 works fine though. :-/

**Comment by jack-hub** [comment]
Anyone having any luck figuring this out? I've tried both my Rpi3 and iMac, still no luck at all. iOS 10 or 11... no luck. Stumped.

**Comment by jack-hub** [comment]
iOS 11 update fix that worked for me...
If you have a lot of stuff in your home, you might want to try this last.

Shutdown homebridge and kill the home app.
Change the user name and pin in the config.json file.
Restart the home app and see if it works. If so, STOP and be happy.
<<<(The next step requires you to re-do all room assignments, zones, and automations!)>>>
Delete the Homebridge from the app. (Details, remove). Kill the app and restart it.
Add the homebridge using the new pin.
For me, it immediately asked me to setup all my devices assigning them back to the rooms.
If that doesn't work, see @jeroen1973 post from Aug 20/13 days ago. His post was the basis for this.

**Comment by picnicbob** [comment]
Thanks @jack-hub 
This (for now) has solved it for me and was pretty painless:
• Stop homebridge
• Edit config.json to change "username" and "pin" values slightly (I incremented each by 1)
• Start homebridge
• Force-close Home app on iPhone
• Open Home app on iPhone, see Homebridge as unavailable
• Add the "new" Homebridge accessory as 'Homebridge2'
• Don't bother configuring new accessories, just hit Next a bunch of times and make sure they're reported as responsive
- At this point I had duplicates of all my Homebridge accessories with the originals reporting "Not Available" and the new ones working but with default names, rooms, and icons. Good, but not great.

• Stop Homebridge
• Revert changes to config.json (decrement "username" and "pin" by 1 in my case)
• Start Homebridge
• Force-close Home app on iPhone
• Open Home app on iPhone
- At this point I saw my original "Homebridge" as available and all my original accessories were back up and working with the new unconfigured accessories reporting not responding / unavailable.
• Delete "Homebridge2" and I'm back up and running with everything the way I had it set up originally.

**Comment by 13mralex** [comment]
@Lemongrass3110 My broken device was an RGB LED WiFi controller, and it had lost connection to my network. Because of that, it had caused my Home app to render useless. After resetting the LED controller and connecting it back to my network and then restarting Homebridge, everything has been working fine. I also run my Homebridge on a Mac Mini running Windows 10. I have found it easy to run on Windows. I have a Pi, but I don't really want to start over. I have also recently switched from wireless to wired, but that hasn't really made a difference in Homebridge performance.

Also note that even though my LED controller was offline, it still showed up on my devices on my Home app since it was still in my config file. After the issue was resolved, I removed the bridge from Home and re-added it back, and everything is still working fine.

**Comment by iRonin** [comment]
In my case the issue was caused by homebridge-roomba980 - removing the accessory (trial and error) and restarting homebridge was enough to see other ones working on the Home app.

**Comment by omriavital** [comment]
After spending almost 3 hours on that... @iRonin 's answer was also true to mine: it was the roomba plugin that was causing this mess... (after removing the plugin, had to do the 'resetting' of changing user name etc. for this to work again), but at least it's now fixed 😬
