### ISSUE TITLE
Homebridge installation problem

### ISSUE THREAD

**Issue by KhaosT** [nfarina/homebridge#1521]
Temporarily use this to discuss the installation problem.

**Comment by KhaosT** [comment]
@orgalinq It's interesting npm install succeeded but then there is no thing in the directory. Can you repeat the full process as following:
```
sudo systemctl stop homebridge
sudo rm -rf /usr/local/lib/node_modules/homebridge
sudo npm install -g --unsafe-perm homebridge
```

and then run homebridge to see if dns_sd error still happen...

**Comment by orgalinq** [comment]
KhaosT, this is what I got after executing your instructions:
pi@raspberrypi:/ $ sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/29/2017, 10:22:20 PM] Loaded plugin: homebridge-edomoticz
[9/29/2017, 10:22:22 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[9/29/2017, 10:22:22 PM] ---
[9/29/2017, 10:22:22 PM] config.json (/root/.homebridge/config.json) not found.
Load homebridge-edomoticz.eDomoticz
/usr/local/lib/node_modules/homebridge-edomoticz/index.js:96
  this.server = config.server;
                      ^

TypeError: Cannot read property 'server' of null
    at Object.eDomoticzPlatform (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:96:23)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
.....

**Comment by orgalinq** [comment]
and this:

pi@raspberrypi:~ $ sudo systemctl status homebridge.service –l
● homebridge.service - HomeBridge Service
   Loaded: loaded (/lib/systemd/system/homebridge.service; enabled)
   Active: active (running) since Fri 2017-09-29 22:34:05 CEST; 5min ago
 Main PID: 641 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─641 homebridge

Sep 29 22:34:48 raspberrypi homebridge[641]: ┌────────────┐
Sep 29 22:34:48 raspberrypi homebridge[641]: │ 031-45-154 │
Sep 29 22:34:48 raspberrypi homebridge[641]: └────────────┘
Sep 29 22:34:48 raspberrypi homebridge[641]: [9/29/2017, 10:34:48 PM] Homebridge is running on port 51826.
Sep 29 22:34:50 raspberrypi homebridge[641]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000...ing anyway.
Sep 29 22:34:50 raspberrypi homebridge[641]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000...ing anyway.
Sep 29 22:34:52 raspberrypi homebridge[641]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000...ing anyway.
Sep 29 22:34:52 raspberrypi homebridge[641]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000...ing anyway.
Sep 29 22:34:53 raspberrypi homebridge[641]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000...ing anyway.
Sep 29 22:34:59 raspberrypi homebridge[641]: [9/29/2017, 10:34:59 PM] [eDomoticz] Successfully connected to MQTT broker.

● \xe2\x80\x93l.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by KhaosT** [comment]
@orgalinq running Homebridge directly failed because your configuration file is not at the expected location `config.json (/root/.homebridge/config.json) not found.`

However, the service side should work,
```
Loaded: loaded (/lib/systemd/system/homebridge.service; enabled)
Active: active (running) since Fri 2017-09-29 22:34:05 CEST; 5min ago
```

What does iOS side show now?

**Comment by orgalinq** [comment]
On my Iphone I see now the Homebridge icon. After typing the code noting happens. Ios is searching.
Its better now than a few hours ago, but no access.
My config.json is at /home/pi/.homebridge/
There are also the directories persist and accessories.

**Comment by orgalinq** [comment]
I can't access /root, permission denied!

**Comment by orgalinq** [comment]
Yes, that's the case.

**Comment by orgalinq** [comment]
I understand that the system is asking for config.json in /root/.homebridge, but it is not there. 
It is in  /home/pi/.homebridge. Also dir persist and dir accessories is there.
Where can I change the location were the system is looking?

**Comment by KhaosT** [comment]
@orgalinq let's try this so we can get more logs. First stop the service, and then run `DEBUG=* homebridge -U /home/pi/.homebridge`
After that, go to Home app, try pair with the bridge and see if there are any logs from homebridge.

**Comment by orgalinq** [comment]
KhaosT, 
I executed your instructions, but nothing happens. I see the accessorie icon on my Iphone and can type the code but nothing happens except the well known wheel wich turning right above in the screen. Its frustrating. I'm busy with áll this for two day's now. And again it is almost one o-clock nights.
Maybe its better to setup everything new......

For now, thank you very much for your help and spending your time.

**Comment by orgalinq** [comment]
Hi KhaosT,

Today, for a clean start, I recovered Homebridge server completely with an disk-image of the working server.  
1. In Homekit all the accessories were detected and further everything looked good, no errors. 
A connection after typing code 031-54-154 was not possible.
2. **sudo apt-get update && sudo apt-get upgrade**
Result: the same situation as 1
3. **sudo systemctl stop homebridge**
**sudo rm -rf /usr/local/lib/node_modules/homebridge**
**sudo npm install -g --unsafe-perm homebridge**
Now I have Homebridge version 0.4.28
Result: the same situation as 1
4. Removed all the files in directories persist and accessories
Result: the same situation as 1 (all de files in persist and accessoires were new created)
5.  **sudo npm update -g npm**
I got a message: Update available 5.0.3 → 5.4.2,    Run npm i -g npm to update
So I did:
**sudo npm i -g npm**
Result: the same situation as 1
6. This is what a get after **sudo systemctl status homebridge.service -l**
● homebridge.service - HomeBridge Service
   Loaded: loaded (/lib/systemd/system/homebridge.service; enabled)
   Active: active (running) since Sat 2017-09-30 15:16:21 CEST; 27min ago
 Main PID: 603 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─603 homebridge

Sep 30 15:16:59 raspberrypi homebridge[603]: [9/30/2017, 3:16:59 PM] [eDomoticz] Initializing platform accessory 'Slaapkamer'...
Sep 30 15:16:59 raspberrypi homebridge[603]: [9/30/2017, 3:16:59 PM] [eDomoticz] Initializing platform accessory 'Thermostaat'...
Sep 30 15:16:59 raspberrypi homebridge[603]: [9/30/2017, 3:16:59 PM] [eDomoticz] Initializing platform accessory 'Woonkamer'...
Sep 30 15:16:59 raspberrypi homebridge[603]: [9/30/2017, 3:16:59 PM] [eDomoticz] Initializing platform accessory 'Zijraam'...
Sep 30 15:16:59 raspberrypi homebridge[603]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Sep 30 15:16:59 raspberrypi homebridge[603]: ┌────────────┐
Sep 30 15:16:59 raspberrypi homebridge[603]: │ 031-45-154 │
Sep 30 15:16:59 raspberrypi homebridge[603]: └────────────┘
Sep 30 15:17:00 raspberrypi homebridge[603]: [9/30/2017, 3:17:00 PM] Homebridge is running on port 51826.
Sep 30 15:17:00 raspberrypi homebridge[603]: [9/30/2017, 3:17:00 PM] [eDomoticz] Successfully connected to MQTT broker.

No errors and everything looks ok but a Homekit connection is not possible. 
_**My Homebridge is running on a RPI2 modelB. So I have to use node-v4.0.0-linux-armv6l
What do you think, can that be the problem?**_
So far, I don't know what I can/should do further.

Kind Regards,
Wallgarden

**Comment by orgalinq** [comment]
Hi KhaosT,

I'am happy to tell you that after switching my Iphone off and back on, I got connection with Homebridge!
Everything is working. No more missing accessories. I hope it will stay functioning.
Thank you again for your help.

Kind Regards
Wallgarden

**Comment by KhaosT** [comment]
lol rebooting iPhone added the issue? Guess that's another bug on Apple's side then. It would be great if you can update this issue after running homebridge for a while so we can be sure if the issue is actually gone or just temporarily disappeared.

**Comment by orgalinq** [comment]
Yes, I will do.

Kind Regards,
Wallgarden

(IPhone bericht)

**Comment by orgalinq** [comment]
Hi KhaosT,

Just to let you know:
Two weeks after the IOS update and a clean start of Homebridge from an old disk-image (as described above) my PI is still running without any problem. I'am very satisfied with that result.

Kind Regards,
Wallgarden

**Comment by toshibochan** [comment]
If you runing home bridge from root first! 
Sudo su 
cd ~/.homebridge
And make you config.json

If you runing homebridge in normal user:
cd ~/.homebridge
And make config.json

**Comment by toshibochan** [comment]
On root type:
Sudo su
homebridge

On normal user type:
Homebridge
