### ISSUE TITLE
bash: homebridge: command not found

### ISSUE THREAD

**Issue by jack-hub** [nfarina/homebridge#1522]
I updated my Pi3, Node, NPM and installed Homebridge
Installation went smoothly, but it won't execute.

pi@raspberrypi:~ $ homebridge
bash: homebridge: command not found

I feel like a real dummy, but I can't find homebridge anywhere. I can find the config.json, and the plug-ins... but not homebridge.

I guess my DOS roots made me think it isn't in the path, but you have to know where it is to begin with... :(

**Comment by AndreiFAD** [comment]
this has solved me:
    sudo nano ~/.bashrc
Add this line:
    PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"
and run:
    . ~/.bashrc

**Comment by dmikhalsky** [comment]
you can get homebridge location with "which homebridge" command, and then include it into path as recommended above

**Comment by NomaanA** [comment]
I'm on a Raspberry pi zero with node v6.11.2 and needed to do the following: (based on @AndreiFAD's comment) 

```
$ echo -e 'PATH="/opt/nodejs/lib/node_modules/homebridge/bin:$PATH"' >> ~/.bashrc
$ . ~/.bashrc
$ echo -e 'PATH="/opt/nodejs/lib/node_modules/homebridge/bin:$PATH"' >> ~/.profile
```

**Comment by MaxHasADHD** [comment]
Does this effect paths for setting up Homebridge on startup? I also had this issue on Raspberry Pi Zero

**Comment by cerniuk** [comment]
The HomeBridge install should have set up an alias... but... Raspberry Pi, NodeJS, HomeBridge are hobbyware so... you have to expect to break out the digital dremel tool and sandpaper when tinkering.   

(NodeJS v6.9.5, Raspberry Pi Zero Wi-Fi)

I dug up the homebridge program in the directory:

    /opt/nodejs/lib/node_modules/homebridge

I opened the .bashrc file and added:

    alias homebridge=/opt/nodejs/lib/node_modules/homebridge

While I was in the .bashrc file I added a couple of more aliases

    alias gohome=homebridge
    alias restartat='sudo /etc/init.d/netatalk stop;sudo /etc/init.d/netatalk start'

and uncommented the other aliases just after:

    # some more ls aliases

I then saved the file and reloaded it with:

    . ~/.bashrc

Because NodeJS changes its directory name in later versions of NodeJS (aka 6.11.2 as noted by ahgharian) the path changed from  /node/ to /nodejs/ so you would alias it like this instead if you are running NodeJS 6.11.2:

    alias homebridge=/opt/nodejs/lib/node_modules/homebridge

(re directory change: annoying as these sorts of small wholesale changes have huge consequences)

And did you catch that? ... using NetATalk to share out my Pi's storage as a network volume and I edit the configuration files with TextWrangler so I can see what is going... To install NetATalk:

    sudo apt-get install netatalk

**Comment by ezfe** [comment]
@cerniuk Regarding your Pi storage and NetATalk, I use Transmit + SFTP which works out of the box. Any FTP client should be able to replace Transmit in my setup.

https://i.imgur.com/9JviY7U.png

**Comment by gh0st699** [comment]
> this has solved for me:
> 
> 
> 
> $ echo -e 'PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"' >> ~/.bashrc
> 
> $ . ~/.bashrc
> 
> $ echo -e 'PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"' >> ~/.profile
> 
> $ sudo reboot
> 
> 

Hello:) I have this problem with the ps4-water command on the Ps4 plugin. Can you help me fix it please? Thanks in advice
