### ISSUE TITLE
macOS - Homebridge runs when manually started, but won't auto start

### ISSUE THREAD

**Issue by jamrolu** [nfarina/homebridge#1556]
Hi all

I have been running Homebridge manually - and this works while the Terminal is kept open.
I followed the instructions on 'How to automatically start Homebridge with launchd' and created the com.homebridge.server.plist file where instructed.

When I restart and type `launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist` I am told that it is already running, but the Home app on iOS cannot see my accessories.

If I go back to Terminal, start manually, and leave open, it does work.

Any suggestions? Help appreciated!
I cannot get viewing of logs to work following the instructions provided.

**Comment by tomwoodhams** [comment]
I get this problem too - I just use an AppleScript to launch now - but would prefer to use launchctl like jamrolu wants to.

**Comment by lbjork** [comment]
I get the same problem. Like to follow the thread...

**Comment by beatpaul** [comment]
unfortunately me too

**Comment by retroneo** [comment]
OK. There are several problems that I have encountered following the instructions for LaunchAgents. All of the following need to be fixed for it to successfully auto launch, and for plugins to work.

1.    Permissions must be correct on ~/Launchagents/ folder and the ~/Launchagents/com.homebridge.server.plist file.

Type the following four commands in Terminal (replacing username with your username): 
`sudo chown username ~/Launchagents/`
`sudo chown username ~/Launchagents/com.homebridge.server.plist`
`chmod ~/Launchagents/`
`chmod 600 ~/Launchagents/com.homebridge.server.plist`

2.   Ensure the plist has the following keys (replacing username with your username). Ensure the full paths are used. The environment variables are essential as otherwise none of the plugins will work.
```
<key>StandardOutPath</key>
    <string>/Users/username/.homebridge/logfile.log</string>
<key>StandardErrorPath</key>
    <string>/Users/username/.homebridge/logfile.log</string>
<key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>/Users/username</string>
    </dict>
```

**Comment by chris-erickson** [comment]
My path didn't have all these paths, so adding them all got me working as expected. 👍
