### ISSUE TITLE
“An accessory is controlled” Problem

### ISSUE THREAD

**Issue by alex101087** [nfarina/homebridge#1596]
Hi guys,

My first ever post.

Firstly the plugins that people spend their time making blow me away, so thank you to all Homebridge and plugin developers out there

Having non-HomeKit devices working with HomeKit thanks to Homebridge is amazing.

I’m not even sure this is a Homebridge issue but unfortunately I cannot try this with a certified HomeKit accessory (forgoing Homebridge) as I have none :(

But my issue as as follows:

I have 4 Milight bulbs using the Homebridge-Milight plugin and it’s fine, but the age old problem is that my partner really wants to control those lights with the wall switch (how dare she), so my plan is to grab some Sonoff Touch switches, flash them with Easyesp, hard wire them and the bulbs to “always be on” and set up an automation in HomeKit to say - when this switch turns on then set milight bulb to ON (so the switch is not connecting directly to the bulb), and the same for OFF.

Before I go and shell out on loads of Sonoff Touch’s, I thought I’d try some automations to see how I get on and I have the following issue:

If I set up an automation to say when my WeMo switch is turned on, turn on (the milight) “Dining Table Light”, and turn on the WeMo through the Home app hey presto, BOTH turn on, however if I turn the WeMo on by its own physical button or via the WeMo app nothing happens to “Dining Table Light” UNTIL I enter the Home App or enter the control centre favourite accessories.

This also happens when I try this using one of my Sonoff S20’s in this automation instead - “Milight still doesn’t turn on.

Obviously this is no good when I (or the missus) want the light to turn on instantly when the switch is controlled.

So my question is what on earth is making this happen?

Timed automations seem to work ok
Motion triggered automations seem to work ok

My set up is:

- Apple TV 4th generation as the hub
- Raspberry Pi with Homebridge running on
- 4x MiLight bulbs on 1 bridge
- 2x WeMo switches
- 1x WeMo motion detector
- 2x Sonoff S20 (flashed with Easyesp)
- 1x XBox One with WOL
- 2x Windows PC with WOL
- 1x Nest Thermostat

If anyone could shed any light that would be great!

Thanks so much in advance,

Alex

**Comment by renssies** [comment]
The problem is with the Wemo switch. The Wemo switch (or an outlet like I have) is one-way communication only. The API of the Wemo switch will allow you to request its state, but it won't notify you when it changes its state. 

So when you open the home app, HomeKit will request Homebridge to ask the state of the wemo switch, homebridge will then ask the wemo switch what its state is and report it back up the chain to HomeKit, triggering the automation. 

The Wemo motion detectors do notify you of its state like most sensors do. 

My guess is that ESPEasy also doesn't notify homebridge of its state. You could try https://github.com/arendst/Sonoff-Tasmota firmware instead, with a Sonoff basic this did report the state when I switched it manually. There is even a homebridge plugin for the Tasmota firmware.

**Offtopic:** You could also look into some 433Mhz, Z-Wave or ZigBee switches and a bridge that can be connected to HomeKit. This might be cheaper than using a Sonoff touch to control wifi enabled lights. I'm currently waiting for my Xiaomi Gateway and switches to come in to see if these work well
