### ISSUE TITLE
Homebridge API

### ISSUE THREAD

**Issue by n1x0id** [nfarina/homebridge#1626]
Is there any way to switch devices added through the homebridge via API or GET/POST url?
I want to add a second voice assistant, besides the Siri, who knows how to make get requests.

**Comment by NorthernMan54** [comment]
There is insecure mode, which allows direct access to all devices via the HAP API.  If you search in closed issues, this has been discussed numerous times already.

**Comment by rcarmo** [comment]
Like in  #1219, I would love to have some sort of REST API to act upon accessory state, since when using an IR bridge or UDP to control exsiting dumb devices I often have to resort to extra sensors to figure out what is going on, and would like to set state on existing devices explicitly. Since there is no API or a way to act upon devices created by other plugins or platforms, homebridge isn't very useful in these scenarios...

**Comment by NorthernMan54** [comment]
You could take the existing plugin that doesn’t have the features you are looking for, add them, then push it back to the plugin maintainer.  That’s the beauty of open source, you can take it, modify it to what you want, and share your enhancements back.  ( Provided the maintainer likes your enhancements )

**Comment by rcarmo** [comment]
That doesn’t scale when you need to modify multiple plugins to incorporate (for instance) Chromecast detection, Broadlink IR sending, custom sensors, etc. I really need an API to inspect existing accessories and set properties/state.

**Comment by MartinPham** [comment]
I'm working on it ! https://www.npmjs.com/package/homebridge-api
