### ISSUE TITLE
Raspberry Pi Zero Wi-Fi + HomeBridge = NULL

### ISSUE THREAD

**Issue by cerniuk** [nfarina/homebridge#1676]
Nothing seems to work with the Raspberry Pi Zero Wi-Fi.  If (and that's a big if) everything manages to fully install, HomeBridge either will not start at all or refuses to stay running.

Has ANYONE gotten this to work on a Raspberry Pi Zero Wi-Fi?

**Comment by 350d** [comment]
I've created a script to install Homebridge on Pi 3 and Zero and test it successfully. Check comments here https://gist.github.com/350d/c774e68f2986f8cf95be85ca9e7c3fcc

**Comment by xoniq** [comment]
I don't know if there are much differences in the Pi Zero or the Pi 3, but I can use an SD card from one into another without issues, currently running HB on my Pi 3 using only a power cable, everything goes via WiFi. If I use a Pi Zero with the same SD card, or a cloned one, it also just works.

**Comment by shanix718** [comment]
Homebridge works fine on my Pi zero w (I installed RASPBIAN STRETCH LITE)!
because Pi zero's CPU is armv6,which is quite different from Pi3.
Here is my installing:
1.  sudo apt-get install curl
(on Pi3) 2.   curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
（on Pi zero w)2.  sudo bash 
                          2.  sudo wget -O - https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh | bash 
                          2.  exit 
                          2.  node -v）
3.  sudo apt-get install -y nodejs
（on Pi zero w) 4.  sudo apt-get install -y npm
5.  sudo apt-get install libavahi-compat-libdnssd-dev
6.  sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
7.  cd /usr/lib/node_modules/homebridge/
（on Pi zero w change the address to)  /opt/nodejs/lib/node_modules/homebridge
8.  sudo npm install --unsafe-perm bignum
9.  cd /usr/lib/node_modules/hap-nodejs/node_modules/mdns
（on Pi zero w change the address to) /opt/nodejs/lib/node_modules/hap-nodejs/node_modules/mdns）
10.  sudo node-gyp BUILDTYPE=Release rebuild
（on Pi zero w) 11.  cd /opt/nodejs/bin
（on Pi zero w) 12.  ./homebridge

**Comment by sassen** [comment]
Thank you shanix718!

I installed homebridge on a Raspberry Pi Zero W with shanix718 method. Tried like 5 different methods and finally this one worked for me, or almost... I actually got a wrong node_module_version error at the end but after some minutes search found the way to solve it. I just uninstalled and installed homebridge again with these commands:

sudo npm uninsstall homebrigde -g
sudo npm install -g --unsafe-perm homebridge

Homebridge running fine now on my Pi Zero W.

**Comment by pdemarco925** [comment]
So I've tried shanix718 method, but still having issues.

when I try "sudo apt-get install -y npm" on my Pi zero w i get the following errors. I know part of my real problem is getting libavahi-compat-libdnssd-dev and mdns installed. I've tried a number of different methods and can't get them to install and/or rebuild. Any suggestions?

Selecting previously unselected package gyp.
dpkg: warning: files list file for package 'libjim0.75:armhf' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libgtk-3-bin' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libdebconfclient0:armhf' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libqt4-xml:armhf' missing; assuming package has no files currently installed
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'libavahi-common3:armhf' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)
