### ISSUE TITLE
Google Wifi is NAT, could this be why I cannot connect to Homebridge?

### ISSUE THREAD

**Issue by br3ttyoung** [nfarina/homebridge#1693]
Everything is working as far as Homebridge running and the configurations are running..
I tried using an iPhone running iOS 10, an iPad & iPhone running iOS 11.2.5. When attempting to pair, Homebridge appears, but gets stuck in an endless loop of connecting until it finally displays "Home couldn't connect to this accessory."

Anyone else know anything about this?

**Comment by cameloper** [comment]
I live in a dorm where the wireless connection is a lot slower than ethernet. That's why I use my Mac to share the ethernet connection to a private wifi for myself over NAT. When I connect my iPhone over my Mac, it cannot connect to homebridge as well, which also supports that homebridge doesn't work when you're connected over NAT. 

In my case though, I can use bridging instead of sharing the connection. Unfortunately I don't know what you could do as a workaround
