### ISSUE TITLE
Homebridge doesn't work with Wireless Lan

### ISSUE THREAD

**Issue by Superduperduu** [nfarina/homebridge#1694]
### Expected Behavior
Work with wlan and not only with lan

### Current Behavior
When my Raspberry Pi 3 is connected to LAN, I can control my Yeelights. But if I connect my Pi only with wireless lan, homebridge doesn't find my Yeelights

### Steps to Reproduce (for bugs)
Start Homebridge with lan plug -> work
Start Homebridge with wlan -> not working

### Versions

- **Homebridge**: `homebridge --version` 0.4.33
- **Node**:       `node --version` v6.10.0
- **OS**:        9 

### Configuration

```json

```

### Homebridge Log / Command Output

```
[2018-1-8 18:10:40] [yeelight] DidFinishLaunching
no ble cap, skip ble device discovery
[2018-1-8 18:10:40] Homebridge is running on port 51826.
add to multicast group
listen on 0.0.0.0
no did or loc found!
```

**Comment by xoniq** [comment]
Very strange. Working fine for months now on my Raspberry Pi 3 using wifi.

**Comment by Tommrodrigues** [comment]
Hey there,
I had this problem when I had set up my Raspberry Pi with homebridge. After much frustration I found that the problem was that my house has wifi extenders and whenever my Raspberry Pi was connected to one of these routers rather than the main router, then I would not be able to access homebridge unless I was connected to the same wifi extender in my house. So, if you do have wifi extenders, the simplest solution would be to move your raspberry pi closer to your main wifi hub. For me, however, this was not an option as my raspberry pi needed to be in a certain location in order to control the garage and gate and therefore I invested in buying some Powerline adapters from TP Link (TL-PA4010) and had one plugged into my main router and the other into my raspberry pi and this works perfectly!
Hope this helped, if you do not have any wifi extenders then please let me know and I will try and work out another solution.
Regards, 
Tommy

**Comment by Superduperduu** [comment]
Hey @Tommrodrigues 
I don't have a wifi extender, so it's all connected to my main wifi hub. 
Is it possible, that homebridge saved the lan connection in settings, when I installed it over the lan connection? And that it doesn't work with wifi because of that?

**Comment by Superduperduu** [comment]
OK, I just deleted my Homebridge in the Home App on iOS and added it again and now it works with wifi - Yeah!
