### ISSUE TITLE
iOS 11.3

### ISSUE THREAD

**Issue by Marsgames** [nfarina/homebridge#1728]
Hey, do you now if there is an issue caused by iOS 11.3 ?

It seems that my homebridge doesn't work anymore since I update my iPad and iPhone to 11.3, but I don't know if it's the cause

**Comment by Hackashaq666** [comment]
works for me

**Comment by zackaweed** [comment]
I've also been having a strange issue since I updated to iOS 11.3 and tvOS 11.3 . No problem at all with any of my homekit accessories when I'm on my home network where my pi is attached, but the minute I leave the network all homebridge accessories are showing "no response". No error or anything strange looking in the homebridge log, any ideas?

**Comment by Marsgames** [comment]
I removed my bridge (so all my accessories) then reinstall it, and now it works perfectly
