### ISSUE TITLE
iOS 11.3b1 remote homebridge access not working

### ISSUE THREAD

**Issue by zackaweed** [nfarina/homebridge#1730]
I've been having a strange issue ever since I updated to iOS 11.3b1 on iPhone 7 and tvOS 11.3b1 on Atv 4. No problem at all with any of my homekit or homebridge accessories when I'm on my home network where my p running homebridge is attached, but as soon as I disconnect from the wifi network all homebridge accessories are showing "no response". No error or anything strange looking in the homebridge log. I have tried removing the accessory and persist folders in homebridge, restarting and upgrading pi, and just did a fresh raspbian and homebridge install but still having the same problem. Any ideas?

**Comment by zackaweed** [comment]
updated to iOS 11.3b2 yesterday to no avail. Also tried restarting all devices, logging out from icloud on both apple TV and iPhone, restarting router an modem, changing the username MAC address, changing the bridge name, removing and readding the bridge, nothing seems to do the trick to have any response off of the local network. Any ideas would be greatly appreciated!!!

**Comment by macbisho** [comment]
I've had an open issue with Apple for remote access (and inability to share HomeKit) since December.. apparently there's a team investigating it.

Christmas is coming.

(Note - I have actual real HomeKit enabled devices and not just HomeBridge items, so I'm confident it's not a HomeBridge issue).

**Comment by pelaxa** [comment]
@macbisho AFAIK that issue was resolved (inability to share homekit).  that was due to a security vulnerability that  was discovered and apple disabled that in December, but if you are on the latest version of iOS, things should be working just fine.

**Comment by K-MTG** [comment]
Since my upgrade to iOS 11, my shared devices lost the ability for remote access (even though I have Allow Editing/Remote Access enabled). The primary home device "sometimes" works remotely. This is with an Apple TV 4. 

Hence, I used my iPad Air as a HomeHub but that too also stopped working with iOS 11.3. So now I don't have any remote access. I just have the message my hub is not responding and my devices are unavailable when I am away from home.

**Comment by popepay** [comment]
Same problem here. 
My ecobee works fine remotely through homekit. 
My homebridge devices work fine locally (WiFi) but are “not responding” remotely. 
Apple TVs & iOS 11.3

**Comment by QempZor** [comment]
Got the same issue, On wifi everything is working fine, however remote access only shows up the Hue lights (native from the Hue app).
Every Homebridge connected device is "not responding".
Currently on iOS 11.3.1 (no beta)

**Comment by xuncia** [comment]
Hi, I have the same problem with last iOS and atv 4K, hue works fine outside but every homebridge accessories is not responding.... :(  any news or tips about this?

**Comment by pelaxa** [comment]
This seems to really be a homekit issue.  I have an iPad and a ATV as my hub, and had to sign in and out of icloud a few times to get the ATV to respond from outside.  Yesterday out of the blue it stopped again.

**Comment by xuncia** [comment]
I’m not so sure, because hue philips works fine with the hub, every time that I disconnect the atv and reconnect hue are working remotely, but homebridge accessories are not responding, I need to try to log out and log in  from iCloud in my iPhone and then I don’t know what to do.

**Comment by pelaxa** [comment]
you need to logout of icloud on your ATV....its the hub that is the issue, not your phone.

I've had it where I cannot talk to the homebridge devices only or any device at all.  as I said, I have two hubs, and when i have this issue, I can remove the active one and the backup seems to work just fine.  Homekit is just not as reliable as it needs to be.

**Comment by xuncia** [comment]
First of all thank you for answering me. I’ll try again but I assure you that yesterday I’ve already tried a couple of times to logout on the appletv and login again. Every time in WiFi everything was fine as soon as I switch off WiFi on iPhone home application shows no answer from any homebridge accessories, but hue still there and works fine....I’ll try again tonight and maybe I’reset the atv.

**Comment by KirillKotlyarenko** [comment]
I use iPad Mini 2 as a HomeKit hub and Windows-based HomeBridge. Everything works fine while I'm at home (as I assume, because my iPhone connects to HomeBridge directly through Wi-Fi), but all devices are "not responding" when I'm away.
I've figured out that closing and opening Home app on iPhone solves the problem, even on another iPhone (e.g. Homebridge devices are not responding -> close Home app on my iPhone, open it again, it establishes a connection successfully -> I open Home app on my wife's iPhone and it also works fine).

Since this is an issue only with Homebridge devices (more then a half of my smart home devices support HomeKit natively), I assume this is something that was changed in recent iOS update and it changed how HomeKit bridges interact with HomeKit-certified devices.

**Comment by xuncia** [comment]
> Since this is an issue only with Homebridge devices (more then a half of my smart home devices support HomeKit natively), I assume this is something that was changed in recent iOS update and it changed how HomeKit bridges interact with HomeKit-certified devices.

Yes it could be, let's hope with the new iOS and tvOs on monday.
let's keep in touch.
thank you
