### ISSUE TITLE
add this accessory to your home you'll need to reset it first

### ISSUE THREAD

**Issue by xiexianghua** [nfarina/homebridge#1775]
### Versions

- **Homebridge**: `homebridge --lastest`
- **Node**:       `node --version`
- **OS**:          11.3

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by xiexianghua** [comment]
配件已添加 若要在家中添加此配件，您需要先将其还原
有谁知道怎么解决吗？
改config里的username和mac地址都没用

**Comment by Fuenti** [comment]
This issue is not stale to me. I am trapped in this penalty box. I deleted homebridge, because I made some significant changes and I wanted to make sure those changes took effect. When I tried to add it again, I got the message "Accessory already added, To add this accessory to your home, you'll need to reset it first." I then tried a series of remedies:
1. I tried a scored earth method by removing the entire home. When I tried to add homebridge as the first accessory to the new home. I got the same message.
2. I deleted the app and then reinstalled it. When I tried to add homebridge as the first accessory, I got the same message. 
3. I deleted the home, deleted the app, and then turned off the router. I then brought them all back and then tried to install homebridge. I got the same message.

**Comment by rjruizes** [comment]
This fixed it for me.

```shell
rm -fr ~/.homebridge
```

**Comment by Fuenti** [comment]
I was able to fix it by changing the username and the pin in the config.json file.

**Comment by qnm** [comment]
The Homebridge web UI has a reset option "Reset Homebridge Accessory" which worked for me.

**Comment by Peppuz** [comment]
> 
> 
> The Homebridge web UI has a reset option "Reset Homebridge Accessory" which worked for me.

I confirm! It worked to me, i deleted all from Home app and Reset Homebridge Accessory.
Than i scanned QR again and worked.
