### ISSUE TITLE
I cannot find the log files in homebridge

### ISSUE THREAD

**Issue by jeffl78** [nfarina/homebridge#1839]
I normally type "homebridge" to run if that helps anyone. I tried all the normal commands in homebridge wiki but it just says file cannot be found.

Actually it does this:

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# tail -f /var/log/homebridge.log
tail: cannot open '/var/log/homebridge.log' for reading: No such file or directory
tail: no files remaining

**Comment by camcs1** [comment]
If you dont run homebridge as a service the logs are not automatically created. 
You can create them by starting homebridge with a command like this 
`homebridge | tee /var/log/homebridge.log`

**Comment by cubilon** [comment]
I run Homebridge as a service but I can't find any log too.

**Comment by jeffl78** [comment]
I got it working, one just has to check their logs after running the above command and read the logs as homebridge starts and runs and get the token.  If you don’t see it in the log completely remove the Oauth client you created at the nest developer site and then make a new one before running it in the homebridge config.json file again.

**Comment by inet-cologne** [comment]
The topic was active a long time ago, but...

... **problem finding the source of errors** shown in the homebridge main screen of the Homebridge UI. 

On my Raspberry4 I've the most current homebridge 1.3.4 with Homebridge Homematic 0.2.226 plugin running and errors in my status screen:
_[homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info._

I couldn't find any log file und was not able to start Homebridge in debug mode to get the exception message of the problem by uncommenting the
   debug=*
line with
  nano /etc/default/homebridge
because Homebridge did not start anymore.

**Solution** was to **stop Homebridge** service by
  sudo systemctl stop homebridge
and **manually start homebridge in debug mode** with
  cd /usr/local/bin
  sudo homebridge -D U /var/homebridge

After that homebridge startet and gave me the debug outputs on the console screen.

Hope this is for help for others!
