### ISSUE TITLE
Z-Way improvements (thermostat etc.)

### ISSUE THREAD

**Issue by luxus** [nfarina/homebridge#193]
follow up of this https://github.com/SphtKr/homebridge/commit/656a8057acbd177995f5a3dd9b63262082387d2b
and
https://github.com/nfarina/homebridge/pull/191
and 
json of stellaZ radiator valve thermostat
https://gist.github.com/luxus/3232fbedc09e8f1eff09#file-devices-json-L82

@SphtKr 
the:
```
        "thermostat",
        "switchBinary",
        "sensorBinary.Door/Window",
        "sensorMultilevel.Temperature",
        "switchMultilevel"
```
works as well
![img_0356](https://cloud.githubusercontent.com/assets/7449/9990870/2aca46fe-6065-11e5-9ece-48182d5fe479.jpg)
now it shows even the battery level :dancer: 
eve understands all characteristics

there is still one metric i don't see.
```
      {
        "creatorId": 1,
        "deviceType": "switchMultilevel",
        "h": -1703465104,
        "hasHistory": true,
        "id": "ZWayVDev_zway_11-0-38",
        "location": 1,
        "metrics": {
          "icon": "multilevel",
          "title": "Wohnzimmer Ventil",
          "level": 44
        },
```

 if i am in heat mode i can't even change it. but it would nice if could see it because it shows how open the valve is.

i don't have any additional z-wave items(sending back my lc-13 thermostat from danfoss). so thats the only one i can test!

**Comment by SphtKr** [comment]
Aha! Well I think you have the Eve app update that came out today to thank for the battery status...finally! I've been trying to get that to work for weeks. I guess it wasn't me!

What...on earth does that `switchMultilevel` do? Is that fan speed? My German is very rough.

**Comment by luxus** [comment]
hi @SphtKr,
sorry for the late answer.
i see you did a lot work on the z-way integration. the wiki sounds awesome.. 
i wish there would be such a integration in home-assistant.io (i learn to program at the moment to do just this)
 back to topic.
the `switchMultilevel` change the level of the valve that controls how much heated water go trough
![german heater]
(http://www.heizsparer.de/wp-content/uploads/images/heizkoerper-glieder-irina-fischer-fotolia.jpg)
for the stellaz it just works in the right operation mode

```
Operating the device
The device does not allow any local operation on the device itself but control via Z-Wave radio from a Z- wave controller only. The thermostat has four operating modes. They are switched wirelessly as well:
1. Frost Protection: The temperature in the room will be regulated to about 6 °C.
2. Comfort: The temperature in the room will be regulated to a comfortable level. On factory default this is 22 °C but the value can be adjusted by the respective Z-Wave command 'Thermostat Setpoint' to a
value between 0 °C and 50 °C. This mode is active on factory default.
3. Energy Saving: The temperature in the room will be regulated to a energy saving level. On factory
default this is 18 °C but the value can be adjusted by the respective Z-Wave command 'Thermostat
Setpoint' to a value between 0 °C and 50 °C.
4. Direct Valve Control: This mode allows the direct control of the valve as percentage value of
opening using the Z-Wave command class 'Switch Multilevel'. The regulation of a temperature within the device is deactivated.
Additionally to regulating the temperature the valve control is reporting the measured temperature on request (using the command class 'Sensor Multilevel' implementing communication pattern 3). It may happen that the reported temperature will remain 0 °C for some minutes due to calibration. 
After the first regular wakeup the temperature value will however be correct. Switching between the four modes is accomplished using the Z-Wave command classes 'Thermostat Mode' and 'Basic'. 
The following mappings apply

Frost Protection: BASIC SET 0x01, THERMOSTAT MODE SET 0x00 
Energy Saving: BASIC SET 0x00, THERMOSTAT MODE SET 0x0b 
Comfort: BASIC SET 0xff, THERMOSTAT MODE SET 0x01
Direct Control: BASIC SET 0xfe, THERMOSTAT MODE SET 0x1f
```
http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=EUR_STELLAZ&pdf=1

comfort mode is default(HEATING) i just set a set point temp. and done.
in the direct control mode it would allow me to change `switchMultilevel` and just activate heating until i say stop (0-100%)

**Comment by SphtKr** [comment]
@luxus Glad you like what I've got so far! Here's what I'd recommend trying:

Go to the Z-Way web UI and add the following tag to the `switchMultilevel` device (not the thermostat!):

    Homebridge.Accessory.Id:StellaZValve1

I *think* that will be sufficient. It will cause the valve control to be split off into its own Accessory, which should then be recognized as a `Lightbulb`, which will allow you to control the value--even with Siri. (Careful, if you say "turn on the lights", it may get set to full open! I don't know for sure.) Which is not ideal, but it should at least get it bridged and let you control it.

Right now the Z-Way server doesn't expect a switchMultilevel to be included in a Thermostat, and the only type of switchMultilevel it knows about is a Lightbulb/dimmer. I could potentially add it but it might be tricky...without some tracing and debugging, it might break the bridge's compliance and without one of the StellaZ's of my own, it's hard to test. Part of the trick is, when it encounters a `switchMultilevel` it adds *two* characteristics--the `Brightness` and an `On` Characteristic--which might cause a problem with the Thermostat. I can give it a try, but try the above and see if it works for your use-case.

If that doesn't do it, you might try adding the following two tags and see if they help:

    Homebridge.Service.Type:Lightbulb
    Homebridge.IsPrimary

But both of those things should be inferred. You can also try:

    Homebridge.Homebridge.Characteristic.Description:Valve Control

...which *might* make it be labeled as such instead of "Brightness", but I haven't actually observed this value being displayed in any HomeKit app.

**Comment by luxus** [comment]
i was able to add it as a additional lightbulb accessory with the first tag, the 3. tag don't change anything 
without being able to change the mode of the of the thermostat it makes no sense at the moment.
for now i just try to add the valve value as a additional info to the grouped thermostat(like battery level).. 
 .. i thought i can use the Homebridge.Accessory.Id: tag to add it to the existing accessory, but i don't get it working yet. i will try it tomorrow again

**Comment by SphtKr** [comment]
Ah, I see. Well, making it possible to control the mode is harder, for two reasons.

First is that HomeKit doesn't natively have a Characteristic for that kind of mode setting, it has only `TargetHeatingCoolingState` and `CurrentHeatingCoolingState`, which have only really 3 values: off = 0, heat = 1, and cool = 2. And you can't really create a custom Characteristic that is an "enum" type like this because your app (Insteon+ for instance) won't know what the values mean--custom Characteristics like that are most useful when you are making your own iOS app for the device. In theory, I could make a custom Characteristic that was just a number, and you could just remember which numeric values are what and you could set the number value you want. Unfortunately, I tried a custom Characteristic over in the YamahaAVR platform and none of my iOS apps really knew what to do with it--those that would even show it could not set it, for instance.

Second is that I'm not certain that Z-Way's VDev API would let me set the value either. The [API Documentation](http://docs.zwayhomeautomation.apiary.io) says that there is a `setMode` parameter you can send to a thermostat, but I'm not 100% sure that would send commands to the StellaZ's mode parameter--but it might. On the other hand, I've read things in the RaZBerry forums about that parameter not working as expected :-/. It might work though, and you could try it. Try making the following HTTP calls to your Z-Way server...something like this:

    http://yourzwayaddress:port/ZAutomation/api/v1/devices/ZWayVDev_zway_8-0-67-1/command/setMode?mode=0

(Note: you will need to hit that address from the browser where you have already logged into the Z-Way Web UI...unless you want to do the authentication manually with curl or something.)

In theory, hitting the above address should set your thermostat to "Frost Protection" mode. Changing `mode=0` to `mode=1` should set "Comfort" mode, and `11` and `31` should be "Energy Saving" and "Direct Control".

If that works, I may be able to hack something in to support that mode, but using it from iOS won't be pretty (probably no Siri control and you'd have to remember to set the number "31" to get direct control). Might be worth it though if it works, I know this is a popular device.
