### ISSUE TITLE
Can't Add HomeBridge to Home App

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1952]
Hey everyone,
Before you reply I already saw issue 422 I believe where someone else has this issue and the "solution" didn't work.
I ran homebridge successfully and everything works, just adding it to the Home App doesn't work it just says "Couldn't add Homebridge" "Home couldn't connect to this accessory."
I also deleted the accessories and persist  folder.

**Comment by iRayanKhan** [comment]
If it help's I am on the same Wi-Fi network as my Pc and iPhone. Does 2.4g/5g bands matter? Also I am not using a netgear router since I heard that has some issues. I am on iOS 12 Dev Beta 5 and even tried to add this to a device running iOS 11.4.1 (15f77)

**Comment by iRayanKhan** [comment]
Running this on an Ubuntu VM btw

**Comment by mklemm** [comment]
I have the same issue. I did some analysis of the Bonjour record that Homebridge advertises, and there seems to be an error:

14:41:39.607  Homebridge-CAD8._hap._tcp.local. can be reached at CC_22_3D_E3_CE_30.local.:51826 (interface 14)
 md=Homebridge pv=1.0 id=CC:22:3D:E3:CE:30 c#=2 s#=1 ff=0 ci=2 sf=1 sh=WEoZ9g==

The "ff" entry, according to apples HAP spec, should actually read "1", meaning it supports HAP pairing. Maybe this is an issue?

**Comment by StoneMoe** [comment]
Make sure your machine which hosts homebridge can do a multicast to your local network,
This is necessary for iPhone to find your server IP address automatically.

You can check this by running wireshark/tcpdump on another device in your local network and see if there any packet recv from homebridge.

**Comment by sbehrends** [comment]
Im having same issue when running Homebridge from an Raspberry Pi.
For debugging I started the server on a Mac and works as expected. Maybe is something related to unix libavahi.

**Comment by sbehrends** [comment]
Just installed iOS 12 beta 6 and everything went back to normal!

**Comment by fqx** [comment]
@sbehrends I still cannot connect to homebridge after installing latest public beta of iOS 12.

**Comment by Tommrodrigues** [comment]
I'm having a similar-ish problem with my Raspberry Pi running homebridge. It seems to work fine when running off wlan0 (Wi-Fi), but I would like to use ethernet instead because it is more reliable. However, when ethernet is in, I can't connect to homebridge, I just get No Response. After that, I try resetting everything like the username, pin etc. and then I follow this issue [here](https://github.com/nfarina/homebridge/issues/607). Strangly, this enables me to pair and connect from ethernet just fine but **only** on my home network and not at all when I try to connect outside of my network i.e. using cellular. I am unaware as to why this is; I believe it may have to do with some way in which my router handles ethernet differently than wifi connections but I am clueless. As @StoneMoe suggested, I have run Wireshark on my network and scanned for all packets on port 5353 and seen that when I am using homebridge without ethernet, these appear. Strangely, in my config.json it is specified that port 51826 should be used but when I scan my network for that port I get no packets at all, why is that?

**Comment by StoneMoe** [comment]
Take a look at issue #1957, you can use an undocumented configuration fix this.

Sent from my iPhone

**Comment by Tommrodrigues** [comment]
@StoneMoe Thank you so much! Doing that solved my problem pretty much straight away and also indirectly solved another issue!

**Comment by iRayanKhan** [comment]
This was fixed I had to get a Raspberry Pi 3 Model B because I believe you can ONLY use a vm if you have a Wi-Fi adapter since it needs to send it's own packets.
