### ISSUE TITLE
AirPlay 2?

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1987]
Hey everyone,
With Apple introducing AirPlay 2 most companies are greedy *hint* ONKYO *hint* and won't give a firmware update to add it. Does HomeBridge support AirPlay 2 accessories? Like so can I make a AirPlay 2 device with it's ip an AirPlay 2 speaker? Yes I'm aware plugins do this, but since I didn
it find any idk if HomeBridge supports Speaker atm.

**Comment by ebaauw** [comment]
Short answer: no.

Long answer:

Homebridge has supported the _Speaker_ service since Apple introduced it, but the Home app only supports this for video doorbells.  The Home app uses Airplay2 instead of HAP to communicate with Airplay2 devices, they don’t appear on other HomeKit apps.  Homebridge only talks HAP.

There’s Airplay implementations in other software (
https://github.com/stephen/node-tunes, 
https://rogueamoeba.com/airfoil/), but I haven’t seen any Airplay2 implementations in software.

**Comment by iRayanKhan** [comment]
Node tunes link broken, and yeah I've seen AirFoil b4. Thanks for the quick response though! 
Another small question: Can you still add doorbells to HomeKit via HomeBridge, I was asking since Apple Removed DoorBells from their website.

**Comment by ebaauw** [comment]
> Node tunes link broken

That’s new to me.  Good thing I forked it:
https://github.com/ebaauw/nodetunes.

> Can you still add doorbells to HomeKit via HomeBridge

I don’t have any myself, but last time I checked, they could still be created in the HomeKit Accessory Simulator.

**Comment by iRayanKhan** [comment]
How do you access the Hk accessory simulator?

**Comment by iRayanKhan** [comment]
Just found it off apple dev website
