### ISSUE TITLE
Accessory not found

### ISSUE THREAD

**Issue by gee4vee** [nfarina/homebridge#1995]
Trying to add Homebridge via Home app and I keep getting accessory not found. Tried clearing accessories and persist folders. Made sure the Homebridge port is open on my firewall. Also tried reinstalling homebridge, homebridge-http, and homebridge-nest.

### Expected Behavior
Homebridge gets added to Home.

### Current Behavior
Home app says 'Accessory not found'.

### Steps to Reproduce (for bugs)
1. Install homebridge, homebridge-http, homebridge-nest via npm -g install ...

### Versions

- **Homebridge**: 0.4.45
- **Node**:       8.11.3
- **OS**:         Windows 10 Pro

### Configuration
For iOS I've tried both latest v11 and v12 GM candidate.

### Homebridge Log / Command Output
```
C:\Users\gee4v\AppData\Roaming\npm\node_modules>CD /D "C:\Users\gee4v\AppData\Roaming\npm\node_modules\homebridge\bin" & node homebridge
[2018-9-13 15:00:37] Loaded config.json with 0 accessories and 1 platforms.
[2018-9-13 15:00:37] ---
[2018-9-13 15:00:37] Loaded plugin: homebridge-http
[2018-9-13 15:00:37] Registering accessory 'homebridge-http.Http'
[2018-9-13 15:00:37] ---
[2018-9-13 15:00:38] Loaded plugin: homebridge-nest
[2018-9-13 15:00:38] Registering platform 'homebridge-nest.Nest'
[2018-9-13 15:00:38] ---
[2018-9-13 15:00:38] Loading 1 platforms...
[2018-9-13 15:00:38] [Nest] Initializing Nest platform...
[2018-9-13 15:00:38] [Nest] Fetching Nest devices.
[2018-9-13 15:00:40] [Nest] initing thermostat "Hallway Thermostat": deviceId: yk6vjQGG_Q6RayOxBaKi0MrbYeLtLUy5 structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing protect "Leo’s Room Nest Protect": deviceId: 8eVs5FCudIKKQLq3zzbnAMrbYeLtLUy5 structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing protect "Entryway Nest Protect (Hallway)": deviceId: 8eVs5FCudIKybCZWH3euJ8rbYeLtLUy5 structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing protect "Office Nest Protect": deviceId: 8eVs5FCudILyCspg9Io1lsrbYeLtLUy5 structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing cam "Front Yard Camera (Driveway)": deviceId: I4gDBvpGQE0thXgYgu9gaAmAEjomQyKZPnDpLwYpYULK22Hi7S1MuQ structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing cam "Baby’s Room Camera": deviceId: KWM53rVByCrf4HwgJDtQ0RmQGi2eIkIu70oYoFYQIsrK22Hi7S1MuQ structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing cam "Front Yard Camera (Porch)": deviceId: LOgz2dRJyFUZH8J4Hotp5jYsaU-gozlkjvMjDOFNfrzK22Hi7S1MuQ structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] initing cam "Living Room Camera": deviceId: qaP6hgZHJkGjVBG5rEaPnGIaeJgvdC--p33mig3j-4zK22Hi7S1MuQ structureId: bjUH2YiBDvARehCWda80Lt6od_JJL5ZUziZiksY7HMLy59ERajx58Q
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Hallway Thermostat'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Leo’s Room Nest Protect'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Entryway Nest Protect (Hallway)'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Office Nest Protect'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Front Yard Camera (Driveway)'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Baby’s Room Camera'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Front Yard Camera (Porch)'...
[2018-9-13 15:00:40] [Nest] Initializing platform accessory 'Living Room Camera'...
Setup Payload:
...
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
...
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
...
[2018-9-13 15:00:40] Homebridge is running on port 51827.
```

**Comment by iRayanKhan** [comment]
Make sure you are on the same Wi-Fi network as HomeBridge is. Yes the Wi-Fi bands matter too.

**Comment by mklemm** [comment]
I still have the same issue. MDNS packets are verified to be received on the network (checked with tcpdump).
If going to manual pairing, HomeKit shows Homebridge as available, but after entering the PIN, HomeKit fails with error 66, and a message along the lines of "Device not compatible".

I did some analysis of the Bonjour record that Homebridge advertises, and there seems to be an error:

14:41:39.607 Homebridge-CAD8._hap._tcp.local. can be reached at CC_22_3D_E3_CE_30.local.:51826 (interface 14)
md=Homebridge pv=1.0 id=CC:22:3D:E3:CE:30 c#=2 s#=1 ff=0 ci=2 sf=1 sh=WEoZ9g==

The "ff" entry, according to apples HAP spec, should actually read "1", meaning it supports HAP pairing. Maybe this is an issue?

BTW I checked with tcpdump that there actually is connection between the iPhone and Homebridge. Several packets are exchanged between the two of them. But still the HomeKit app says: Could not connect to accessory

**Comment by ebaauw** [comment]
> The "ff" entry, according to apples HAP spec, should actually read "1", meaning it supports HAP pairing. Maybe this is an issue?

Interesting find - that's how I read the spec as well.  To check, my v2 Hue bridge advertises `ff=1` both when paired and when not paired.

I never looked at the Discovery section 5.4 of the HAP spec before, but it contains some interesting stuff:
> The name of the Bonjour service is the user-visible name of the accessory, e.g. "LED Bulb M123", and must match the name provided in the Accessory Information Service of the HAP Accessory object that has an instanceID of 1.

Since the move to the native javascript MDNS implementation, the advertised name no longer matches the Accessory Information Service, due to the four-letter suffix added to the advertised name.  @KhaosT, @nfarina what's your take on this?

**Comment by ebaauw** [comment]
I don't see any difference in responsiveness, but it seems I can no longer pair homebridge with `ff=1`.  According to the debug log, the client does a POST /pair-setup for Pair step 2/5 and then turns silent.  Also, the client doesn't show the warning that the accessory is not certified.

**Comment by dreamcasting** [comment]
+1 to this being an issue. Disabled firewall and no good.

**Comment by dreamcasting** [comment]
Research:
Using Bonjour Browser it looks like localhost can see the homebridge going but no other computer on the network can, even if all firewalls are disabled.

**Comment by dreamcasting** [comment]
@ebaauw - The mdns fix allows it to be seen now across the network in bonjour browser - thank you! iOS still won't attach to it for whatever reason. Also confirmed there's no IGMP snoop enabled.

**Comment by dreamcasting** [comment]
Update: It looks like there was a wait for publishing time for iOS to recognize it. I forgot I left it running and when I was adding something else to HomeKit today it also saw the homebridge running as an accessory. I'd definitely suggest having the instructions guide updated to include the mdns setting.

**Comment by gee4vee** [comment]
So is there something we can do to fix it in an existing install or do we need a homebridge fix?

**Comment by dreamcasting** [comment]
I would say just updating the guide to:

- Make sure Windows Firewall has ports open for bonjour and homebridge.
- Use the mdns binding setting to the network IP in config.json

**Comment by gee4vee** [comment]
Adding the mdns line to config.json worked! I was able to add my homebridge to Home app. Thanks!

**Comment by mklemm** [comment]
Still doesn't work for me. mdns records are received on all machines on the network, homebridge is shown as pairable device in manual pairing, but pairing gives error 66 "Device not compatible"

**Comment by hepcat72** [comment]
For anyone else finding themselves here and trying these tips and it's not working... check your logs. I was getting "no response" errors from Siri, couldn't control any device from the home app, couldn't re-add the homebridge to the home app, and none of the usual fixes worked either: remove persist, remove accessories, change the name, turn onn/off airplane mode, restart the Pi & my phone... I even tried the dumptcp suggestion and saw homebridge traffic on the expected ports... Well, my homebridge-liftmaster2 plugin was crashing homebridge a dozen times a minute due to a bad response from the chamberlain remote server that the plugin doesn't handle. My logs had bloated with multiple errors per second and pm2 was working overtime to restart homebridge continually.

**Comment by joshstrange** [comment]
Not sure if this will help anyone else but I added the package "umdns" to my LEDE/OpenWRT router and restarted and now I can add the bridge. I'm not sure if it was the restart or the package that fixed it but I've been pulling my hair out and now it's working. I think it was probably the reboot as this was working previously.

**Comment by mtrudel** [comment]
Setting `ff=1` changes the value of `kTLVType_Method` in the first request of the `pair-setup` flow to be `1`, or `Pair Setup with Auth` (with the value of `ff=0`, this is set to be `0`, or `Pair Setup`. Setting it to 1 also suppresses the 'Uncertified Accessory' warning at the start of pairing, and also causes the iOS device to abort pairing after the device sends an otherwise correct `M4` response. 

My best guess here is that `ff=1` is actually intended to be used by certified devices only. My hunch is that with that flag set, the iOS client thinks it's connecting with a certified device, and that there's something in the information of the `M4` which disproves that, causing the iOS client to abort the pairing request.

**Comment by hepcat72** [comment]
> Setting `ff=1` changes the value of `kTLVType_Method` in the first request of the `pair-setup` flow to be `1`, or `Pair Setup with Auth` (with the value of `ff=0`, this is set to be `0`, or `Pair Setup`. Setting it to 1 also suppresses the 'Uncertified Accessory' warning at the start of pairing, and also causes the iOS device to abort pairing after the device sends an otherwise correct `M4` response.
> 
> My best guess here is that `ff=1` is actually intended to be used by certified devices only. My hunch is that with that flag set, the iOS client thinks it's connecting with a certified device, and that there's something in the information of the `M4` which disproves that, causing the iOS client to abort the pairing request.
> 
> CC @ebaauw

So you're suggesting setting `ff=0`?  Do you have file and line numbers for these settings?

**Comment by mtrudel** [comment]
@hepcat72 I honestly have no idea. I'm neither using nor contributing to homebridge; I'm using it as reference material for a project I'm working on (https://github.com/mtrudel/hap).

That being said, it looks like https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/Advertiser.ts is the relevant source for this project.

**Comment by hepcat72** [comment]
Sorry.  I didn't mean to imply you were associated with this project.  I did assume you were a user of it though and were trying to solve this issue.  It does appear you're at least trying to avoid encountering the issue described on this page in your own project.  Is that correct?  If so, I'd be interested in hearing about your solution once implemented.

**Comment by mtrudel** [comment]
Sorry for the confusion - here's what I've figured out so far:

* The details of `ff` are undocumented in the spec (it looks like it probably got redacted away when they sanitized the spec for non-commercial use). In general, there seem to be a lot of (presumably redaction) errors / omissions in the non-commercial specification (as well as conflicts between R1 and R2 of the spec).
* The mDNS value of `ff` determines the value passed for `kTLVTypeMethod` in the `<M1>` request (Step 4.7.1 of the spec). Specifically, an `ff` value of `0` causes a value of `0` ("Pair Setup" in Table 5-3) to be sent, where an `ff` value of `1` causes a value of `1` ("Pair Setup with Auth" in Table 5-3) to be sent. Since this value denotes the auth method being used, it follows that the subsequent interactions will differ in these two cases.
* Even though the specification specifies that we should expect a "Pair Setup with Auth" flow, doing so drops out after the accessory sends back its `<M4>` response, presumably because that method expects a different payload than we send back per the spec. If one advertises `ff=0` (and thus the Home app follows the `Pair Auth` flow), it works just fine. I assume this is an error in the specification.

For reference, the flow outlined in https://github.com/mtrudel/hap is correct as far as I've been able to tell. I spent a lot of time experimenting & synthesizing together various OSS HAP implementations to get to there, and it seems to work quite well so far. Check out https://github.com/mtrudel/hap/blob/master/lib/hap/discovery.ex and https://github.com/mtrudel/hap/blob/master/lib/hap/pair_setup.ex for details, but please bear in mind that it's a work in progress and nothing beyond `<M5>` in the pair setup flow is even implemented yet.

**Comment by Dudleydogg** [comment]
So this Thread is over a year old, and I see Videos of people still setting up home Bridge, so it must work. Although I have completed 2 clean installs on my Lan/Subnet I cannot add HomeBridge to any of my Iphone Home application.  So does anyone have a solution to this problem?
has to be a answer some where or this project would be dead which it appears not to be

**Comment by hepcat72** [comment]
> So this Thread is over a year old, and I see Videos of people still setting up home Bridge, so it must work. Although I have completed 2 clean installs on my Lan/Subnet I cannot add HomeBridge to any of my Iphone Home application. So does anyone have a solution to this problem?
> has to be a answer some where or this project would be dead which it appears not to be

I can’t speak to your specific issue, but I can attest that I am not currently experiencing this issue.

**Comment by Dudleydogg** [comment]
I have Ubuntu with HomeBridge installed.  Even added some devices and they all show up in the http portal.

But the iphone wont allow me to add the home bridge.

 

Maybe this is just ubuntu thing?  Should I try another OS?

**Comment by hepcat72** [comment]
I had similar trouble when I set mine up but it’s been a long time. I got around it with a lot of googling and posting to get help. Perhaps post your own issue with the details.

**Comment by Dudleydogg** [comment]
Problem is everything appears to work from the HomeBridge it self but my HOME on IOS refuses to find it.

 

So not sure where to look actually googlilng is what got me to this thread LOL.

 

Point me anywhere ill go check it out.

**Comment by Dudleydogg** [comment]
OK well maybe this will help someone else, Everything I read kept saying how you needed Multicast enabled. When in fact I had to Disable Multicast and configure Bonjour forwarding on all the AP's.  Soon as  I disabled multicast I could add the homebridge. All my Air print started working again too.
So I was able to add HomeBridge running in a Ubuntu VM, and I can see Snapshots from my ring doorbell, apparently it does not stream video.  Get 60 second snapshots only.  and Neither of my Venstar thermostats work,  But I was able to add the homebridge LOL just nothing works yet.
