### ISSUE TITLE
No answer from tuya power-outlets in Home app

### ISSUE THREAD

**Issue by hajopaj** [nfarina/homebridge#1998]
Hi, I’m using Homebridge on a Raspberry Pi with the Homebridge-tuya plugin and I’m experiencing the following issue: 

I got Homebridge and the plugin running flawlessly and all the devices behind the bridge show up in Apple’s "Home"-App showing their actual and correct state.
![14065cf0-1abb-4376-8c6e-eabf9d795d60](https://user-images.githubusercontent.com/43090955/45585826-88fe6980-b8eb-11e8-8e0a-d6bd723bd238.jpeg)
The problem is that switching the devices (WAZA WiFi smart plugs) does not have any effect. It just says “no answer" from the device.

I’m running node 9.9.0 and npm 5.10.0 and have absolutely no idea what’s causing the problem...
I posted this issue in the Homebridge-tuya repository but as said there the plugin is working fine and there seems to be a Homebridge issue.

https://github.com/codetheweb/homebridge-tuya/issues/9

So I’m posting this here...

**Comment by hajopaj** [comment]
Nobody has any idea? Maybe even a hint where to look elsewhere?

**Comment by Jefronty** [comment]
It sounds similar to an issue I was having.  The local key changes every time a device is adopted.  If you used tuya-cli to get the keys and then added them back to another app like Smart Life you cannot control them with the local keys you had found.  You still will be able to read the state of the device since that only requires the device ID and not a key value.  I was able to resolve the issue by installing Smart Life on an Android emulator, signing in and reading the local keys from an XML file as described [here](https://github.com/codetheweb/homebridge-tuya/issues/13#issuecomment-431162608).  I hope that helps.

**Comment by hajopaj** [comment]
This truly could be the problem I am experiencing. Have to try it out...
Thanks for helping! 
I will tell you what happened.👍🏼

**Comment by hajopaj** [comment]
It worked! The credentials could be found in another .xml file.
I changed the keys in the config.json accordingly ans since then everything ist Wirkung fine. Thank you very much!

**Comment by Jefronty** [comment]
Glad it worked.
