### ISSUE TITLE
Homebridge Node warning, tried unintalling and reinstalling help please!

### ISSUE THREAD

**Issue by nebdy** [nfarina/homebridge#2013]
homebridge wont start!

I have run
   sudo npm uninstall  homebridge -g

and then 
   sudo npm install -g --unsafe-perm homebridge

But each time i get the following error on startup

Error: The module '/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)

Any help thoughts please?

Happy to nuke and start again

**Comment by pponce** [comment]
what version of Node are you using?
Also insure that the node version that sudo is using is the same as the node version that the homebridge user ends up using. I had a similar problem and didn't realize the issue was different node versions in use by different users.
run 
sudo which node
and then run
which node

if they are different that may point to your issues.

I use node version manager to manage my node versions.
https://nodejs.org/en/download/package-manager/#nvm

But sudo was still using the node version installed by apt-get even though i had installed node version 8 via nvm.
So i also followed the directions to update my linux distro to the same version 8 of node i installed via nvm.
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

There was probably a way to get sudo to use the node version as installed by nvm but i didn't look into it.
