### ISSUE TITLE
Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by henkied** [nfarina/homebridge#2031]
node --version => 08.12.0
homebridge --version =>0.4.45

**Usage**:

Homebridge installed via docker on my Syonlogy. Removed all plugins, so no plugins installed at the moment

**Problem:**

Error: Service name is already in use on the network
at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
at emitTwo (events.js:126:13)
at EventEmitter.emit (events.js:214:7)
at Socket. (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
at emitTwo (events.js:126:13)
at Socket.emit (events.js:214:7)
at UDP.onMessage (dgram.js:659:8)

**Current Behavior**
Homebridge keeps starting up with this error message so it does not come online

**Steps to Reproduce**
1. container and image removed.
2. all folders deleted / docker and docker / homebridge
3. package removed.
4. then everything reinstalled.

_Unfortunately I keep getting this error message_

**Comment by iRayanKhan** [comment]
is the instance still running?
Two things you can try:
On a linux/raspberry pi type or try: sudo killall homebridge
Or disconnect your modem from power and let your Wi-Fi disconnect from all devices

**Comment by henkied** [comment]
Yes he is still runing.
Homebridge is installed on a synology via Docker. I do not know how you can shut down everything there.

I have restarted the synology. I also switched off my router and modem and restarted it in a few minutes.

No effect!

**Comment by chiaruz** [comment]
Same problem... I'm using pfSense 2.4.4 as router with the Avahi service enabled.

I discovered that the "Reflect incoming mDNS requests to all local network interfaces" is the cause of the issue.

**Comment by iRayanKhan** [comment]
Try to kill the docker instance and completely restart Homebridge

**Comment by chiaruz** [comment]
> Hi! I got the same problem, Could someone show me how to fix it?
Hi KhMeRA , 
Your issue could be caused by the router if a the mDNS broadcast functionality active. 

The solutions are 2: 
- Change the name in the conf.json file of homebridge installation (but you should do this every time you restart the service)
- Verify the router. I had the issue with pfSense, 

I discovered that the "Reflect incoming mDNS requests to all local network interfaces" is the cause of the issue. pfSense advises that "Disabling the cache can help with object duplication when reflecting"

**Comment by iRayanKhan** [comment]
Or sudo killall homebridge

**Comment by KhMeRA** [comment]
Thanks all. Yesterday I just found out that, My Ring floodlights and Spot lights causing this problem. As long as I removed all floodlight and spotllight, just keep ring alarm and doorbell, my homebridge is working fine. As soon as I put any one of them back, I got the same error, Error: Service name is already in use on the network. 
Now I know the root cause but how to fix it.

@iRayanKan, what killall homebridge would do? just to stop homebridge from running? By the way, I am using docker on synology, still that command "sudo killall homebridge" work?

**Comment by KhMeRA** [comment]
@chiaruz,  "Disabling the cache can help with object duplication when reflecting". how can I do that?

**Comment by chiaruz** [comment]
> @chiaruz, "Disabling the cache can help with object duplication when reflecting". how can I do that?

I have a Ring Door Peep Cam on my network active and I don't have the problem.

On pfSense you sould go on Service -> Avahi and Remove the flag in the section "Enable reflection"
![image](https://user-images.githubusercontent.com/1955746/64966863-779dc380-d897-11e9-9249-dff1ef4f4534.png)

This solved the issue on my network. If you have a different router probably is better to verify the manual. The issue could be caused by a mDNS "reflector"in the network: this kind of service caches the name of the Bonjour/mDNS client and broadcast it across the different networks.

**Comment by KhMeRA** [comment]
I have Ubiquiti USR router. There is an option to turn on Multicast DNS.
This option was turn off right now. Should I turn it on?

**Comment by chiaruz** [comment]
You can try to give a look to these link:
https://community.ui.com/questions/mdns-reflector-help-computer-name-keeps-changing/180dd51f-a5b2-465c-88c2-6e85ab03c38a
https://community.ui.com/questions/run-mDNS-without-the-enabling-the-reflector/ed491791-9a56-4c5f-8f19-faa544ab1ce9

**Comment by MikeJ67** [comment]
I found out, how it came to the exact same error in my system. Full documentation can be found here

https://community.home-assistant.io/t/after-some-slight-changes-node-red-doent-start-anymore-service-name-is-already-in-use-on-the-network/746750/5

In short; I am migrating from an "old" system (a simple raspi with Node-Red (NR) on it) to a new Yellow with a lot more storage capacity. During copying nodes from the old to the new system I seem to have also copied a configuration block to the "old" HomeKit-bridge entry. Therefore I suddenly had two configurations for the same advertiser "bonjour-hap", which lead to the crash of NR on the new system, and which also prevented NR to re-start with the mentioned error message "Error: Service name is already in use on the network". This advertiser is part of the configuration block.

The simple solution was to download the `flows.json` file via Samba (use your prefered method), open it with vs code (again, choose yours), find the appearances of "bonjour-hap" in it, and remove one of it. The re-upload `flows.json` back into your system. Then re-start Node-Red.
