### ISSUE TITLE
Handle/retry network failures

### ISSUE THREAD

**Issue by longzheng** [nfarina/homebridge#2053]
Homebridge seems to crash when the network interface is disconnected (e.g. router restart).

Pasted exception below.

### Expected Behavior

Homebridge retries until network is restored.

### Current Behavior

Homebridge crashes.

### Steps to Reproduce (for bugs)

1. Start homebridge
2. Disconnect network

### Versions

- **Homebridge**: `homebridge --version`
0.4.45
- **Node**:       `node --version`
v8.11.1
- **OS**:         
Windows 10 1803

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": 51826,
        "pin": "xxx"
    },
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "..."
                }
            ]
        }
    ]
}
```

### Homebridge Log / Command Output

```
dgram.js:601
    throw errnoException(err, 'setMulticastInterface');
    ^

Error: setMulticastInterface EADDRNOTAVAIL
    at _errnoException (util.js:1022:11)
    at Socket.setMulticastInterface (dgram.js:601:11)
    at Timeout.that.update [as _onTimeout] (C:\Users\Long\AppData\Roaming\npm\node_modules\homebridge\node_modules\multicast-dns\index.js:141:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by ebaauw** [comment]
Did you restart homebridge after disconnecting the network?  If not, does the error happen immediately after disconnecting the network, after a while, or when re-connecting the network?

See also #1948: there’s something odd since homebridge switched to the native Javascript mdns implementation, but I haven’t seen any crashes before.  Maybe specific to Windows?

**Comment by longzheng** [comment]
Actually I just did a few manual disconnects (unplugging/replugging LAN cable) and it did not seem to trigger this problem. I'm no longer confident that this issue is caused by the network disconnect then.

In any case, do you think it would be wise to maybe try/catch this exception so it is retried?

**Comment by ebaauw** [comment]
From the stack trace, it would seem that a timeout fired (to renew the Bonjour announcement?) somewhere in the multicast-dns module.  This module is used by hap-bonjour, which is used by homebridge.  The try/catch would have to be in the multicast-dns module, instead of in homebridge.  I’m not sure what corrective action we’d need to take in the catch.  If the exception would cause the Bonjour announcement to be dropped, homebridge would still be running, but no HomeKit app would be able to find it.

**Comment by the-ress** [comment]
mafintosh/multicast-dns#56 could fix this.
