### ISSUE TITLE
Homebridge on a VPS?

### ISSUE THREAD

**Issue by jacc** [nfarina/homebridge#2065]
Hello everyone.

I’ve been looking at an LED controller that is compatible with Homebridge. However, I realized that I don’t have a Pi to run it on. I do however, have a VPS from a friend at a hosting company. Would it be possible to run Homebridge on the VPS and still control my devices?

Cheers, Jack

**Comment by ebaauw** [comment]
homebridge needs to run on the local network (where you iDevices run on).  If you have a bridging VPN into the VPS it might work, but I wouldn't bet on it.

The connection from homebridge to the device depends on the plugin and the device; e.g. homebridge-hue can access a Hue bridge or deCONZ ZigBee gateway over a routed network (although UPnP discovery might be challenging), but Sonos speakers can only be accessed from the local network, so homebridge-zp needs to run locally..

**Comment by iRayanKhan** [comment]
I tried this, but it won't work unless:
- You add Homebridge to the iDevice when they are on the same network
and secondly have a HomeHub on that vps network.

**Comment by TheRealMaN** [comment]
I'm successfully running Homebridge in a Docker container on remote VPS. No problems or delays. You don't need a VPN for that, but you need to advertise the bridge on a local network through mDNS so that you Home app could see it. You can use macOS terminal command, Node library Bonjour or Ciao, linux Avahi library or Arduino library with ESP8266 module.

## Get config from Homebridge remote server
Also you need to get the bridge parameters from the running Homebridge container. You can do this by running the console command inside the container installing the avahi-utils (avahi should be listed as default service in your homebridge.conf) and then resolving mDNS record from "_hap._tcp" service like this:

```sh
apt update && apt install avahi-utils
avahi-browse -r _hap._tcp
```

Now save the printed configuration for later and choose your way to run mDNS announcer on your local network.

There are different options:

## macOS
```sh
dns-sd -P "Homebridge A3BA 0694" _hap._tcp local 51226 "myvps.ddns.net" "23.100.200.1" "pv=1.1" "ff=0" "s#=1" "md=homebridge" "c#=4" "id=05:5F:66:56:A3:BA" "sf=0" "ci=2" "sh=3E6uB3=="
```

## Node
You can announce using Node with these libraries:
* [Bonjour](https://github.com/homebridge/bonjour)
* [Ciao](https://github.com/homebridge/ciao)

Code example:
https://github.com/TheRealMaN/mdns-announcer-public/blob/main/app/via-bonjour.js

## ESP8266
[Description](https://github.com/TheRealMaN/mdns-announcer-public)
Code example:
https://github.com/TheRealMaN/mdns-announcer-public/blob/main/app/via-esp8266/via-esp8266.ino
