### ISSUE TITLE
Restarting homebridge can break everything

### ISSUE THREAD

**Issue by netRunner0** [nfarina/homebridge#2085]
Restarting homebridge can break everything...

He worked for a long time. I updated the plugin via web-ui, restart the homebridge.
More it is not available for the program Home.

I tried all the new options linked to:
mdns
disable ipv6
disable AppleTV home gateway
delete persist and accessories folders
http://10.0.0.40:51826/accessories - very good

Avahi log:
`=;eth0;IPv4;Home10-97B0;_hap._tcp;local;0E_78_BE_A8_68_62.local;10.0.0.40;51826;"sh=JxpvbA==" "sf=1" "ci=2" "ff=0" "s#=1" "c#=11" "id=0E:78:BE:A8:68:62" "pv=1.0" "md=Home10"`

`983	5.223333	10.0.0.40	224.0.0.251	MDNS	385	Standard query response 0x0000 PTR Home10-97B0._hap._tcp.local SRV 0 0 51826 0E_78_BE_A8_68_62.local TXT A 10.0.0.40 AAAA fe80::c70a:d226:ea0e:4191`

` EventedHTTPServer [::ffff:10.0.0.7] New connection from client +30s
  EventedHTTPServer [::ffff:10.0.0.7] HTTP server listening on port 43149 +0ms
  EventedHTTPServer [::ffff:10.0.0.7] HTTP request: /pair-verify +4ms
  HAPServer [0E:78:BE:A8:68:62] HAP Request: POST /pair-verify +1ms
  HAPServer [0E:78:BE:A8:68:62] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.0.7] HTTP Response is finished +24ms
  EventedHTTPServer [::ffff:10.0.0.7] Client connection closed +165ms
  EventedHTTPServer [::ffff:10.0.0.7] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:10.0.0.7] HTTP server was closed +1ms
`

`eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.40  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::c70a:d226:ea0e:4191  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:d8:c5:86  txqueuelen 1000  (Ethernet)
        RX packets 84556  bytes 67451972 (64.3 MiB)
        RX errors 0  dropped 49  overruns 0  frame 0
        TX packets 80817  bytes 64341435 (61.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1728  bytes 310226 (302.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1728  bytes 310226 (302.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

I changed the pin and the name, and it was successfully added to the same house where all the accessories appeared ... But this is not an option, as it is necessary to reconfigure all automations!

Any ideas on how to make it work?

**Comment by netRunner0** [comment]
This problem?

EventedHTTPServer 
[::ffff:10.0.0.7] New connection from client +30s EventedHTTPServer 
[::ffff:10.0.0.7] HTTP server listening on port 43149 +0ms EventedHTTPServer 
[::ffff:10.0.0.7] HTTP request: /pair-verify +4ms HAPServer 
[0E:78:BE:A8:68:62] HAP Request: POST /pair-verify +1ms HAPServer [0E:78:BE:A8:68:62] Pair verify step 1/2 +1ms EventedHTTPServer 
**[::ffff:10.0.0.7] HTTP Response is finished +24ms EventedHTTPServer 
[::ffff:10.0.0.7] Client connection closed +165ms EventedHTTPServer 
[::ffff:10.0.0.7] HTTP connection was closed +2ms EventedHTTPServer 
[::ffff:10.0.0.7] HTTP server was closed +1ms**

**Comment by ayalon** [comment]
@netRunner0 : Ty this:
https://github.com/nfarina/homebridge/issues/2089

After a long journey, I finally found the issue and was able to fix it.
The issue is IPv6 / tcp6.

Its a bug in a library homebridge uses. See here:
https://github.com/nfarina/homebridge/issues/1277

You can check this easily using. If you see this, you are fine:

`$ pi@raspberrypi:~ $ netstat -an | grep 51826`
`$ tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN`

If you have IPv6 enabled, it will only listen on the IPv6. This also leads to erros with avahi.

First, disable IPV6 completely on your rasperrypi. I was able to achieve this by adding this too 
 `/boot/cmdline.txt` > ` ipv6.disable=1`

Then reboot and check with `ifconfig` that IPv6 is disabled.

Then disable IPv6 on avahi settings in /etc/avahi/avahi-daemon.conf:
`use-ipv6=no`

Check your bonjour dns names:

`sudo apt-get install avahi-utils`
`avahi-browse --verbose _hap._tcp`

`$  local`
`$ +  wlan0 IPv4 Homebridge_LIVE-9A81                          _hap._tcp `

Now you have to the delete the bridge and reconfigure everything from scratch, because some devices still try to connect IPv6. From then on, my Homebridge was stable.

**Comment by platini76** [comment]
don't understand this:

$ local
$ + wlan0 IPv4 Homebridge_LIVE-9A81 _hap._tcp

**Comment by netRunner0** [comment]
@ayalon In my case, this is not a solution, as a simple reset (change of pin and name) returned the homebridge back.

However, a broken homebridge could not be returned even with an empty config. I think the problem is even deeper ... I need to find it.

**Comment by ryanschmidt** [comment]
I'm not sure if it's related but I've not had this issue until upgrading from 0.4.44 to 0.4.45 yesterday. I'm now having simple restarts cause issues like described in this and other recent issue threads.

- restart homebridge
- no errors
- "no response" for all homebridge accessories

Still working to get it back up and running.
