### ISSUE TITLE
Homebridge Not Responding On All Accessories

### ISSUE THREAD

**Issue by mcmillster** [nfarina/homebridge#2089]
**Expected Behavior**
When opening "Home" on an iOS device, I should see the accessories respond and load.

**Current Behavior**
I am running my homebridge off my Raspberry Pi and my Home app is showing "No Response" on all accessories. I've had homebridge working for about 6 months with random "No Response" happening periodically and having to reset everything. I'm running an Ipad as my Home Hub.

I have tried: 
1. Restart homebridge and delete Apple Home settings
2. change homebridge name/username/pin and setup new Apple Home
3. different Wi-Fi network for both homebridge and Ipad
4. tried running homebridge from my Windows PC (Where I ran it prior to the Pi)
5. reinstall homebridge on Pi, clear "accessories" & "persist" files of cached items on homebridge. 

No matter what I try when I open my Home I get "No Response" on all accessories... Totally lost on what else to try. I haven't changed version on npm, node, Raspbian, etc.

**Steps to Reproduce (for bugs)**
See above. 

**Versions**
Homebridge: 0.4.45
NPM: 6.4.1
Node: v10.14.0
OS: Raspbian 
Ipad: 12.1.1

My Config, "###" blocking out info, not actually in my config.

```
{
  "bridge": {
    "name": "McChillen's Homebridge",
    "username": "CC:22:3D:E3:CE:14",
    "port": 51826,
    "pin": "049-56-013"
  },

  "description": "",

  "platforms": [
    {
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "###",
      "accessories": [
        {
          "name": "Open West Garage Door",
          "buttons": [
            {
              "caption": "A1-1",
              "triggerOn": "openWest",
              "triggerOff": "closeWest",
              "stateful": true
            }
          ]
        },
        {
          "name": "Open East Garage Door",
          "buttons": [
            {
              "caption": "A2-1",
              "triggerOn": "openEast",
              "triggerOff": "closeEast",
              "stateful": true
            }
          ]
        }
      ]
    },

    {
      "platform": "Venstar",
      "auth": {
        "user": "###",
        "pass": "###"
      },
      "thermostats": [
        {
          "name": "Home",
          "uri": "https://192.168.1.29"
        }
      ]
    }
  ],
  "accessories": []
}

```

**Comment by W0GER** [comment]
If you have an Apple HomePod or Apple TV, try rebooting them. They participate in the HomeKit integration. 

When you start homebridge, are you getting any errors in the log or output?

**Comment by krisrice** [comment]
I'm having the same issue.  The console log shows valid data from my 2 configurations  Nest and Dyson. However the Home ios/laptop app all accessories show No Response

**Comment by alexij1997** [comment]
I have same problem

**Comment by iRayanKhan** [comment]
Delete Persist and Accessories folder and re add home bridge

**Comment by krisrice** [comment]
Didn't work. Only thing that worked was purge the caches, remove the dyson, remove the hub, change the hub id, then restart and re-add the 'new' hub.

**Comment by iRayanKhan** [comment]
Just had this issue appear today.

**Comment by iRayanKhan** [comment]
So I had a garage too using a different plugin "Lift Master" I changed to chamberlain and It worked. for Syntax Pos 0. or there's an "N" key in your config mis placed. I am trying to find an SD card reader to wipe my Pi and start again as I believe my "Homebridge-roomba-stv" plugin has broken my HomeBridge. I plan on using 2 Homebridge instances now to separate the Confirmed working and the Experimental ones.

**Comment by ayalon** [comment]
After a long journey, I finally found the issue and was able to fix it.
The issue is IPv6 / tcp6.

Its a bug in a library homebridge uses. See here:
https://github.com/nfarina/homebridge/issues/1277

You can check this easily using. If you see this, you are fine:

`$ pi@raspberrypi:~ $ netstat -an | grep 51826`
`$ tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN`

If you have IPv6 enabled, it will only listen on the IPv6. This also leads to erros with avahi.

First, disable IPV6 completely on your rasperrypi. I was able to achieve this by adding this too 
 `/boot/cmdline.txt` > ` ipv6.disable=1`

Then reboot and check with `ifconfig` that IPv6 is disabled.

Then disable IPv6 on avahi settings in /etc/avahi/avahi-daemon.conf:
`use-ipv6=no`

Check your bonjour dns names:

`sudo apt-get install avahi-utils`
`avahi-browse --verbose _hap._tcp`

`$  local`
`$ +  wlan0 IPv4 Homebridge_LIVE-9A81                          _hap._tcp `

Now you have to the delete the bridge and reconfigure everything from scratch, because some devices still try to connect IPv6. From then on, my Homebridge was stable.

**Comment by mcmillster** [comment]
@ayalon awesome! Tried this and it fixed everything immediately. I'm not able to access the Home app from outside my network, but I'll troubleshoot that separately.

**Comment by iondarie** [comment]
Hello,

I am facing the same NO RESPONSE on all accessories, tried the suggested fix but the issue remains...

Any ideas what else i can try?

**Comment by snielsen** [comment]
I experienced this recently and it was driving me insane. I followed every recovery step I could find, but to no avail. Last night I finally tracked down what it was in my case. 

I could find and add my Homebridge just fine. All the accessories would show up, the HomeKit devices would query for state, I would see the result and response of the queries in the Homebridge log, but Home.app in iOS would display all accessories as "Updating" and would eventually timeout and be marked with "No Response".

Apparently, a single plugin can block responsiveness for all accessories. When queried, one of my plugins, https://github.com/gbro115/homebridge-roomba690, would attempt to contact my Roomba to get the state. My Roomba had a dead battery and I hadn't bothered to recharge it yet, so it was uncontactable. The plugin wasn't written with any logic to detect the case where the target Roomba is offline and so it would never perform the requisite callback back to Homebridge. Thus, Homebridge would just sit there, waiting forever for the answer to the query and never respond back to HomeKit with any information at all. Removing the plugin or charging the Roomba brought everything back to life. 

While the plugin is certainly not written correctly to handle these kinds of scenarios, I feel like it's also a bug that Homebridge can be silently blocked (no errors, no logging to suggest what's going on) by any single, bad actor plugin. 

Relevant issue: **One accessory blocks the whole homebridge** https://github.com/nfarina/homebridge/issues/948

**Comment by rcarmo** [comment]
I just had this happen to me for the third time in six months without apparent cause (I use very few plugins since I rely almost exclusively on https://github.com/cflurin/homebridge-mqtt), and there was nothing on the logs.

The only way to fix things was to remove and re-add everything, and it would be nice to have a cleaner way to recover from this.

**Comment by TRColT** [comment]
Maybe it could help someone it the future. 
Just had the same issue this morning after adding my GF Ipad as a Hub. Everything wokred great before doing this. I looked at the log and it turns out to be the tuya platform trying to get info from a smart plug that I don't use anymore and wasn't plugged in. Deleted the accessories and everything is back on track.

**Comment by iRayanKhan** [comment]
@TRColT, which Tuya plugin were you using?

**Comment by TRColT** [comment]
I think it was "homebridge-tuya".

**Comment by danielk117** [comment]
> For everyone running the docker image, adding the following to `startup.sh` in your shared homebridge folder does the trick, even when the container is rebuilt:
> `sed -i.bak "s/this._tcpServer.listen(targetPort);/this._tcpServer.listen(targetPort, '0.0.0.0');/" /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js
`
> _Originally posted by @mrvnklm in https://github.com/homebridge/homebridge/issues/1277#issuecomment-504532025_

This helped me (canged folder according to @mrvnklm answer):
```
sed -i.bak "s/this._tcpServer.listen(targetPort);/this._tcpServer.listen(targetPort, '0.0.0.0');/" /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js
```

before:
```
$ netstat -an | grep 51677
tcp6       0      0 :::51677                :::*                    LISTEN     
```

after:

```
$ netstat -an | grep 51677
tcp        0      0 0.0.0.0:51677           0.0.0.0:*               LISTEN     
```
