### ISSUE TITLE
Help required: Boiler/hot water temperature

### ISSUE THREAD

**Issue by yozik04** [nfarina/homebridge#2103]
I have a boiler where I have two temperature sensors.
I would like to see them in HomeKit.

The problem is that if I set type to temperatureSensor Homekit thinks it is a room temperature sensor.
If I ask "What is current temperature of the house", the response comes "from 23 to 56 degrees".

How to bypass that?

I am using homebridge-mqttthing plugin.

**Comment by ebaauw** [comment]
Not that I know of.  I’m facing the same issue with my outdoors temperature sensor.  You could place the boiler in a different HomeKit home, but switching homes is probably more of a nuisance than Siri reporting the temperature range.  Alternatively, create a zone or group and ask Siri for the temperature of that, instead of the house

**Comment by NorthernMan54** [comment]
I too have numerous sensors, and when I want to know the temperature I have to remember to ask for each by name.

**Comment by nielsth** [comment]
Does it help to disable the option Include in Status for this sensor (under Settings > Status and Notifications)?

Otherwise I'd suggest to file a feature request with Apple at bugreport.apple.com to be able to add different types of temperature sensors.
