### ISSUE TITLE
Change default port 80 and 443 to other?

### ISSUE THREAD

**Issue by varna33** [nfarina/homebridge#2199]
I can not run homebridge on default 80 and 443 ports as they are used for other purpose.
Is it possible to change 80 and 443 to different ports in homebridge for Apple HomeKit to access it correctly?

Janis

**Comment by varna33** [comment]
I can not run homebridge on default 80 and 443 ports as they are used for other purpose.
Is it possible to change 80 and 443 to different ports in homebridge for Apple HomeKit to access it correctly?

Janis

**Comment by NorthernMan54** [comment]
Homebridge can use any port, just set the setting in config.json.

Typically people use port 51826

**Comment by varna33** [comment]
This is homebridge port. I can change that, but it doesn't help.
As I use 80 and 443 for other purposes and when they are active, then HomeKit is not anymore able to access Homebridge Accessories, even Homebridge is running and I can access it for configuration needs.
I was asking about the ports HomeKit is using to access to homebridge.

**Comment by ctgreybeard** [comment]
Homekit and Homebridge can use basically any port, usually a high numbered port chosen randomly from a range. My own Homebridge is currently using 56578 but has used ports between 49173 and 65377. You can see the port that it has chosen in the log during startup. It will never, however, use 80 or 443 for Homekit. If you are having a conflict it may be because of some plugin you have installed.

**Comment by arvidcarlander** [comment]
The default homebridge installation listens to port 80. How can that be changed?
