### ISSUE TITLE
Homebridge devices disappear and/or are all in one room

### ISSUE THREAD

**Issue by luissimoes** [nfarina/homebridge#2225]
### Expected Behavior

Homebridge is running and shows up in Homekit::Home
Sharing the Homekit:Home with someone else results in this person seeing (and possibly controlling) the ::Home devices. The devices show up in the Rooms the Homekit::Home creator has defined

### Current Behavior

The devices show as expected and then some time after (could not find a pattern) some **disappear** and **most are all gathered in one of the rooms**.

Even when the person that got the ::Home shared has rights to change the location - this happens again and again.

### Steps to Reproduce (for bugs)

Remove everyone from the shared ::Home
Go to each of their devices and make sure they are not seeing ::Home
restart iPhone
Go back to original Homekit::Home and invite person again

---> after some time it happens again

### Versions

- **Homebridge**: 0.4.49
- **Node**:       10.15.3
- **OS**:         Raspbian Version 9

### Configuration

```json
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
 
        "accessories": [
        ],

        "platforms": [
            {
                "platform": "config",
                "name": "Config",
                "port": 8080,
                "sudo": true,
                "restart": "sudo -n systemctl restart homebridge",
                "log": {
                        "method": "systemd",
                        "service": "homebridge"
                        }
            },
		{
		"platform": "HomeMatic",
           	"name": "HomeMatic CCU",
           	"ccu_ip": “removed….XXX.XXX.XXX.XXX”,
           	"filter_device":[],
           	"filter_channel":[],
           	"outlets":[],
           	"doors":[],
           	"programs":[],
           	"subsection":"Homekit"
		},
		{
        	"platform": "RademacherHomePilot",
        	"name": "RademacherHomePilot",
        	"url": "removed….XXX.XXX.XXX.XXX"
      		}

        ]
}
```

### Homebridge Log / Command Output

```

```

**Comment by Xusqui** [comment]
Same here. 
Sometimes the rasp reboots itself (I guess it reboots because if I perform a “uptime” coammand, the uptime is just a few hours) with no reason, and after comming back, all the accessories are moved to the room where the hombridge is placed. They are all displayed as new accesories, so I loose all my automations. 

Thanks in advance!

**Comment by rcoletti116** [comment]
This is happening to me, but I don't think its related at all to home sharing. Out of nowhere devices disappeared, then reappeared in Default Room as new devices (losing automations and scenes).

It happened once a few weeks back and I got burned by losing my automations. I got set up with Controller for HomeKit to create backups. Now its happened again, thankfully restoring from backup works, but occurring frequently is frustrating. I'm curious if anyone else has experienced this. Since this issue is stale maybe its a very rare bug. As of today running latest, 1.1.6.
