### ISSUE TITLE
can't add homebridge to iOS 12.3

### ISSUE THREAD

**Issue by yhur** [nfarina/homebridge#2236]
Hi,

I had added my RPi homebridge to my iPhone some time ago. I don't remember which iOS version was when I added. And I had been using the homebridge fine. But when I removed the homebridge from the iOS and tried to add, the homebridge is not showing up. I tried to add with the numbers manually, but that didn't work either.

Has there been any change with the IOS that prevents the Homebridge from adding/working?

Regards,
Yoonseok

**Comment by igorhou** [comment]
Delete persist folder reboot RPi and try again.

**Comment by mafyata** [comment]
Just change username and pin in config.json

**Comment by yhur** [comment]
Thank you igorhou and mafyata. 

Your old tricks are not for this situation, though. I have an iPhone 5 which is at 10.3.3. That shows and connect to the homebridge successfully while my iPhone 6S with 12.3.1 doesn't.

**Comment by yhur** [comment]
Hi @igorhou, 
My sincere apology. With some doubt, but to double check, I just deleted the persist & reboot, then the home bridge shows and connects to my iPhone. So your suggestion worked great here.

So I guess it's not about the iOS version differences. Thanks again.

**Comment by dkossman** [comment]
Everything was working reliably up until a few days ago, not sure what changed, but my homebridge accessories stopped responding today.  so  i deleted the homebridge accessory, but am unable to add it back.

i've tried deleting the persist folder, changing the username and pin in config.json, but with no luck.  I have also now updated to the latest version of homebridge. I'm running on a Raspberry Pi under Raspbian Jessie (updated as well).  Homebridge starts up fine.

The Pi and my iPhone (iOS 12.3.1) are on the same wifi network.  

I saw some posts about forcing homebridge to listen on a particular interface, but my Pi only has one interface so that can't be the problem.

any suggestions would be appreciated.

**Comment by yhur** [comment]
@dkossman 
Actually, the problem I had was resolved by disabling the WMM on my new Access Point.

To describe it a little bit more, I had set up the homebridge and my iPhone home app with an Access Point and used it happily for some time. Some time ago I changed my AP, and the configuration was still happy until I removed the home kit setup and tried to re setup it on my iPhone, then I couldn't discover the homebridge. Without a doubt about the new AP, I suspected the iOS version, so I started this thread. And realized my iPhone could discover it successfully if I set up the homebridge in a different lab/network, then started to poke around the AP network setting. Finally I can discover and configure the home kit on my iPhone after I disabled the WMM setting on the new AP.

Hope this helps.

**Comment by dkossman** [comment]
Hi @yhu thanks for your reply.  In my case, I'm using an older Apple Airport Extreme, which does not support WMM.  Apple did issue a firmware update for this device a week or two ago, which I installed - I wonder if that could be the problem?

**Comment by mafyata** [comment]
I am using two airport extreme routers. They are updated to latest firmware a week ago and afterthat I haven’t got a problem. 4 days ago I installed the new raspbian buster on new sd card and installed homebridge, everything is fine. Added homebridge to ios without a problem.

**Comment by yhur** [comment]
@dkossman 
I guess it's a different problem then.
