### ISSUE TITLE
Homebridge syntax error

### ISSUE THREAD

**Issue by sacheswart** [nfarina/homebridge#2285]
I am busy with the Homebridge config.json file. Every time I get an error message (config.json syntax error) what am I doing wrong and can someone help me? This is the following script

{
    "mdns": {
        "interface": "192.168.178.50"
    },
    "bridge": {
        "name": "homebridge",
        "username": "22:34:56:78:9A:BC",
        "port": 41813,
        "pin": "031-45-154"
    },
    "description": "piet",
    "platforms": [
        {
            "platform": "config",
            "name": "config",
            "port": 8080,
            "sudo": false
        }
    ],
    "accessories": [
        {
            "name": "Woonkamer",
            "apiroute": "http://192.168.1.33",
            "accessory": "Daikin-Local"
        },
        {
            "name": "Slaapkamer-1",
            "apiroute": "http://192.168.1.33",
            "accessory": "Daikin-Local"
        },
        {
            "name": "slaapkamer-2",
            "apiroute": "http://192.168.1.33",
            "accessory": "Daikin-Local"
        }
    ],
    "platforms":[
        {
            "platform": "Tahoma",
            "name": "My TaHoma Box",
            
            "user": "user@me.com",
            "password": "MyPassw0rd",
        }
    ]
}

**Comment by tknz** [comment]
You have two platforms section in the JSON file,

1 adding the config platform at line 12, then again at line 34 adding Tahoma.

Take another look at the sample configuration files, you can only add all platforms in the platform section and accessories later e.t.c.

Presumably you have an iPhone because you're going down the homebridge path, give this app a go. He makes life super easy in an IOS App to configure Homebridge.

https://linkdhome.com/articles/2019/5/1/set-up-homebridge-easily-with-an-app

https://apps.apple.com/au/app/homebridge-for-raspberrypi/id1123183713
