### ISSUE TITLE
Hue Homekit & Homebridge?

### ISSUE THREAD

**Issue by dreameruk** [nfarina/homebridge#229]
Now Hue have officially released Homekit support, any ideas what will happen if 'upgrade' my bridge to new 'Homekit bridge' assume will get confused with Homebridge via Pi? 

https://www.facebook.com/huePhilips/videos/744903252308228/

**Comment by snowdd1** [comment]
By 'upgrade' you say 'buy the new one'?

**Comment by maddox** [comment]
It should just show up as a second bridge right next to Homebridge. Theoretically it should work just fine.

**Comment by stephenyeargin** [comment]
I updated my Hub software this morning and it continued to work (granted, I didn't test everything -- I was getting on an :airplane: out of town).

- If you own a round hub (1.0), use `homebridge` per usual. The firmware update seems to simply opened up a migration path for data stored on the 1.0 bridge to the 2.0 bridge.
- If you buy the square one (2.0), there's not an obvious benefit to using `homebridge` other than the warm fuzzy feeling you get for hacking hardware. :grin:

Reference: http://www.macrumors.com/2015/10/05/philips-hue-bridge-with-homekit/

**Comment by dreameruk** [comment]
Benefit is you can set moods containing not yet supported devices like Nest and Wemo. Especially as it looks like Nest will never officially work with Homekit.

**Comment by justme-1968** [comment]
actually i think i still prefer the integration via homebridge and my fhem shim instead of the new hub as it will give me one single point of control in fhem with an always up to date status. as long as the hub has no push api controlling it from multiple points will just result in the different apps having a different current status till the next polling is done. polling too frequently is bad.

ps: of course i will buy the new hub. maybe there will be other changes beside homekit integration...

**Comment by kaiguy** [comment]
The reason I would like to use homebridge is if I have non-homekit lights being controlled by the Hue bridge 2.0.  The problem, it seems, is that all my official Philips lights are then duplicated as far as Homekit is concerned.  Any suggestions for how to continue to control non-homekit bulbs via Homebridge without this duplication issue?

**Comment by nfarina** [comment]
@kaiguy Do you mean that non-Hue lights can be controlled by Hue Bridge 2.0 but aren't exposed to Siri? That doesn't make sense to me... It seems you should be able to use the new Hue Bridge and just disable the hue homebridge plugin (that's what I've done).

**Comment by kaiguy** [comment]
@nfarina Correct.  So non-Hue lights are able to be controlled by the Hue Bridge 2.0, but as a result of Philips firmware as of sometime in Nov/Dec does not allow those non-Hue bulbs to be controlled by Siri/Homekit.  

To overcome that limitation, Homebridge with the Philips Hue plugin does allow me to control the non-Homekit lights.  But, as mentioned, the side effect is the duplication of the other Homekit-enabled (Hue) bulbs.  Not a big deal if you only have a few lights, but def difficult when you have many (especially since the names are exactly the same).

**Comment by damianromanowski** [comment]
If you have a hue 2.0 bridge that is connected to your homekit setup you should remove the homebridge hue plugin. No reason to have two instances of the same lights.

**Comment by kaiguy** [comment]
@damianromanowski the reason to include the hue plugin is so I can have Siri control those non-Homekit bulbs.  If there is some other way to control those bulbs without using the Hue plugin for Homebridge, I'm all ears!

**Comment by damianromanowski** [comment]
@kaiguy If you have a 2.0 bridge then all the lights associated with it can be controlled via Siri. What non-homekit bulbs are you referring to?

**Comment by kaiguy** [comment]
@damianromanowski Nope.  Philips claimed that Homekit support for 3rd party bulbs was a "bug" that they squashed.  No longer possible.  For further reading: http://www.developers.meethue.com/documentation/3rd-parties-and-homekit

Examples of bulbs that can be controlled by Hue Bridge 2.0 but not Homekit: Cree, GE, Dresden FLS-PP lp LED strip ballast, etc.

**Comment by damianromanowski** [comment]
@kaiguy Interesting.. I had no idea the hue bridge could interface with non-hue bulbs. I learned something just now lol. I guess your only option would be to modify the plugin itself and exclude all the hue bulbs, while allowing everything else to be registered.

**Comment by kaiguy** [comment]
@damianromanowski Agreed.  I reached out to the author of the Hue plugin about it, but unfortunately I personally don't have enough knowledge to implement.  Some switch to be able to not expose anything from "Philips" or "Hue" would probably be all it needs, I'd think.

**Comment by damianromanowski** [comment]
@kaiguy If I have some spare time I'll take a look into developing you hue bulb exclusion. No promises though :)

**Comment by kaiguy** [comment]
@damianromanowski Haha.  Fair enough!  I appreciate your time in responding in any case!

**Comment by brandonlang** [comment]
@kaiguy Do you have any FLS-PP lp LED strips working on homebridge with Siri?
