### ISSUE TITLE
Siri says wrong temperature IOS 13.1.2

### ISSUE THREAD

**Issue by DewGew** [nfarina/homebridge#2330]
I Use homebridge - eDomoticz plugin. I have  issue with temp in IOS13.1.2 Shows correct in the Home app (16 C) and in homebridge UI X but Siri says its -8.88888888888888889 C. 
Is it the plugin,  homebridge or IOS problem?

**Comment by shereefalkady** [comment]
I have the same issue ... 
with some of my devices and plugins only... 

you see what’s happening there is that it says 16 degrees - Siri thinks that’s Fahrenheit which is -8 Celsius ....

Ever since Siri’s last OS update this has been happening ... perhaps there’s a way in the plugins to specify Celsius so that doesn’t happen ?? Because only some of my plugins are doing that

**Comment by DewGew** [comment]
This is fixed in IOS 13.1.3 👍
