### ISSUE TITLE
QUESTION - Why homebridge won't work on Mac OS Docker

### ISSUE THREAD

**Issue by cianiandreadev** [nfarina/homebridge#2394]
Just a quick question: 

I saw in the documentation that Homebridge won't work on Mac OS on Docker.

Why homebridge will not work on MacOS Docker? What is the real issue? Is there some way to fix it?

Thanks

**Comment by dkrizic** [comment]
I have running Homebridge even in Kubernetes (twice). Since Kubernetes uses Docker internally I don't see a reason why it should not work in Docker only. Fact is, that Docker for Mac does not run natively, but in a virtual machine (based on HyperKit). This might have some networking issues and requires propers "host networking" to be setup.

**Comment by cianiandreadev** [comment]
@dkrizic indeed. I had the same doubt. Maybe some hw limitation that you cannot achieve with HyperKit?
For sure you don't have the same freedom as you have in Linux (i.e., it's really hard to access to the GPU using docker on Mac).
Would be nice to extend the homebridge docs with some more informations about it.

**Comment by cianiandreadev** [comment]
@oznu OMG. Thanks! 😄 That fast!! 😄
