### ISSUE TITLE
Hue Platform and HomeKit scenes

### ISSUE THREAD

**Issue by stipus** [nfarina/homebridge#240]
I found a problem trying to create a HomeKit scene to control hue lights through the hue platform:

Test scene is simple: switch on 2 hue lights at a specific brightness, saturation and hue.
Problem: 
1) A HomeKit scene contains a set of Actions, and sets do not maintain any order....
2) When I ask SIRI to activate the scene, actions are executed by HomeBridge in various orders..
- Sometimes HomeBridge first executes set-power-on, then set-brightness, set-hue, set-sat
- But sometimes it first executes set-brightness, set-sat... before set-power-on

This results in a Hue-API error:

First "activate scene" is OK:
[Phillips Hue] Lampe Gauche, characteristic: power, value: true.
[Phillips Hue] Lampe Droite, characteristic: power, value: true.
[Phillips Hue] Lampe Droite, characteristic: hue, value: 360.
[Phillips Hue] Lampe Gauche, characteristic: hue, value: 162.
[Phillips Hue] Lampe Droite, characteristic: brightness, value: 100.
[Phillips Hue] Lampe Gauche, characteristic: brightness, value: 100.
[Phillips Hue] Lampe Gauche, characteristic: saturation, value: 100.

Then, after turning-off the 2 lights, another "activate scene" results in a different execution order, 2 errors, and an incorrect scene.
[Phillips Hue] Lampe Gauche, characteristic: hue, value: 162.
[Phillips Hue] Api Error: parameter, bri, is not modifiable. Device is set to off.
[Phillips Hue] Lampe Gauche, characteristic: brightness, value: 100.
[Phillips Hue] Api Error: parameter, hue, is not modifiable. Device is set to off.
[Phillips Hue] Lampe Droite, characteristic: power, value: true.
[Phillips Hue] Lampe Gauche, characteristic: power, value: true.
[Phillips Hue] Lampe Gauche, characteristic: saturation, value: 100.

**Comment by vandalon** [comment]
I don't think this is a plugin issue in itself, huebridge sends the hue command before the power command, this can not be solved within the plugin.

**Comment by stipus** [comment]
I thought it might be possible for the plugin to automatically add an "ON" to the Hue command, when it processes a Brightness/Hue command for a switched-off light.

**Comment by luc-ass** [comment]
I thought about this for a while now but there is a BIG downside! It will turn on all your lamps (i.e. whole room when you just want the few lamps that are on to change)...

I my case this would turn on 5 lights in my bedroom when i just want the floor-light from 30 to 10 %....

**Comment by justme-1968** [comment]
#807 is something different. for scenes the order seems just not to be defined.

**Comment by ebaauw** [comment]
Just stumbled upon this rather old thread, but it's still open.

> for scenes the order seems just not to be defined

Indeed, but the issue is much bigger than just the order in HomeKit scenes.

HomeKit (or rather the HomeKit app or Home hub activating the scene) issues a separate event to the accessory (i.c. homebridge) for each characteristic in the scene.  A simple pass-through plugin typically translates these one-to-one into requests to the Hue bridge.  Note that homebridge handles the events from HomeKit asynchronously, and the plugin sends the requests to the Hue bridge asynchronously, resulting in multiple requests in parallel.  Even when HomeKit would send the events in the right order, the Hue bridge might receive the requests in a different order.

Turning on a light at specific colour and brightness in HomeKit requires changes to four characteristics (note that underneath, `Color` is actually two characteristics, `Hue` and `Saturation`).  HomeKit supports up to 50 characteristics in a scene.  Hence the limitation of 12 lights in the Hue app for syncing (or rather: copying) scenes from the Hue bridge to Homekit.  Even so, activating a 12-light HomeKit scene results in 48 requests to the Hue bridge, and 48 messages on the ZigBee network. There will be a noticeable delay between the changes to the different lights, which will become worse with throttling.  Without throttling, this load will likely flood the Hue bridge (especially a v1 (round) bridge) and/or the ZigBee network, resulting in some lights not changing.  When the plugin resends Hue bridge requests that timed out or failed, the bridge will definitely receive the requests out of order.

On the other hand, activating a 50-light Hue bridge scene results in a single (albeit broadcast) ZigBee message and changes all lights simultaneously  Morale: for serious home automation, use the Hue bridge instead of HomeKit to control your Hue-connected lights.  To activate a Hue bridge scene from HomeKit:
- On the Hue bridge, create a `CLIPGenericFlag` sensor and a rule to activate the scene when the sensor's `flag` changes;
- Expose the this sensor to HomeKit as a `Switch` service, using [homebridge-hue](https://github.com/ebaauw/homebride-hue);
- In the HomeKit scene, include the switch's `On` characteristic (and any characteristics for your non-Hue devices).

> this can not be solved within the plugin
> I thought it might be possible for the plugin to automatically add an "ON" to the Hue command, when it processes a Brightness/Hue command for a switched-off light.

While a plugin cannot solve the structural issues with HomeKit scenes, I see three approaches how a plugin can soften these issues, in order of increasing complexity:
1. As suggested, when a brightness or colour change is received while the light is off, include `"on": true` in the request to the Hue bridge.  As including `on` in the bridge request results in an additional message on the ZigBee network, the check that the light is off is essential.  While this would address the issue with the order, it could increase the load on the Zigbee network (up to three  (!) additional `on` messages per light when it's off);
2. When a brightness or colour change is received while the light is off, don't send a command to the Hue bridge.  Instead, save the changes to a desired state in memory.  When the `On` change is received, include the desired state in the bridge request.  This would address the issue with the order.  This could reduce the load on the Hue bridge (only one request per light) and the load on the Zigbee network (only three requests per light, as `Hue` and `Saturation` are now combined into one `xy` request), but only when the light is off, and when HomeKit sends the `On` event last;
3. When any change is received, save it to the desired state in memory, setting a timeout (of say 100ms) to send the request to the Hue bridge.  When another change is received before the timeout, it is included in the same request.  This would address the issue with the order.  It would also reduce the load on the Hue bridge and on the ZigBee network, irrespective of the light state and Homekit order of events.  It would also combine `Hue` and `Saturation` into a single `xy` Hue bridge request and corresponding ZigBee message.

Despite its complexity, I'll be implementing 3) in [homebridge-hue](https://github.com/ebaauw/homebride-hue).

**Comment by ThomasWelzel** [comment]
Is there something new?
