### ISSUE TITLE
Remote Control over cellular with Apple TV and iDevice Smart Switch

### ISSUE THREAD

**Issue by ttgolf** [nfarina/homebridge#256]
This is not an issue.  Just an quick update.

Haven been running Homebridge with my WeMo Switches for a few weeks now.  As everyone knows there currently is no way to control home bridge accessories away from home network.  I just purchased a iDevice Smart Switch (smart plug) from Lowes to compare it to Wemo.  To my surprise once it is setup (and assume you have gen 3 Apple TV), remote control away from home network is now possible.  It is now possible to use Siri to turn on my lights driving home.

**Comment by KhaosT** [comment]
Homebridge should works fine with Remote Access over Apple TV, I've being using homebridge remotely for a few months... If it doesn't work for you, try to remove the accessory from your iOS device and then re-pair the bridge.

**Comment by nzhome** [comment]
why do we need an apple tv?  can't we mimic an apple tv, and have the commands come via icloud to homebridge instead?

**Comment by KhaosT** [comment]
@nzhome HAP over iCloud requires MFi Chip.

**Comment by nzhome** [comment]
oh. can't someone make an SPI version of MFI chip and then we integrate it to homebridge via the SPI port?

**Comment by KhaosT** [comment]
MFi chip uses I2C, the only issue is that you have to be part of MFi program to purchase that chip... Redistribution of the chip violates the contract between MFi Licensee and Apple. And if you're already part of MFi, you shouldn't need this project at all...

**Comment by nzhome** [comment]
yes, still need this project, because it integrates with soo many of my devices in my house.  I just want to access them all via internet when driving home.  and the only roadblock seems to be mfi chip.   and I am positive all existing MFi members are reading this thread anyway. I don't really need a whole $199 apple tv just for that 1 feature. $27 mfi chip to SPI or mfi chip USB dongle would be good. existing mfi members reading this thread, please take note. thanks.

**Comment by khkremer** [comment]
Actually, all you need is a $69 Apple TV, which Apple will still sell after they come out with the new (and more expensive) one.

**Comment by maddox** [comment]
> Actually, all you need is a $69 Apple TV

Even if all you did was plug it in, set it up, and never use it as a a media player...and remote access is important to you...this seems worth it for the price.

**Comment by ttgolf** [comment]
I tried to remote control homebridge without the iDevice Switch but still can't get it to work.  Not sure it is because I use Wemo accessories.   Once I add iDevice Switch into my network remote control starts to work.

**Comment by luxus** [comment]
did i understand it right, a mfi chip accessory brings bridge all accessories and enable remote access for everything?
can anyone confirm that the new philips hue will help to get remote access to the homebridge?

**Comment by KhaosT** [comment]
@luxus that's not accurate. Each accessory needs to implement HAP over iCloud and communicate directly with iCloud. Having other HomeKit accessory that supports HAP over iCloud won't magically enable Remote Access for other accessories.

**Comment by ttgolf** [comment]
OK now I am confused too..  In my setup without mfi accessory (Wemo) I could not get remote control to work.  But with a mfi accessory in the setup now remote control is working for everything.

**Comment by fitzage** [comment]
So let me get this straight: If I am using Homebridge and I have an Apple TV (third gen) I should be able to control things via my phone when off-network?

I haven't got this to work.

**Comment by KhaosT** [comment]
@fitzage it should work. If it didn't work for you, please try to sign out iCloud from Apple TV, reboot Apple TV, sign in iCloud on Apple TV. Make sure during the whole process, your iOS device is in the home network and all accessories are reachable.

**Comment by fitzage** [comment]
@KhaosT Tried that again, no luck. And it's a black box, so I don't have any way to test it.

I can't find any info on router setup, so I would guess nothing special needs to be done there.

**Comment by fitzage** [comment]
@ttgolf So when you added the Smart Switch, you were able to start controlling ALL devices that were part of homebridge from off network? Like having a certified device finally kicked the Apple TV into gear or something?

**Comment by nfarina** [comment]
I've been able to remotely control homebridge via my Apple TV from the beginning - and I don't have any other HomeKit devices besides homebridge. I wish I could tell you how I did it, but it "just worked" for me. I didn't even realize it was possible until I tried it!

**Comment by KhaosT** [comment]
@fitzage no extra is setup required on router side. It's a known issue that for some iCloud accounts, remote access may simply not work, you can try to connect Apple TV to your Mac, open Xcode/Apple Configurator and try to get Apple TV log from console. HomeKit and IDS will print information about why setup failed.

**Comment by SphtKr** [comment]
Hmm...I'm in the boat of not being able to get it to work also. I bought a ATV3 just for this purpose and it's annoying. I've reset HomeKit configuration and I also have added "real" HomeKit devices to my network (Eve devices). I figured it was excluding non-certified devices, it's nice to know that's not the case and at least for some people it works!

**Comment by KhaosT** [comment]
@SphtKr Can you try this, reset the HomeKit Configuration again, sign out the iCloud account from Apple TV, reboot all the things, sign in iCloud on Apple TV, wait 5mins, create a home on iOS device, wait maybe 1 min, start the bridge with all hap-nodejs debug info, pair with the accessory, wait for 1~5 mins, check the hap-nodejs logs and see if "/pairings" get invoked?

**Comment by SphtKr** [comment]
@KhaosT I will do that, I'm reseting my config after the UUID change pull request anyway. I'll get back to you tomorrow, it's still saying "iCloud data sync in progress" :-/

Hmm...you know, I wonder if some of this has to do with how iCloud keychain is set up. There's a big difference in whether you use a PIN code or not (only approve from another device)...I have only done the latter, which means my keychain never gets uploaded to iCloud--at least according to what I read when iCloud Keychain was first introduced in...iOS 7? And I also remember iOS telling me that iCloud Keychain had to be setup for iCloud sync of HomeKit to work.

Could everyone on the thread list whether it's working or not for them, and whether they add additional devices to iCloud keychain via a PIN/password or approval via another device only?

**Comment by KhaosT** [comment]
@SphtKr there is a monthly limitation on number of times you can reset iCloud Container for HomeKit related stuff... so if you are experiencing "data sync in progress" for over an hour after reset, you may hitting that limit.

I have been using both approve with device and approve by PIN, it shouldn't matter how you add your device to trust circle. The only issue with iCloud Keychain is that sync mechanism isn't really reliable, sometime it may takes hours for iOS device to actually get the updated keychain db which HomeKit relies to decrypt home information.

**Comment by khkremer** [comment]
BTW: If anybody is interested in an AppleTV, I received a Groupon offer
today with refurbished AppleTVs for $49

And, just in case: I don't have any financial interest in Groupon, I am
just an occasional customer.

Here is the link:

https://www.groupon.com/deals/gg-apple-tv-with-1080p-hd-manufacturer-refurbished?p=1


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by SphtKr** [comment]
@KhaosT Hmm... So I see:

    HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings +0ms
    HAPServer [CC:22:3D:E3:CE:30] Adding pairing info for client +1ms
    Accessory [Homebridge] Paired with client ........-....-....-............ +0ms

Twice...and now both my iPhone and iPad have the bridged devices shown. So iCloud sync is working, but the AppleTV doesn't seem to be generating a pairing request, as near as I can see.

> it shouldn't matter how you add your device to trust circle. ... the updated keychain db which HomeKit relies to decrypt home information.

Exactly, here's my point: I've never turned on the option in iOS Settings > iCloud > Keychain > Advanced > "Approve with Security Code", which lets you add devices with a PIN/password. It sounds like you have. And critically, I have never been prompted to approve my AppleTV...either after setting it up out of the box or after signing out and back into iCloud, which I have done at least twice now. So, how is the AppleTV supposed to access my Keychain DB?

For those who have enabled "Approve with Security Code", do you get prompted for an iCloud keychain PIN when you sign your ATV3 into iCloud? Has anyone who has not enabled it ever been prompted on another device to approve the AppleTV for keychain access?? It seems one of these two things should happen if the AppleTV is a HomeKit participant.

**Comment by KhaosT** [comment]
@SphtKr just to confirm, you didn't share the newly created home with anyone else right? If that's the case, the add pairing request we saw should be the one for Apple TV.

If possible, can you connect your Apple TV to your computer and see what's the console output on the Apple TV side? If iOS tried to add pairing info for Apple TV, that means iOS is at least trying to setup Remote Access. It would be helpful to know why it failed on the Apple TV side.

**Comment by SphtKr** [comment]
@KhaosT Well I'll be danged...you're right. I just got around to trying it, I turned off my iPhone's WiFi, and I can in fact control devices over cellular network. Woo hoo!

Still, makes me marvel...or worry...how can the AppleTV pair with the bridge, if I haven't authorized it to access my keychain...?? It almost must not authorize itself to the bridge (device) at all, just pass through the iOS device's authentication...or something??

**Comment by KhaosT** [comment]
@SphtKr Great to know you finally gets it to work.

The current Remote Access model using Apple TV involves lots of workarounds... Due to the lack of CloudKit, Keychain Sync support on Apple TV (iOS 8), when setting up Remote Access, Apple TV actually generates a local key pair, send it to iOS via IDS and iOS device will add Apple TV as a special shared user to HomeKit Accessory. (So Apple TV wasn't actually joining your iCloud Keychain trust circle)

**Comment by fitzage** [comment]
I still can't get this working. Does anybody know if it has issues if you have your Apple TV logged into one iCloud account and a different store account?

**Comment by iRaven** [comment]
Someone having Unitymedia as ISP? All my VPN Solutions got broke with ios9/el capitan (ECN flag set by isp), i wonder if icloud is also affected by this.

**Comment by webdeck** [comment]
I'm having this problem, too.  I tried logging out of iCloud on the Apple TV, rebooting it, and then logging back in.  I didn't see any requests hit Homebridge during all of those steps.  How do I access the console logs on the Apple TV?  It's a v3, running the latest version, and not jailbroken.

I have an iCloud account that dates back to the me.com days.  However, I log in everywhere with the icloud.com address, not the me.com one.  Could that be the issue?

**Comment by KhaosT** [comment]
@webdeck there is a known issue that Remote Access won't work if you signed in with anything other than your primary account on Apple TV (although for someone signing into @icloud.com on all devices worked for them)... I'd suggest you to try signing in with your @me.com account on both iOS device and Apple TV and see if what works.

**Comment by jmvanbuskirk** [comment]
@ttgolf I'm having the issue where I can't get Homebridge to work remotely. What accessory did you ad to setup? By setup I assume you mean package.json? Any help would be appreciated. 

Thanks,

Josh

**Comment by webdeck** [comment]
@KhaosT I signed everything out of my icloud.com address and signed everything back in with the me.com address instead (what a pain that it deletes all your Apple Pay cards.)  Then I followed your previous steps:

1. reset the HomeKit Configuratio
2. signed out the iCloud account from Apple TV
3. stopped homebridge
4. deleted persist files
5. rebooted Apple TV
6. signed into iCloud on Apple TV
7. waited 5 mins
8. created a home on iOS device
9. waited 5 mins
10. started the bridge with all hap-nodejs debug info
11. paired with the accessory

Here is what I see:

iPhone does 3 /pair-setup requests and 2 /pair-verify requests
iPad (which was sitting there sleeping) does 2 /pair-verify requests
AppleTV sends no requests

I've let it sit there for 15 mins now and AppleTV still does nothing.

Thanks for any help!
-Mike

**Comment by webdeck** [comment]
PS - and the iPad hasn't gotten past step 1/2 of pair verify, so it shows everything as unreachable, even though it is on the same WiFi as the phone.

**Comment by KhaosT** [comment]
@webdeck and you never see ``HAP Request: POST /pairings`` on the Homebridge side? If so then iOS device may experiencing issue discovering Apple TV...

**Comment by webdeck** [comment]
I did see it call /pairings when I did the first step of resetting the HomeKit configuration.  It never called it again after that from what I could tell.

**Comment by KhaosT** [comment]
@webdeck if you really wants to figure out why Remote Access is not working, you can connect Apple TV to your computer and open Xcode -> Devices -> Apple TV to see logs from Apple TV...

**Comment by webdeck** [comment]
@KhaosT I've tried that, but it only shows me crash logs - I couldn't find anything interesting in there.  Is there some trick to see more log files?

**Comment by KhaosT** [comment]
@webdeck not really, try to search "homed" and/or "accountsd", there should have a few lines related to why remote access failed...

**Comment by webdeck** [comment]
@KhaosT Maybe I'm doing it wrong. How do I see the log files?

**Comment by webdeck** [comment]
@KhaosT duh, I was doing it wrong - didn't see the triangle to open at the bottom to see the console log.  Okay, I have a console log with what looks like errors.  Could you send a sanitized version of what a working ATV log looks like so that I can determine which of these errors are real?

Here's what I see for lines with accountd or homed or AppleIDAuth (I replaced my iCloud e-mail address with <<<MY-ICLOUD-EMAIL>>> and <<<REDACTED>>> other identifiers):

Oct 25 21:41:00 Apple-TV accountsd[82] <Warning>: [Warning] Services all disappeared, removing all dependent devices
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [handles]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [email-address]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [auth-token]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [self-handle]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [invitation-context]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [realm-user-id]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Unhandled server key: alert
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] No auth-token for serviceType = com.apple.account.IdentityServices
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [handles]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [email-address]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [auth-token]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [self-handle]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [invitation-context]
Oct 25 21:44:43 Apple-TV accountsd[82] <Warning>: [Warning] Missing keys in the authentication dictionary service keys.  Please file! [realm-user-id]
Oct 25 21:44:44 Apple-TV accountsd[82] <Warning>: NSScanner: nil string argument
Oct 25 21:44:44 Apple-TV accountsd[82] <Warning>: Account not provisioned
Oct 25 21:44:47 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:47 Apple-TV AppleIDAuthAgent[41] <Error>: SERVER Password not in keychain; adding it. (__addPasswordToKeychain_block_invoke()/AppleIDKeychainItems.cpp #1027) KeychainDispatchQueue
Oct 25 21:44:47 Apple-TV homed[103] <Error>: Unable to read encrypted metadata - Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn\U2019t be completed. (NSCocoaErrorDomain error 260.)" UserInfo=0x17d176a0 {NSFilePath=/var/mobile/Library/homed/protected-metadata.config, NSUnderlyingError=0x17d12f10 "The operation couldn\U2019t be completed. No such file or directory"}
Oct 25 21:44:47 Apple-TV homed[103] <Warning>: No archived metadata
Oct 25 21:44:48 Apple-TV accountsd[82] <Error>:  SOSCCSetUserCredentials SOSCCSetUserCredentials!! <<<MY-ICLOUD-EMAIL>>>
Oct 25 21:44:48 Apple-TV homed[103] <Warning>: Starting with built-in metadata version 101
Oct 25 21:44:49 Apple-TV homed[103] <Warning>: No archived home config data
Oct 25 21:44:49 Apple-TV homed[103] <Warning>: Empty results for asset update query
Oct 25 21:44:50 Apple-TV securityd[66] <Error>:  securityd_xpc_dictionary_handler accountsd[82] SetUserCredentials The operation couldn\U2019t be completed. (SyncedDefaults error 1025 - Remote error : No valid account for KVS)
Oct 25 21:44:50 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:50 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:50 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:50 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:51 Apple-TV AppleIDAuthAgent[41] <Notice>: SERVER AppleIDAuth: Adding account "<<<MY-ICLOUD-EMAIL>>>" succeeded.[ NULL ]  (__AppleIDDoAddAppleID()/AppleIDAuthenticationImpl.cpp #298) client 82
Oct 25 21:44:51 Apple-TV AppleIDAuthAgent[41] <Notice>: SERVER AppleIDAuth: Creating CSR for "<<<MY-ICLOUD-EMAIL>>>". (__AppleIDDoCreateCertificateRequestForAppleID()/AppleIDAuthenticationImpl.cpp #657) accountCheckDispatch
Oct 25 21:44:52 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:53 Apple-TV accountsd[82] <Warning>: AIDA Notification plugin running
Oct 25 21:44:57 Apple-TV AppleIDAuthAgent[41] <Notice>: SERVER AppleIDAuth: CSR sent to Apple ID server for account "<<<MY-ICLOUD-EMAIL>>>", certificateToken=, certToken="<<<REDACTED>>>", delay=300. (__AppleIDDoCreateCertificateRequestForAppleID()/AppleIDAuthenticationImpl.cpp #726) accountCheckDispatch

**Comment by KhaosT** [comment]
@webdeck is this from console after login into iCloud or after pair with Homebridge? If possible, can you grab the logs from Apple TV from iCloud login to Homebridge setup and wait for a few minutes..

**Comment by justme-1968** [comment]
i now have a used apple tv to play with and after some trying the remote access works. sort off...
in the homebridge log i can see that the request for current values are coming in at a rate of 1 every 4 seconds. which is much to slow i think eve always shows last access x minutes ago. switching works from time to time but using siri to ask for something always times out.

any idea how to find out more ?

**Comment by KhaosT** [comment]
Before iOS 9.2, HomeKit will not try to combine read/write requests from app so every single request will be queued up and waiting for Apple TV to process… the message exchange process between Apple TV and iOS is really slow so sometime Siri request will timeout due to the queued requests from the app.

iOS 9.2 finally fixed this and your problem should be resolved with that release.

**Comment by justme-1968** [comment]
sounds great! i will try the 9.2beat. thanks.

**Comment by luxus** [comment]
Hey, i got The new Apple TV 4. Gen and can confirm that remote access is working, even my girlfriend can access via LTE (I shared her my HomeKit home)

**Comment by fitzage** [comment]
Works for me with the Apple TV 4 as well. At first I thought it didn't, but that's because I'm having a crashing issue in homebridge and it wasn't active at the moment.

**Comment by webdeck** [comment]
Apple TV 4 solved it for me as well.  Thanks again @KhaosT for all your help!

**Comment by KhaosT** [comment]
There are improvements not directly related to HomeKit in tvOS 9.0 which fixes HomeKit Remote Access Setup :) Glad to know it's working.

**Comment by Brice-Cassagnabere-Work** [comment]
Hi all.
I just installed Homebridge few days ago and everything is working fine with my Fibaro HC2 using dedicated plugin.
Now, I am trying to have it working over cellular but it does not.
I have an Apple TV 4 on my Network configured with my iCloud account.
Is there something specific to do to make it work ?
Maybe a dedicated plugin to install on homebridge to link it to my iCloud account ?
Thanks for your help !

**Comment by Gazous** [comment]
Hi all.
I just installed Homebridge few days ago and everything is working fine with my Fibaro HC2 using dedicated plugin.
Now, I am trying to have it working over cellular but it does not.
I have an Apple TV 4 on my Network configured with my iCloud account.
Is there something specific to do to make it work ?
Maybe a dedicated plugin to install on homebridge to link it to my iCloud account ?
Thanks for your help !

**Comment by benbeton** [comment]
since iOS 9, remote access should work without the need of a ATV, is this a limitation of homebridge?! 
Can anyone confirm, ATV3 is working as "HomeKit Gateway"

Would be great to have a solution without ATV

**Comment by fitzage** [comment]
The latest Apple TV is working for me, but the previous which was a third generation did not.

**Comment by Gazous** [comment]
Hello, i have tried everything to get remote Homekit working but.
When I try over cellular, Siri says, "Sorry i did not receive a response from system"
iCloud account loged out and in on the ATV4.
Remote HomeKit access disabled and enabled on the iPhone.
Am I doing something wrong ? Is there something to configure in Homebridge ???
Thannks for your reply.

**Comment by KhaosT** [comment]
@Gazous there is nothing you need to do from homebridge side. When toggle Remote Access settings on iOS, please make sure you're in local WiFi and all accessories in your HomeKit database is reachable. Sometime it may takes a few minutes for HomeKit to finish setting up the Remote Access (since the communication is slow) but with ATV 4 + tvOS 9.0, it should be setup fine...

**Comment by Gazous** [comment]
Thanks Khaos for your reply.
I have tried several times and it does not work.
Also update to iOS9.2 and TVOS9.1 and same behavior...

**Comment by deejc-uk** [comment]
i also thought it didn't work, so i logged out of ATV, logged out of icloud on iPhone, Logged back in on ATV, back in on iPhone and tried... it can take a LOOOONG time to get anything back in the app you are using, I am using HOME and it can sometimes take a minute or 2 to update the device states.

**Comment by luxus** [comment]
I switched back to a Apple TV3.. I got it for 30€
I don't really have use for the newer appletv at the moment
Now I can't get the remote access working.. It worked with the appletv 4
I changed iPhone and Apple TV to my primary ID (@mac.com)
I tested to logout reboot and login after restart of the appletv.. But yet I can't get it working.
For what should I search when I hook up the appletv with my Mac and what should I do? Re-login? Disable and enable the remote access?

**Comment by KhaosT** [comment]
You can try disable and re-enable the remote access on iOS. Sometime that will solve the issue but given it worked with ATV 4, there might be something wrong with your Apple ID that ATV3 failed to register IDS for communication with iOS. In that situation, I'm afraid there is no reliable way to fix.

**Comment by n8henrie** [comment]
Just wanted that after messing around all morning I finally got remote access working with homebridge and my aTV3.

What did *not* seem to work (alone or in various combinations):

- Signing in and out of iCloud on various devices
- Numerous reboots on various devices
- Removing and re-adding homebridge to HomeKit
- Removing  old HomeKit preferences from the `Privacy` section in iOS Settings
- Ensuring remote access was enabled in HomeKit preferences

The additional steps I required:

- Disabling Apple 2-factor authentication
- On Apple TV, not only signing out of iCloud but also signing out of iTunes Store

Once I did the second set of steps, I was able to go back to the first set of steps (a few more reboots, etc.) and in short order saw the `/pairings` come up in debug output and remote access started working in no time. After I verified it was working, I was able to re-enable 2-factor authentication without trouble and remote access continues to function as expected.

**Comment by A5HRAJ** [comment]
When I'm on cellular, the HMCatalog app works but Siri doesn't ("Sorry, I wasn't able to do that.") Does anyone else have partial remote access?

**Comment by omarshahine** [comment]
I had some serious challenges getting Remote Access to work with Apple TV 4. Based on this thread I was suspicious of the keychain, the chillies heel of iOS and Mac. So I went looking in my iCloud Keychain for home kit related entries and found one.

> HomeKit Pairing Identity
> Identity used to pair with HomeKit accessories.

<img width="646" alt="homekit pairing identity" src="https://cloud.githubusercontent.com/assets/10343873/13765561/bbb22182-ea17-11e5-9b0e-ab6bcd2b1dbb.png">

Deleted this key, ensured it propagated to my other Macs, Reset HomeKit Configuration, Restarted Apple TV and added a single HomeKit device. Remote Access worked!

**Comment by sashahilton00** [comment]
Hi guys, do we know what exactly is stopping this project from implementing a homebridge based gateway for remote access? I saw earlier that the MFi chip is obviously a limitation, but do we understand the MFi challenge-response for Homekit to the point that it can be reimplemented here? The reason I ask is because I've attached a copy of Apple's airtunesd reciever source code, and all the documentation for the source and the MFi chipset, which from a brief look and some research into the technicalities of Homekit looks pretty similar, though I have not looked at the Homekit protocol in enough detail to give a definite answer. Anyway, here is a link to the source and the documentation,  the interesting stuff is under the Technical Specifications folder. Also, if necessary, it isn't too difficult to get one's hands on some MFi chips... https://www.dropbox.com/sh/y8rghzutjyezsar/AAD5btv-e677dA9wA6Db3m6ba?dl=0

**Comment by KhaosT** [comment]
@sashahilton00 Thanks for sharing those specs, to avoid the whole project from being take down by Apple's DMCA request, I removed the link from your post… The primary problem for this project to implement HAP over iCloud is legal related, right now the only way to get the HAP over iCloud's spec is through Apple's MFi program and there are extra NDA related to that specific spec so without violating the NDA, it's not possible to include an implementation publicly in homebridge. (This situation might change after some accessories that support iCloud Remote Access hit the market) Second problem is the MFi chip, so far I haven't find a way to get MFi chip from any other channel other than Apple's appointed distributor, so even if we were able to ship the implementation, it's hard for normal user to actually use it. And the third thing is, if there is already an Apple TV in your iCloud account, HomeKit will not try to setup HAP over iCloud with the accessory.

**Comment by sashahilton00** [comment]
@KhaosT apologies for the link, should've masked it, I leave that one up to you to re-add if/when you feel it is necessary. I do have a way to acquire MFi chips cheaply that isn't through Apple, though point taken regarding the ease of access. I may one day make some MFi shield with headers to make it a bit more accessible to the public, but we'll see... Regarding HAP over iCloud, I'm sure there will be a leaked reference soon enough, or someone will make sudden headway on reversing it.

**Comment by KhaosT** [comment]
@sashahilton00 that specific spec (HAP over iCloud) is only distributed to chip manufacturers and without seeing an actual product, there is nothing to reverse engineering the protocol since iOS side doesn't contain the "talk to iCloud" part for accessory 😅

**Comment by sashahilton00** [comment]
The ATV 3/4 are HAP over iCloud products right? I know the ATv 3 is unbreakable, but I thought there was some headway on jailbreaking the ATv 4? Anyway,  cheers for clarifying, will wait and see :)

**Comment by KhaosT** [comment]
ATV uses a different way to do remote access.

**Comment by ebalsumgo** [comment]
Hmmm so I have two ATVs one 3 and one 4, both running latest. I am logged into the same icloud account across all devices, but no matter what I seem to not be able to get remote access. I have toggled remote access on/off. I have not tried logging out of all the devices and logging back in, but that doesnt seem to be a needed step based on what I am reading. homebridge is the only "home" i have in the system... any suggestions?

**Comment by ebalsumgo** [comment]
NM.... now i am looking like a fool. I set remote access on/off a couple of times and it finally worked... ignore above comment :)

**Comment by apwelsh** [comment]
I haven't been able to get it working with Apple TV 3. I dont see a remote access sstting nor anything tondo with homekit.  Do your ATV 3 and 4 have different iCloud features?  I know the early reports stated you needed a 3 or 4, but i assume they deprecated that ability in the latest software that i am running now.

**Comment by derekhardwick** [comment]
@ebalsumgo what 'remote access' toggle are you talking about?  On the appleTV?  in homebridge config.json?

**Comment by toshibochan** [comment]
If you have appletv 3 and above in same iCloud account with the HomeKit in your iPhone you can control from outside of your home wifi.

**Comment by toshibochan** [comment]
For remote access: 
login on Apple TV and iPhone with same iCloud account.
Add you home and accessories on iPhone with the app.
Go to settings-HomeKit-home(select you home)-allow remote access(ON).
All this have to be done in the same wifi network and sane iCloud account.

**Comment by derekhardwick** [comment]
Thanks @toshibochan, didn't know about that.  Sadly it wasn't the source of my problem.

I still couldn't get my ATV v3 setup to allow remote access tohomebridge.  I thought it was 2FA, keychain PIN, this setting, and have signed in/out of iCloud on the ATV (and rebooted it between steps) added/removed the accessory on my iPhone numerous times, but it didn't love me.  I see the device in Bounjour so I can't really imagine why the ATV doesn't pick it up.  I had stopped just before digging into the ATV logs with my developer account.  Oh how i love little black boxes.

But today, new iOS version! New Apple Home app!  New chances! 

The new app says you can make your ATV v4 (or a spare iPad) your 'home hub', with no mention of how the ATV v3 fits into any of this. I was hoping that the ATV v3 will at least try to sync homekit.  Thankfully, it does!

Steps:

- Upgraded my phone to iOS 10, deleted the homebridge accessory, deleted the EVE app.
- Signed out of iCloud and the Apple Store on my ATV v3.
- Rebooted ATV
- Signed into iCloud and the Apple Store on the ATV
- Opened Apple's new Home app, added my homebridge accessory.
- Got a wonderful message after setup underneath the title of my home.  Something like "Trouble connecting to Apple TV".  I say wonderful because at least there's something!
- Message disappeared after 1-2 seconds.  That's promising.
- Tried out some light controls, they work fine.
- Switched off wireless, and yes, I can control my lights over the 4G connection (with some delay).
- Siri also appears to work fine remotely with this setup, as does controlling devices via control center.

Hopefully this update and tiny error message will help other homebridge / ATV v3 users get things working (or at least have some clue of why it's not).
