### ISSUE TITLE
Yamaha- no Audio functions-

### ISSUE THREAD

**Issue by neonightmare** [nfarina/homebridge#265]
Hi, got the platform Yamaha now active on HomeKit/Homebridge, but the Audio functions are not available. I can only set the State on/off of the AVR.
log from home bridge-start:
```
[undefined] Found Yamaha RX-V2067 - 0BF249F3, "Yamaha"
[undefined] Waited 30 seconds, stopping discovery.
[undefined] Discovery finished, found 1 Yamaha AVR devices.
[undefined] Initializing platform accessory 'Yamaha'...
```

is this normal?

thx neo

**Comment by SphtKr** [comment]
Yeah...So, here's the situation: HomeKit doesn't directly support anything like input switching, DSP modes, setting FM station, even Volume--it does not have standardized "Characteristics" for those things. So, there's not a good way to expose those settings to HomeKit in a way that the various iOS apps that act as HomeKit controls (including Siri) will know how to work with them.

That said, you can create custom Characteristics in HomeKit. In fact, I added one in a recent update to the YamahaAVR platform, for controlling the volume. In theory, this should be possible for a HomeKit iOS app (potentially even Siri) to make sense of and use--because in this case, it's simply a Percentage value between 0% and 100%, exactly the same as Brightness. Unfortunately, it didn't seem to work. MyTouchHome shows the existence of the Characteristic, but won't show its value or let you modify it. HomeRoot is the only other one I've seen that even recognizes it, but if I try to edit the value then HomeRoot crashes :-/. So, it doesn't work as nicely as I hoped.

It's worse for things like input switching, because there's not a way (that I know of) to communicate the list of possible values to the HomeKit app...so it wouldn't know what options to show in a menu, for instance. Again, in theory, I could make a Characteristic that just had a number value, and let you assign inputs to numbers. It's clumsy, but usable. But, I think right now it wouldn't work any better than the volume...the apps probably wouldn't let you set the number successfully.

So, what to do? Maybe, some apps will update to make sense of my custom percentage Characteristic--that would be awesome. Or, I could also make the volume value show up like a dimmer...apps and Siri would think you were adjusting a bulb brightness, but it would really change the volume. That sounds like it would work, but I haven't tried it yet. I could do something stranger with FM station like make it a thermostat temperature or something...that might get weird.

That's the explanation. I want to do what you're describing but it's tricky. What kinds of audio functions would you most want to be implemented? One other question, which app(s) are you using right now?

**Comment by SphtKr** [comment]
Oooh...minor update: it seems that the Eve app lets me set the custom volume characteristic now! Sweet! I'll have to try adding the "muting" characteristic I was half-done implementing and see if that works.

**Comment by SphtKr** [comment]
Erm....So does HomeRoot...or at least it doesn't crash. Hmm. I wonder if there was a bug fix in iOS 9.0.2...??

**Comment by neonightmare** [comment]
THX for the work! For me at the moment I don't need more... I am trying first the bridge between my Wago-Controller and KNX-Homebridge...

**Comment by neonightmare** [comment]
@SphtKr: Is there a possibility to pack the AVR in the new Plugin-Structure? Can I help, maybe?
