### ISSUE TITLE
"telldus" dependencies not building

### ISSUE THREAD

**Issue by nfarina** [nfarina/homebridge#277]
I've had to temporarily remove "telldus" references from package.json as it is breaking "npm install" on Node v4.

@johngson, @theodorton: Any ideas on how to get these to build again?

**Comment by johngson** [comment]
Hi!

I introduced the platform called "Telldus Live!" that depends on "telldus-live": "0.2.x". What I can see is that it should work fine with this dependency. Could you please add it and try it yourself @nfarina? If it doesn't work please notify me otherwise add it to the project again.

Currently I cannot speak of "telldus": "0.0.9" since I've never worked with it. I'll look into it as soon as I've got time but i guess @theodorton can answer this best.

**Comment by nfarina** [comment]
Thanks @johngson, you're correct, `telldus-live` works fine - I've restored it.
