### ISSUE TITLE
Simple solution for installing dependencies on-demand?

### ISSUE THREAD

**Issue by nfarina** [nfarina/homebridge#278]
@cflurin, @snowdd1, @SphtKr: I'd like to resurrect some of the discussion from #187 and find a solution we can implement quickly for dealing with our growing "dependency problem".

Right now of course it's silly to put all possible accessory/platform dependencies in the main `package.json` file - it was a great way to get moving quickly on supporting lots of accessories and bringing in contributions, but it doesn't scale.

My "long term" solution has a lot of work ahead of it, and unfortunately these days my "hobby time" is very limited.

I think we should be able to come up with something simple for dealing with this in master though. Reducing deps in the main `package.json` to the bare minimum is step one. I'm fine having the user install more deps in `node_modules` as needed, or doing it for them. Perhaps we can auto-detect dependencies by doing a simple source code scan for `require()` calls so we don't crash and instead suggest to the user that they need to install them. Or, we can come up with a simple format for "declaring" dependencies and versions at the top of the file in a comment?

Any other ideas?

**Comment by SphtKr** [comment]
Hmm... so is there a problem with making all the platforms their own npm modules? I really don't know because I'm still quite new to node (not to Javascript, but still). I assumed the "right" answer will be something like

    npm install git+https://github.com/nfarina/homebridge/platform/YamahaAVR

Or something. Beyond that I'm not sure I'm too qualified to have an opinion, but I'll try...

Auto-detecting/source code scanning seems like a nightmare, and error prone. I'd recommend against that.

As a quick fix, would it make sense for each platform to provide a script to install its needed modules? A `bash` script would probably be Mac/Linux specific solution and cause problems for anyone trying Windows. I am surprised I don't see (after some quick Google searching) a `npm` module--one that would let you install `npm` modules from a node script. That is, this would be ideal:

    node run platforms/YamahaAVR-setup.js

or

    node run setup/YamahaAVR.js

And that would run a node script that would install the modules needed. We just require that any modules that have their own dependencies include a setup script.

Is this possible? It's very hard to Google "npm node module", obviously. [This question](http://stackoverflow.com/questions/14548220/how-to-install-npm-package-from-nodejs-script) suggests a way, but it's still *nix shell-script specific, and doesn't translate well to Windows.

**Comment by cflurin** [comment]
Several users have used this [guide](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi) but obviously it'd be easier to install Homebridge without any platform dependencies. I'll come back as soon I have an idea.

**Comment by snowdd1** [comment]
Looking at #187 I found I described my solution approach incorrectly.

My idea was to [install](https://github.com/snowdd1/homebridge/blob/dynamic-platform/app.js#L128) packages **not** based on homebridge's package.json (which I wrote) but based [on config.json]() (which I meant). *I have to admit that, for a discussion branch, it is insufficiently commented.*

Prerequisites:
-  npm packages for all platforms and accessories (that shouldn't be too much work, even if not all owners want to host their own, we can possibly find enough buddies to host that)
-  npmi as run-time installer (I tested that in my dynamic-platform branch successfully)

Alternative that I see:
- We put the dependencies for each accessory/platform in an *extra file*, as a separated ersatz package.json for non-npm-packages, and upon encountering those in config.json we do a npmi.install for those packages. That's easy to implement (and thus stable I think);  And runs fast if they are installed in the right version.

I would definitely **not** go for the code scanning. The debugging effort occurs to me higher than the extra work for maintaining the extra file. And if it doesn't work you know where to look, and do not have to ask *why did it not run this time*

Also using node as scripting engine is possible, npm **is** a node package (@SphtKr), and is used by the wrapper npmi.

**Comment by SphtKr** [comment]
There you are, npmi is what I was looking for but couldn't find on Google. I think I like that approach. Again, I'm new to Node and npm...would you like me to try to make separate npm packages for YamahaAVR and ZWayServer to try this out? Would that make sense?
