### ISSUE TITLE
Netatmo Platform with man attached modules

### ISSUE THREAD

**Issue by patricks** [nfarina/homebridge#326]
Hi,

I saw, that you added the netatmo platform. This is really nice, but I have a problem, that some modules have the same name, but they are physically attached to another station. So I wrote a PR #325 to fix this problem. But it would be nicer to add the station name to every module. This could be easily fixed by using my netatmo node.js module from: https://github.com/patricks/netatmo
I have added the new, not deprecated getstationdata api call (https://dev.netatmo.com/doc/methods/getstationsdata) to the module.

What's you opinion? Should I add a separate PR for this fix?

**Comment by planetk** [comment]
HI Patrick,

thanks for your contribution. Since I only own one modul and one device I was not aware of this issue ...

I've been using the devicelist methoe instead of getstationsdata mainly for three reasons:
1.) lazyness
2.) even more lazyness ;-)
and 
3.) I thought this could be the more generic approach for any kind of netatmo device.

But I totally agree that using getstationsdata would be preferable.

BTW: Do you use the elgato eve client? I would be very interested in using the time series display,
which is according to screenshots provided available... and support for battery level would be great as well.... and of course a better error handling... ;-)

**Comment by patricks** [comment]
Hi planetk,

I habe submitted a new PR #335, where i have implemented the net getstationsdata() api call. 😄

Now the station name is written to every module name, so we avoid duplicate accessory names.

No I use the Home.app (http://selfcoded.com/home/), but if I find some time in the next days, I'll also try this one. Time series display would be really nice. 😉
