### ISSUE TITLE
Accessory timeout?

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#340]
Hey, 

I am making a new Accessory for my Marantz/Denon Receiver and it's growing quite well. The only thing I noticed is, that I can only send commands every so many seconds. Annoying since volume should be quite fast.

Any ideas? Or is it just the Service.Switch() that is so slow?

**Comment by justme-1968** [comment]
try to look where the delay really comes from. from the homekit side or from the connection to the receiver.

for the volume control in the fhem shim i have added a delay so that the value is only sent if the user has stopped changing it in the homekit app. if i send to fast to the sonos system there are some feedback problems.

**Comment by luc-ass** [comment]
Thanks. The delay occurs even if I have no script attached. If I simply log out "Power state changed to true/false" it takes about a minute before I can change it again...

**Comment by justme-1968** [comment]
it should be immediate.

do you call the callback from the set event?

**Comment by luc-ass** [comment]
You were right. I forgot to properly callback()... Clumsy me ;)
