### ISSUE TITLE
Homebridge as a Service on RPi - Needs Reset every 8 hours

### ISSUE THREAD

**Issue by ericvogel84** [nfarina/homebridge#365]
I am running Homebridge as a service on my Raspberry Pi and it works great.... util I stop using it. Every time I leave the house or go to bed, whenever I come back and try to use it the service has stopped. 

There is no sleep function enabled and I cannot find anything in the logs that would give me a clue. Anyone else have any ideas?

**Comment by nfarina** [comment]
Is the homebridge program still running on your RPi but not accepting your commands? Or has it crashed? Can you run with `DEBUG=* node app.js` and see if the logs print out anything interesting once it stops working?

I do have a raspberry pi 2 myself and homebridge has been running for weeks without issue, so it should be possible.

**Comment by vogelboy** [comment]
Ok so I managed to get the .err log (I have been running with DEBUG=* the whole time, just didn't realize there were two of them!) and there are multiple quits of the script after this error. Seems I'm having a nest issue? I'm going to try removing the nest bit from my config.json and see if that helps. 

Mon, 02 Nov 2015 04:20:44 GMT EventedHTTPServer [::ffff:192.168.29.156] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND czfe88-front01-iad01.transport.home.nest.com czfe88-front01-iad01.transport.home.nest.com:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN home.nest.com:443
    at Object.exports._errnoException (util.js:874:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by nfarina** [comment]
This looks like a network/DNS problem. After this happens can you cURL https://home.nest.com? Also is your home network setup unusual at all?

**Comment by askme233** [comment]
I have been having the same error and trying to isolate it.  

I have found that my Homebridge server is initially advertising over Bonjour on two different local IP addresses (server is dual NIC) and then one of the IP address advertisements drops off after a bit.  I also noted the pseudo-HTTP keepalive logic HAPServer.  Any ideas on if that could cause a problem?

[Vogelboy stated "(I have been running with DEBUG=* the whole time, just didn't realize there were two of them!) "  and I have  been looking all over for another error log or place to set DEBUG but can't seem to figure out how he found a second log.  VOgelboy, what did you find?]

**Comment by nfarina** [comment]
The pseudo-http keepalive stuff shouldn't cause iOS to become unresponsive - this is just a "bonus" mechanism for keeping iOS connections alive on the Node side (iOS HomeKit supports extremely long-lived connections without any traffic but Node has a problem with this). However if the connection is dropped, iOS should always reconnect automatically.

**Comment by askme233** [comment]
OK, thanks I will continue my search for the drop.

**Comment by vogelboy** [comment]
nfarina- How would I go about doing the cURL (im sort of a novice when it comes to this!)? 

My home network setup is not strange at all - Cable modem connected to router- router ethernet to RPi. I could see the network having hiccups to cause the DNS error as Mediacom has been horribly unreliable since I moved here, but home.nest.com is always reachable whenever I try. 

The issue seems to be that the nest API becomes unreachable and then homebridge is bailing...

**Comment by cali0028** [comment]
seem like I have this same fever. Can't seem to figure out what the problem is and good thing to see that I'm not the only one having this problem.

**Comment by askme233** [comment]
Not sure why your debug isn't working. I am on Windows and finally realized I need to set the DEBUG env variable rather than the command line option. You might be able to do the same. 

I had thought my issue was a network issue as nfarina had suggested related to my dual NIC (eg Bonjour advertising in both and iOS binding to the wrong one). After disabling the second NIC the problem persists.  

Debug console output shows a series of keepalives and then an error on ECONNRESET that closes the connection 

I haven't found the Windows equivalent of the error log vogelboy mentioned.

**Comment by askme233** [comment]
Well, I went back to my Linux VM version and rebuilt from the latest versions and all is well, I no longer seem to lose connection.  Not sure if the issue had to do with my sketchy Windows build or a fix that was made since i last built. I will next rebuild the Windows version (pita) and see if that solves it as well.

**Comment by cali0028** [comment]
@tex4ever the issue you are reference to brings it back to this conversation thread. 

@askme233 maybe I need to do the same. Let me start from fresh again and see if I still have this problem. I'll report back.

**Comment by dannystdu** [comment]
This issue seems not only related to RPi, I am running homebridge on Vagrant VM,
homebridge will stop working after period of time , to get it work again I'll need to delete
files locate in /persist path and re-pairing homebridge to IOS again, It's seems somehow
avahi-deamon and bonjour broadcast not working any more due to 
AccessoryInfo and IdentifierCache data was changed.

**Comment by aebgit** [comment]
Hi all,

merry christmas to all of you and many thanks to nfarina for that great project!

I had similar problems on my raspberry. 
After disabling power-save for the WiFi-adapter homebridge runs absolutely stable.

I currently cannot check my personal configuration, but here is described what do do: https://www.raspberrypi.org/forums/viewtopic.php?t=51543&p=397663

It is possible to set the 8192cu power management parameter to off by generating the 8192cu.conf file with command sudo nano /etc/modprobe.d/8192cu.conf and adding the lines
# Disable power management
options 8192cu rtw_power_mgnt=0

Viele Grüße,
Andreas

**Comment by chrislongden** [comment]
I was having an issue when after something like 2 hours the Pi would stop responding, either through homekit or even just attempting to ssh using putty.

I did as aebgit suggested, changing the wifi power management to off and since then, around 6 hours, everything is still up and running with no issues.

**Comment by ssub9673** [comment]
Ive connected the RPi using ethernet and i still have this issue. @chrislongden @aebgit . Any suggestions? Thanks again for the help.

**Comment by chrislongden** [comment]
Maybe this?? I just attempted the wifi fix and all seems good. Maybe
Ethernet is sleeping too?!

http://raspberrypihell.blogspot.co.uk/2013/10/stop-raspberry-pi-going-to-sleep.html?m=1

**Comment by dr-ito** [comment]
I read somewhere on GitHub, Homekit blocks a device if it receives invalid messages from it. Perhaps  malformed messages are causing this problem here?

**Comment by chrislongden** [comment]
Mine is only setup with the wemo plugin controlling 4 switches for
reference.

**Comment by ssub9673** [comment]
@chrislongden  thanks for the help.ill try the link that you sent. I'm getting the same error that @vogelboy is getting...

Error: getaddrinfo ENOTFOUND czfe88-front01-iad01.transport.home.nest.com czfe88-front01-iad01.transport.home.nest.com:443

**Comment by ssub9673** [comment]
Still the same issue :( looks like its specific to RPi.

Error: getaddrinfo ENOTFOUND czfe88-front01-iad01.transport.home.nest.com czfe88-front01-iad01.transport.home.nest.com:443

**Comment by chrislongden** [comment]
For reference mines the A+ modal.

**Comment by ssub9673** [comment]
Hmm. Mine is the Pi 2 Model B

**Comment by IMNotMax** [comment]
Hi, I have a RPi 2 B with Jessie, homebridge is running as a daemon for the Pi user (using systemd not unit.d) and it works like a charm. 
I was on OS X 10.7.5 and had some crashes. On the RPi it's perfect. 
My RPi runs also motion for motion detection with a webcam and it's still powerful enough to run other daemons :)
I'll post my detailed config ASAP if it helps.

**Comment by ssub9673** [comment]
@IMNotMax Yes. Please post the config whenever you get a chance. Thanks. 
I was thinking this had something to do specifically with nest. since the log said that. but I could be wrong. Thanks again for the help.

**Comment by IMNotMax** [comment]
See my comment here : https://github.com/nfarina/homebridge/issues/385#issuecomment-167344506
You'll find my setup.

And in this thread, you will find details on how I install my RPi and what I did.
Hope this will help.

**Comment by kenthua** [comment]
I seem to be experiencing this particular issue as well on my rpi 2.  It's connected via ethernet.  I am using the IOS app eve and my devices just don't refresh anymore, it works for a few hours.   "Updated this week".  I have DEBUG=* enabled.  I've tried restarting homebridge and it just stops working.  I can only get it back if I delete all the config on HomeKit as well as the homebridge persisted folder.  

http://pastebin.com/RNGB1jxt

**Comment by ssub9673** [comment]
@kenthua I tried couple of things with no luck. The only way i could reliably make nest on homebridge work is by scheduling a restart every morning :( . Works flawlessly now, but not an ideal solution

**Comment by kenthua** [comment]
@ssub9673 thanks for the suggestion.  I have it restarting every day as well, a little more stable.  However on some days it just doesn't want to work and after it's daily scheduled restart, it eventually works again.  Not sure of any particular pattern yet.

**Comment by ooii** [comment]
I'm experiencing the same issue with a linux server. Also hanging on nest servers dns resolution.

**Comment by peaz** [comment]
I was having the same problem. But after a while I figured out why that's the case for my install. I've blogged it [here](https://www.atpeaz.com/fixing-homebridge-no-accessories-responding-problem/) so I would remind myself of it for future installs, but long story short
1. Check and make sure multicast is enabled on your router. Different routers may have different settings that need to be configured to get this done properly. I'm using an Asus AC87U and there were a few settings that I needed to ensure is configured in the IPTV settings.
2. Disable sleep mode for the WiFi module on the Raspberry Pi.. yup. Took me a while before I figured this out.

Hopefully these would help you too. My install has been stable ever since.
