### ISSUE TITLE
Couldn't find config.json after finding config.json

### ISSUE THREAD

**Issue by carnifex82** [nfarina/homebridge#379]
Hi there,

so I instaslled homebridge via npm and added the homebridge-fhem plugin afterwards.

First start of homebridge:

	pi@fhem-pi ~/.homebridge $ homebridge
	[cut bonjour warning]
	Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-fhem' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-fhem'.
	Loaded plugin: homebridge-fhem
	Registering platform 'homebridge-fhem.fhem'
	 ---
	Couldn't find a config.json file at '/home/pi/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

Why it believes that it needs to load fhem twice, I don't know.

So the config is missing. I copied the sample config from https://www.npmjs.com/package/homebridge-fhem to ~/.homebridge/config.json

Time to try again:

	pi@fhem-pi ~/.homebridge $ homebridge
	[cut bonjour warning]
	Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-fhem' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-fhem'.
	Loaded plugin: homebridge-fhem
	Registering platform 'homebridge-fhem.fhem'
	 ---
	Loaded config.json with 0 accessories and 1 platforms.
	 ---
	Loading 1 platforms...
	[fhem] Initializing fhem platform...
	Couldn't find a config.json file.

So apparently it loads the config file .. and then it can't find it? I tried copying the config.json to my home directory, to the homebridge directory in /usr/local/lib ... no change.

So where do I need to place the other config.json file?

**Comment by nfarina** [comment]
Just pushed a fix for the first issue where it attempts to load the same plugins twice.

The second problem is occurring inside the fhem plugin. It's attempting to load its own configuration file `config-fhem.json` from `.homebridge` and when it doesn't exist it complains about not finding `config.json` (which is the wrong name).

I'll add the user storage path to the homebridge API for plugins (since it's now configurable) but @cflurin will have to update the fhem code in that repository to fix the issue.

**Comment by nfarina** [comment]
Moving discussion to https://github.com/cflurin/homebridge-fhem/issues/1
