### ISSUE TITLE
IOS won't pair

### ISSUE THREAD

**Issue by jerle69** [nfarina/homebridge#381]
For whatever reason, my IOS apps wouldn't see the homebridge any more (I was fiddling with the platforms).  So I decided I'd blow away the home kit configuration on IOS and reset the configuration under privacy also and start over.  Now none of the IOS homekit apps ever discover the homebridge, nor do they allow me to pair against the pin like it did the first time.

Anyone know what's going on?

Thanks,
Barry

**Comment by rudders** [comment]
I had a similar issue - renamed homebridge in config.json and the userid as well for good measure and it all came back okay.

**Comment by Be2daErtin** [comment]
Hi,

When you start up after resetting, do you also get stuck at "HAP Listening...."

Usually opening the app on my phone created the HAP server to respond. But now it just sits... waiting....

I think it could be one or more of:
1. Using a wifi dongle in a pi. Cable seems to break it.
2. Setting a static IP seems to be better.
3. Don't change the IP for the HAP server 

It could be that homekit is somehow working together with icloud and making changes to your HAP server just breaks everything. Maybe also give it some time to find itself.

**Comment by nfarina** [comment]
Two reasons why Homebridge may not be discoverable:

  1. Homebridge server thinks it's been paired with, but iOS thinks otherwise. Fix: deleted `persist/` directory in your user/.homebridge folder.

  2. iOS device has gotten your Homebridge "username" (MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your "username" in config.json to be some new value.

**Comment by jerle69** [comment]
Your second suggestion worked... Thanks!

**Comment by nfarina** [comment]
Glad to hear it! Closing this for now.
