### ISSUE TITLE
Remote Control over cellular (IOS 9) without Apple TV (Gateway)

### ISSUE THREAD

**Issue by benbeton** [nfarina/homebridge#412]
since iOS 9, remote access should work without the need of a ATV, is this a limitation of homebridge?! 

Would be great to have a solution without ATV

There is a thread for access with ATV https://github.com/nfarina/homebridge/issues/256

**Comment by humac** [comment]
My guess is that it is not feasible.  From what I understand iOS 9 removed the need for ATV by moving homekit to iCloud.  So device manufacturers can would have to enable their homekit devices to publish it's services to iCloud api.  Since homebridge is running locally and not talking to iCloud API but on the local network it is not possible without an ATV3/4.  This is just my guess based on what I have read and understand.  Homebridge would have to expose all the devices to iCloud Homekit API's for this to work.

**Comment by KhaosT** [comment]
@benbeton humac is right. iOS 9 introduces HAP enhancement like HAP over iCloud which allows iOS device to talk to HomeKit accessory using iCloud as a tunnel. However, since this is a protocol enhancement, it requires accessory side modification to add support for communicating with iCloud.
To support HAP over iCloud, accessory needs to perform a MFi challenge using MFi chip to get necessary access to iCloud which I believe won't be possible for most of users since you can't just go out and buy a MFi chip breakout board. Because of that, the underlying server hap-nodejs won't add support for HAP over iCloud.

**Comment by benbeton** [comment]
@humac @KhaosT thanks for explaning HAP and MFi, I haven't found a lot information about this, thats why I asked.

**Comment by Kosta-Github** [comment]
But could an AppleTV (2, 3, or 4) be used as the iCloud connector enabling remote access/control for hap-nodejs? This doesn't work for me neither...

**Comment by KhaosT** [comment]
@Kosta-Github Apple TV 3 or 4 can be used to enable remote access for HomeKit. tvOS 9.0 or later is recommended. Due to the complexity of HomeKit Remote Access, sometime setup might fail. Sign out iCloud and re-sign in on Apple TV may solve the issue.

**Comment by prateek1108** [comment]
Hi,
I am also facing the same issue on ios 9 icloud backup backups of ios 8 and below are listed. i also tried iloot same issue is there in that.
