### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by ffranks** [nfarina/homebridge#448]
Registering accessory 'homebridge-liftmaster.LiftMaster'
---
/usr/local/lib/node_modules/homebridge/lib/server.js:129
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:129:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

**Comment by rudders** [comment]
Post your config.json pleae to help us help you out.

**Comment by ffranks** [comment]
I was using:
	"accessories": [{
		"accessory": "LiftMaster",
		"username": "myemail",
        "password": "my password"
	}]
}

Then added:

{
	"bridge": {
		"name": "Garage Door",
		"username": "00:01:01:01:15:CD",
        "port": 52826,
		"pin": "977-65-432"
	},

After that, it now loads. However, I have a new issue. If I close out terminal window, it ceases to function properly.

**Comment by mpdifran** [comment]
Here's my `config.json`:

    {
        "description": "JSON API",
        "platforms": [
            {
                "platform": "SmartThings",
                "name": "SmartThings",
                "app_id": "xxx",
                "access_token": "xxx"
            }
        ]
    }

Should there be more in it?

**Comment by rudders** [comment]
You need to set it up as a daemon- check out the wiki for some auto start options and other issues. Very platform specific.

**Comment by AppleTechy** [comment]
@ffranks I was going to say your original issue was due to the MAC address being improperly formatted but based of what you posted on the Dec. 31 it shows that you fixed that issue. I believe @rudders has answered your question about closing the terminal window. If not please create a new issue so it can be more clearly addressed(but feel free to reference this if you need to).

@mpdifran take a look at the sample config. You are missing the entire bridge setup which is essential for homebridge to run. I would just take the sample config rename it and then build of that/edit it because it already has the essential info included in it. The bridge part should be included and  should look like something like this 
"bridge": {
"name": "Garage Door",
"username": "00:01:01:01:15:CD",
"port": 52826,
"pin": "977-65-432"
},
