### ISSUE TITLE
"TypeError : Path must be a string" when start homebridge on boot

### ISSUE THREAD

**Issue by casper-gh** [nfarina/homebridge#460]
I setup homebridge to start on reboot (RPi). But I saw this error when Deamon tried to start homebridge. In fact, homebridge starts fine after boot from `sudo /etc/init.d/homebridge start`

This is the error:

![image](https://cloud.githubusercontent.com/assets/7980348/12137466/b8474c90-b405-11e5-9536-1efe1c4669e8.png)

**Comment by herious1989** [comment]
I also found this error from var/log/homebridge.err

![image](https://cloud.githubusercontent.com/assets/7980348/12163548/6c17cef8-b4c3-11e5-9e19-eea275a68163.png)

    Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by rudders** [comment]
have you installed libavahi etc from as per the wiki - and did it install properly (errors)

`https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi` 

`sudo apt-get install libavahi-compat-libdnssd-dev`

**Comment by herious1989** [comment]
@rudders yeah I installed it, no error whatsoever

**Comment by rudders** [comment]
Another homebridger @Jborn4christ had this issue - https://github.com/nfarina/homebridge/issues/421#issuecomment-164328966 - can't trace back to see what fixed it - perhaps approach them for help also.

**Comment by arnthorsnaer** [comment]
@casper-gh @rudders I think this problem is unique to launching with launchdeamons. LaunchDaemons define their own enviroment variables (and users can set them in launchd.conf). Homebridge is looking for : HOME, HOMEPATH or USERPROFILE - however my launchd.conf only specifies PATH.

So I don't think the fix should be in this project (unless someone writes a launchdaemon feature in homebridge) ... the fix is probably that we who are using launchdaemons define HOME or HOMEPATH

https://github.com/nfarina/homebridge/blob/master/lib/user.js#L30

**Comment by arnthorsnaer** [comment]
Seems the problem is most likely both with path.join in Node 6 and setting the required env in setenv.

Anyways, I fixed this for me by hardcoding my user directory in lib/user.js

`User.storagePath = function() {
  if (customStoragePath) return customStoragePath;
  //var home = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
  return path.join("/Users/myusername", ".homebridge");
} `
