### ISSUE TITLE
Dynamically reload platform accessories

### ISSUE THREAD

**Issue by johannrichard** [nfarina/homebridge#465]
Homebridge platform plugins like OpenHAB or [the one I recently build](http://github.com/johannrichard/homebridge-mystrom) all connect to systems where the number of accessories can and will change dynamically over time. Unless I missed it, `homebridge` does not provide any means to dynamically reload the accessories a platform provides, and hence, one has to restart the process every time a new accessory is added to the platform. 

It would be nice if this was changed at some point.

**Comment by snowdd1** [comment]
See #237, this would require plugins to be able to restart the bridge's advertiser.

**Comment by AppleTechy** [comment]
@johannrichard My understand is that the homekit platform doesn't allow dynamic device. Though I believe if my understand is correct iOS 9.3 beta does allow dynamic device loading which then the homebridge plugin can be edited to support this new function in the newest version of HomeKit. If that makes any since...?

**Comment by KhaosT** [comment]
@AppleTechy Apple allows bridge to add/remove bridged accessory. It's just hap-nodejs doesn't implement that initially because the upper stream package (mdns) doesn't support update TXTRecord. Now I fixed that so it's possible for homebridge to make necessary changes to adopt this :)
