### ISSUE TITLE
as of this morning just stopped working

### ISSUE THREAD

**Issue by EnigmaFx** [nfarina/homebridge#502]
http://d.pr/i/11dNK <— ok so everything loads fin NO errors nothing seemingly no issues at all up until last night everything worked with out so much as a hitch all of a sudden this morning WHAM nothing!  non of my hubs or nests will work with siri?!

**Comment by jndizoglio** [comment]
Did you try wiping out your persist file in homebridge?

**Comment by maddox** [comment]
> Did you try wiping out your persist file in homebridge?

Is there any particular reason this might resolve issues like this? Or is this just considered the last result?

I've had my devices just disappear as well in the past and this is what I did to resolve it, but I mean, of course it should, it's a full reset of the whole system. It's particularly annoying when you have many many devices in many many rooms. It's even worse when you're sharing your HomeKit DB with other people.

Is there a better way to debug this type of situation rather than starting from scratch?

/cc @nfarina @KhaosT

**Comment by AppleTechy** [comment]
@maddox We ended up reseting the entire thing when discussing it over slack. We tried reseting the identifier file in .persist file but that didn;t work. I would love to hear if there is a better solution as to be prepared if it happens to me.

**Comment by KhaosT** [comment]
@maddox I personally never experienced something like this so I'm not exactly sure. It would be great if any of you guys can provide detailed homebridge logs and iOS logs during this happens so I can actually figure out what goes wrong…

**Comment by maddox** [comment]
I'll do it next time. Thanks!

**Comment by tonesto7** [comment]
Mine does this all the time.  The only devices that remain are the accessories.  All of the platform devices disappear as it they were never there.  A quick reboot of the server usually resolves it.

**Comment by KhaosT** [comment]
Can you post the list of plugins you’re using?

Best Wishes,
Tian

**Comment by tonesto7** [comment]
nest
smartthings
lifx-lan
sonos
thinkingcleaner
liftmaster

**Comment by KhaosT** [comment]
BTW can you guys try to upgrade homebridge to 0.2.17 and see if this issue still occurs?

**Comment by alexandrupaulpopa** [comment]
complete noob here, what's the command to upgrade?

**Comment by KhaosT** [comment]
@alexandrupaulpopa try ``npm update -g homebridge``

**Comment by alexandrupaulpopa** [comment]
one more question how do i check the version number that is currently installed?
