### ISSUE TITLE
Sending commands directly to Homebridge – trigger scenes?

### ISSUE THREAD

**Issue by henriklied** [nfarina/homebridge#517]
I was able to send commands directly to accessories connected to my Homebridge with a PUT request to /characteristics, after finding the right one in /accessories.

But I was wondering if it's possible to trigger scenes as well. Or are the scenes maybe not saved on the Homebridge server?

Is this at all possible?

**Comment by robertvorthman** [comment]
I would also like to be able to programmatically trigger scenes or something to that effect.  I want to use an Amazon Dash button to turn on an iDevice Switch which turns on my coffee maker.  The Raspberry Pi can listen for the Amazon Dash, but I'm not sure how to command the iDevice Switch.

**Comment by KhaosT** [comment]
@robertvorthman [homebridge-amazondash](https://www.npmjs.com/package/homebridge-amazondash) allows you to bridge Amazon Dash Button to HomeKit as a programable switch, after that you can setup an event trigger in HomeKit to control your iDevice Switch

**Comment by robertvorthman** [comment]
@KhaosT Perfect!  Thank you for your quick response and for writing this plugin.

**Comment by martinjuhasz** [comment]
Is there a way to trigger a scene without using a switch and event triggers?
I would like to switch a scene inside my plugin code. I guess this is not possible due to the design of homebridge/homekit?

Is the best option for me to create a ghost switch in my plugin code and then creating triggers using the home app? The only other solution i can find is to "recreate" a scene by switching every accessory using characteristics.
