### ISSUE TITLE
Question: Any consensus on best iOS app for managing home/devices?

### ISSUE THREAD

**Issue by theboyk** [nfarina/homebridge#520]
Hey all,

I have Homebridge working stable for the last few days (running on an OS X server w/ autostart, etc.) and in this original setup I've been using [Devices](https://itunes.apple.com/us/app/devices/id966877433?mt=8&uo=4&at=11l4L8). Works fine, so I don't need another app, but just wondering is there's any consensus as to what app might work "best" with Homebridge?

Thanks,
Kristin.

**Comment by snehalnayan** [comment]
+1 for this

Devices is not paid at $2.99.
I have used iDevices 
https://itunes.apple.com/us/app/idevices-connected/id682656390?mt=8

And also Ezzi Home
https://itunes.apple.com/us/app/ezzi-home-control-for-homekit/id1039845950?mt=8

I prefer iDevices over the other since it tells me if home bridge is offline.

Both are free.

But do not mind spending on Devices app if its worth it.
Has anyone used others and done the comparison.

**Comment by KraigM** [comment]
One of my future plans for [HomeBridge Controller](https://github.com/KraigM/HomeBridgeController) is to bring it to iOS and add in HomeKit as well.

**Comment by justme-1968** [comment]
i think eve is the most complete regarding support for different acessorys and service/charactersitic types. and it is free.

if anyone is doing an app with a tighter integration to homebridge then it would be great to set defaults for rooms and scenes from the homebridge side and also be able to save and restore this.

**Comment by digiltd** [comment]
I agree about Eve. It is not locked to "Elgato Eve" hardware, has regular updates and it is free. 

The one thing it has trouble with is Service Groups.... though I am not too sure what a Service Group is, but I have put my Harmony Hub actions into a "Harmony" service group. I use the Homekit Catalogue app for that, which you have to compile and install yourself. Tutorial here https://www.youtube.com/watch?v=MhlK1LNE6ZE (requires a Mac) 

I am tempted by "Home" but not sure what the hefty price tag will give me that I don't already have. But I here good things about it.

MyTouch Home had potential, but once you start having more than a few devices, the circle based interface becomes useless http://i.imgur.com/BRFPsgN.png

**Comment by khorn73** [comment]
I find myself using iDevices the most. It seems to be the best to set up your home and organize it. Plus it is easy to go to a room and turn on and off your devices.

I did, however splurged and bought Home, but I'm not sure it's worth the price. The main feature it offers is, "Triggers", which I'm not sure if any of the free apps offer. Triggers, if you're not aware opens HomeKit up to more possibilities by adding conditions. For instance, you can set up a trigger to play a scene when you come home, but then specify it to only work at a certain time and only if another scene is active and so on. For example, I set up a trigger to turn on a fan when I shut off a light, but only if it was after 10pm and the temperature in the room was above 70 degrees. Home isn't a replace all other apps kind of app, but I do find myself going into it to set certain things. Another thing it allowed through triggers is the ability to unlock my Ecobee's remote sensors motion detection. I now have a trigger to shut off lights in a certain room when the Ecobee sensor detects no motion. Unfortunately, I can't have the lights come on when it detects motion because the Ecobee sensors have about a three minute delay before they send the signal they've detected motion. That is unless I want the lights to come on three minutes after I've entered the room.

**Comment by JotWee** [comment]
myHome - Home Automation
https://itunes.apple.com/de/app/myhome-heim-automatisierung/id1064362767?mt=8

**Comment by nicknewlin14** [comment]
@digiltd The big thing you get with the Home app is trigger editing and configuration. More of the manufacturer apps are starting to support time based / scheduled triggers, but Home supports device characteristic triggers and geolocation triggers.

One issue though is that Apple isn't allowing Bluetooth LE device characteristics to be used for triggers yet, so you can't use the Eve door/window sensors for example as triggers, yet.

**Comment by JotWee** [comment]
myHome even supports iBeacon location events on triggers, is cheaper and much more comfortable.

**Comment by digiltd** [comment]
Thanks @nicknewlin14. Do you know if it offers anymore than the HomeKit Catalog app in the way of triggers and characteristics? Always happy to pay for a decent app, but sometimes "buy it and see" doesn't always work out. 

@JotWee You're app looks loverly, but the same problem exists. What does the £6.99 give a Homebridge user (who is already comfortable with the workarounds and hacks home automation requires) in terms of functionality that the free apps don't?

I don't mean to sound negative, or to put any app down. But I have purchased several Hue apps in the past. Yet learning how to use the api seemed to be the only way to achieve what I thought was relatively basic control (group lights in rooms, set scenes, simple transitions).

**Comment by JotWee** [comment]
You actually don't sound negative, you're asking the right questions. The free apps (and the non free as well) usually miss a feature. Usually the trigger support is not complete with respect to the possibilities HomeKit offers at the moment. The HomeKit Catalogue app itself is not even complete in that regard. Then, my and other apps as well offer Today Widgets and ApplWatch apps. My app btw is the only one I know that even supports watch complications. 
But when I read you post, I have the the impression you mainly want to use it for hue lamps. Apps that use the hue API can be much more powerful with respect of controlling light and light transitions. I would never recommend a HimeKit app for this alone. HomeKit only gets interesting in my opinion, when you want to combine different types of accessories from different manufacturers.

**Comment by digiltd** [comment]
@JotWee Thanks for the reply, and I am glad it was not taken in the wrong way :)

I guess the whole HomeKit (and any home automation solution) still seems incredibly over complicated. With each manufacturer wanting to fence in their users by basically ignoring other manufactures devices, which is kind of the whole concept of IoT. Just so their users stay loyal to their hardware.

Whilst it is possible with great tools like HomeBridge and openHAB to work around this, it does require a moderate amount of development skills. Which thankfully I have due to my 20 years in web design and development. Perhaps that is why Apple are not really doing much HomeKit stuff, they see home automation to be very specialized and not mass market. 

I do use more than the Hue, though lighting is a bit part of my setup. But I also use the Harmony Hub, openHAB, several outlet switches, pir sensors, thermometers, wall switches etc. 

At the moment openHAB is my main "hub" and I set up sequences and scenes in that which I activate with switches linked to HomeKit through HomeBridge. 

I used to have all the scenes and rooms setup in HomeKit with triggers and all sorts, but I got tired of them disappearing at the slightest sign of a problem. With no way to restore.

So my "set scene time for bed" just just contains an openHAB switch with when triggered runs (amongst other things) the shutdown of the home entertainment stuff, turns on the upstairs lights, starts a slow 3 min transition of the lights to off to allow time to gather things and go to bed, it also reminds you if you have to put the rubbish or recycling out that night.

If you have the skills and time, at the moment there is no way to save a config (placement of accessories in rooms, zones etc) in HomeKit. Having a way that an app can save all settings out to a file would be great. Even greater if it could read and restore the config, I doubt Apple will allow a simple GET and POST of the data. But perhaps it could be achieved by mimicking the sequence of user actions to "recreate" the config like an old school macro.

**Comment by nicknewlin14** [comment]
To my knowledge the Home app supports the full range of HomeKit triggers. I haven't seen a trigger supported in another app that Home doesn't support.

I've been playing around a bit with OpenHAB myself. Spent most of the day Saturday getting my devices bound into it, and now I just need to plot out what I want my setup to be in the app itself. I agree that it does offer a lot more flexibility than most HomeKit based solutions.

**Comment by JotWee** [comment]
No, Home does not support iBeacon location based triggers.

**Comment by Anjarovskaya** [comment]
I found Ezzi Home supports Siri now https://itunes.apple.com/us/app/ezzi-home-control-for-homekit/id1039845950?mt=8
So I just telling what to do and it works. But for some reason not in my garage..

Interesting to know how Home from Apple will actually look like=)

**Comment by jer78** [comment]
There's a new app called Smart Homie that I like. I was using iDevices previous to that because I like nice looking UI's. Smart Homie does have the configuration options iDevices was missing plus iDevices was incorrectly displaying some homebridge accessories.

**Comment by MorningZ** [comment]
I've been enjoying using "Hesperus" for an app.... one thing I've found is no app seems to do more than 1 or 2 things well enough to be the go to app

I'll throw another 2 cents into the conversation: "Powerhouz" was a huge waste of $5... terrible/buggy app

**Comment by apwelsh** [comment]
I am using homebridge to Home Kit enable my Smart Things system, so I still use the SmartThings app for everything except Siri integration. I find Elgato Eve to be my favorite app for managing Home Kit.

**Comment by LwsBtlr** [comment]
On Jun 17, 2016, at 10:52 AM, Stephen <notifications@github.com> wrote:
> I'll throw another 2 cents into the conversation: "Powerhouz" was a huge waste of $5... terrible/buggy app

Remember, you can easily get refunds for apps you don’t want or are lacking. Just go to the receipt email and click on “Report a problem” and says it is defective or buggy and the refund is nearly always applied right away.

-- 
ɹןʇnqן
<mailto:lbutler@covisp.net>
303.219.0564

**Comment by matthijs2704** [comment]
iOS 10 Home app! 😁

**Comment by rcreasey** [comment]
Can confirm homebridge 0.3.4 works great with iOS 10 Home app.

**Comment by simonrb2000** [comment]
iOS 10 native home app is great as you can swipe up and quickly access your favourite devices, comes with an Apple Watch app that even supports dimmers using the Digital Crown. Although it only supports native HomeKit devices. Eve however doesn't have an Apple Watch app, but does support non native devices. (See edomoticz for non native devices like energy usage etc..)

There is another app called home which is nice and does have an Apple Watch app although you can't use dimmers on the watch like you can on the native iOS 10 Home app. Not used insteon+ app much.

You can use any of the above, I have all them installed and you can play around until you have your own preference.

Good luck!


On 4 Sep 2016, at 06:35, Ryan C. Creasey <notifications@github.com<mailto:notifications@github.com>> wrote:


Can confirm homebridge 0.3.4 works great with iOS 10 Home app.

-
