### ISSUE TITLE
Can the Homekit config (rooms, scenes, names etc) be backed up and restored?

### ISSUE THREAD

**Issue by digiltd** [nfarina/homebridge#535]
It is really depressing .... no, heartbreaking, when you have had a nice working setup with neat little rooms, zones, service groups and scenes. The after weeks of stable use and a connection issue leaves you with every accessory in the default room. 

I have tried backing up the persist folder, but it doesn't restore settings when you put an older version back.

It is not necessarily a Homebridge issue, as I lose all my Hue setup as well. Am I missing something? or is this all part of the undocumented mystery that is "HomeKit"

**Comment by devbobo** [comment]
@digiltd what version of Homebridge are you currently running ?

There has been some recent improvements made on hap-nodejs which I believe will result in the overall stability of Homebridge. Make sure you are running at least v0.2.17.

**Comment by digiltd** [comment]
At the time of writing 2.18 (with hap-nodejs at 0.2.3)

Which has been stable since posting the issue and was stable for quite a while before the incident that caused everything to reset (though I don't know what that was).

I think my problem is more the lack of backup and restore options, which appears to be a general HomeKit problem.

The goto advice from Apple is consistent in that if you are having problems with any aspect of HomeKit, then delete your Home and start again. Giving no mention of restoring your config. Which is a very tedious process.

Perhaps this will eventually be achieved through one of the client apps. 

Anyone know if it possible to assign an item to a room in the homebridge config? Or is that plugin dependant?

**Comment by KhaosT** [comment]
The idea of "room" only exists in HomeKit on iOS ... It's not possible for homebridge to alter HomeKit database on iOS without the help from a HomeKit app. Since this is an extreme edge case (backing up the home data), it's really hard to see Apple or any HomeKit app developer will try to make effort in this area. There are minor things that can be done better from homebridge/hap-nodejs side but in the end, it's really about what Apple should do to improve the stability of the system and what's the right way to do error handling. Their current solution of throwing away anything user created just for the ease of recovery is really not ideal for good UX.

**Comment by digiltd** [comment]
Thanks @KhaosT 

A similar answer can be found on #538

It really is bizarre how Apple are almost ignoring HomeKit with no official app, no multiuser support (making the use of geofence triggers very limited) and all round "vagueness" about its implementation and future.

Granted as anyone who has dabbled in home automation will tell you, it can be a nightmare connecting "things" together. So maybe they just don't see anyone other than dedicated thinkering "enthusiasts" would want anything more than turning lights on and off, and so can't be arsed to put money into it. 

Oh well. Roll on the UK launch of Amazon Echo.
