### ISSUE TITLE
Homebridge and PhilipsHue. Can we change the port 80?

### ISSUE THREAD

**Issue by marteken** [nfarina/homebridge#553]
Hi, Im almost done controlling my emulated hue devices (ha-bridge) through Siri. The problem is that my emulated server can't be in port 80 and homebridge search for the server in por 80. I know there must be something to tweak in the plugin itself, but I was wondering if someone has experienced this problem and knows how to fix it.

Thanks!

**Comment by cykew** [comment]
I encounter same issue. Any solution?

**Comment by cykew** [comment]
Marteken, you solve it?

**Comment by marteken** [comment]
hi cykew. no, sorry.

**Comment by cykew** [comment]
Hi marteken, check with you on how you do the start up of ha bridge and home bridge ? because home bridge required ha bridge to start up first else it would not be able to scan the accessories added in ha bridge. And i notice if network connection lost and come back, only ha bridge will be available, home bridge will not be able to re-establish again until i restart my device which installed the bridges. Any solution on that? thank
