### ISSUE TITLE
Explore "Bridged mode" server

### ISSUE THREAD

**Issue by nfarina** [nfarina/homebridge#58]
(Discussion forked from #54)

So here's an example of a problem here - try running HAP-NodeJS in bridged mode, add the bridge (which bridges a few sample accessories). Now you can do things like "Open the garage door" and it works behind the bridge.

However, now shut down HAP-NodeJS, remove/rename the GarageDoorOpener_accessory.js and restart the server. HomeKit doesn't "know" that the garage door is now gone. It still shows up in your HomeKit apps on your phone. And you can't Delete it yourself, because it was a bridged accessory. It's just sort of a zombie.

**Comment by madmod** [comment]
It looks like we need some kind of "cleanup" step on startup to un-register accessories associated with a bridge that aren't in the config.json. It [looks like](https://developer.apple.com/library/prerelease/ios/documentation/HomeKit/Reference/HMAccessory_Class/index.html#//apple_ref/occ/instp/HMAccessory/bridged) HomeKit has no way for a user to remove bridged accessories without removing the bridge. Removing the bridge each time we want to remove accessories might remove them from scenes, triggers, zones, and remove Siri names unless HomeKit uses the serial number or something to identify it rather than the bridge id. 

Is there a way to remove an accessory with HAP?

I think every instance of homebridge needs to remember what devices it has registered and remove the ones that aren't in `config.json` only if the user explicitly asks for it with a command line flag, as the file might be simply unavailable when homebridge is restarted. Once we get a web interface we could have more specific workflows to deal with new devices, changing names, etc.

**Comment by nfarina** [comment]
So it turns out that _adding_ a new accessory creates an odd situation as well: a new accessory _does_ magically "appear" in the list, but everything is now sort of "mixed up". The names of the accessories are all wrong (there are two thermostats, no garage door) even though the underlying services are correct. But Siri doesn't work with the newly-added Garage Door at all.

iOS does all the `/accessories` API on HAP-NodeJS periodically so it does seem like this should work. Either it hasn't been tested much or we're doing something wrong.

**Comment by madmod** [comment]
Perhaps this is not yet fully tested by Apple? Are there even any HomeKit bridges that are commercially available right now? What happens if you ask Siri to change the temperature on your "Garage Door"? :laughing: I doubt it is just some index off by one bug in HAP/iOS because [in HAP-Nodejs](https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/types.js#L29-L30) the `sTypes` are not close. (`40` and `4A`) Could it be some type coercion bug causing `4A` to become `40`?

**Comment by nfarina** [comment]
After more investigation I am focusing on `accessoryID` which is assigned on an increment-from-one basis in `BridgedAccessoryController`. I believe that this causes the bridged accessories to have unstable IDs - and I suspect HomeKit requires accessory IDs to be permanent.

Also I think this _must_ be supported - I think that the reason that the concept of "bridge" exists in HomeKit at all is precisely because of devices like the Philips Hue bridge. Apple can't expect you to add hundreds of lights one by one, it has to be a one-shot thing. And the set of lights has to be dynamically updated because any normal user would expect to be able to install a new light in their home and have it "just work".

**Comment by madmod** [comment]
It also could be a bug that has been fixed in iOS 9. I don't have any devices with the beta right now unfortunately.

**Comment by nfarina** [comment]
OK! I have some most excellent news :) It looks like, as long as the accessory representing the bridge itself is "1", the bridges accessory IDs can be anything, as long as the IDs of existing devices do not change when adding/removing devices.

I've just tested adding a single Bridge accessory (providing 5 bridged accessories) and then removing one and :boom: it magically disappears from the home. Then I can add a new one with a different ID and :boom: it appears magically.

I think this is definitely the way to go. You can just pair with the bridge once, and all other devices can be added or removed without the user having to lift a finger.

**Comment by madmod** [comment]
That is great! :smile: 

If the ID must be "1" how can you have multiple bridges in one HomeKit database? (Multiple houses/bridges for different platforms)

**Comment by nfarina** [comment]
The ID is local to the HAP accessory server - really it's all hidden behind a single GUID that looks like a MAC address.

**Comment by madmod** [comment]
Cool! I am excited to never lookup the pairing code again! :laughing:

**Comment by nfarina** [comment]
OK one thing I just thought of. It could be that when Apple describes the limitations of not allowing bridged devices that "control the home", they mean that they may allow local (over wifi) control but not "remote control" of these devices via Apple TV. It would be good to test this - although I guess most people might not want this anyway. As in, "oops, Siri opened my garage door from the plane and now I've lost signal..."

**Comment by maddox** [comment]
It sounds like the definition of HomeKit bridge devices is being muddied. In HomeKit, a 'bridged' device is one that does not natively support HomeKit, and is in fact being bridged by a hub that does support HomeKit. "Support" here meaning it's a licensed hub with a HomeKit chip.

So, Insteon has a selection of devices it already supports, but none of them are native HomeKit devices. But since they talk to the Insteon hub, the hub then gets HomeKit support and advertises them on their behalf. So the hub (the bridge) is the actual HomeKit device. Its these unsupported (non HomeKit) devices that control the home (locks, thermostats, garage doors) that are not allowed. Insteon is not allowed to bridge them. Insteon is not allowed to make them available to HomeKit.

Any native HomeKit garage door, thermostat, lock, can be accessible from anywhere.


PLEASE excuse me if I'm speaking the obvious, lol. Especially seeing we're all talking on this repo, and even more specifically, this thread.

**Comment by nfarina** [comment]
Yes I believe you're correct - but having just successfully controlled a lock, garage door, thermostat, etc. from behind a HAP-NodeJS bridge, I think your earlier suggestion is correct that this limitation is purely in licensing and not (currently) a technical restriction imposed by iOS.

The next question then is, how confident are we that Apple won't impose this restriction later?

**Comment by maddox** [comment]
> The next question then is, how confident are we that Apple won't impose this restriction later?

Well they could lock us out with encryption for the WHOLE project just as easy right? lol. I mean I thought there was a promise of that from the get go. So we're lucky HAP-NodeJS got this far right?

#yolo

**Comment by nfarina** [comment]
Good point. Onward then!

**Comment by madmod** [comment]
I think it may be harder for them to lock us out of HomeKit because there are going to be a ton of IOT devices using this protocol. Unless they come up with some standardized firmware update process for hardware manufacturers to use. An App Store for firmware.

**Comment by maddox** [comment]
> I think it may be harder for them to lock us out of HomeKit because there are going to be a ton of IOT devices using this protocol. Unless they come up with some standardized firmware update process for hardware manufacturers to use. An App Store for firmware.

Yup yup. My favorite kind of limitation. :)

**Comment by alistairg** [comment]
OK - I just submitted a PR with bridge support. Not my prettiest code ever, if I'm honest, but I tried it with my two Hue bridges (with a minor change I'm sure we can fight about / remove!) and it worked great.

No more hundreds of pins to enter! :)

**Comment by alistairg** [comment]
On a plane at the moment and just catching up with this thread.... as far as I can see from playing with the accessory simulator, there really is no limitation on accessories that can be bridged. If anything, for this project, it's likely a performance benefit using a bridge as it spawns fewer server / transport processes (as bridged accessories share the transport with the parent bridge).

Interestingly, the simulator supports services on the bridge itself, which HAP-NodeJS doesn't. I can't see a real-world situation that'd logically use that though.

Honestly I'm surprised that we haven't seen a "takedown" notice from Cupertino yet though. What I suspect we *will* see in the future is the mandated signature during pairing for supporting HomeKit accessories (note the popup we get now saying "Not tested with HomeKit" or similar?). That'll make awesome projects like this moot anyway.... :(

**Comment by flynhawaiian** [comment]
I'm running iOS 9 beta 4 and everything is working. At least the lights. I've created some scenes with Siri and it seems to work well. 

The one thing that would be fun is to figure out how to clone the thermostat

**Comment by nfarina** [comment]
Bridged mode is now supported by default.
