### ISSUE TITLE
Send commands to HomeKit

### ISSUE THREAD

**Issue by bgottsch** [nfarina/homebridge#601]
Hello,

I have a setup in which I can turn my main light with a physical switch. When I use that switch, my home automation network (Insteon), broadcasts the change. I would like to update the HomeKit database when this happens. My ideia was to create and event listener on a raspberry pi which would listen to all commands. And when a command is received, it would send the appropriate action to HK and update the db? Is there a way to send actions from homebridge to HomeKit (or programatically from the same machine the homebridge server is running)?

Or is it pointless? In thesis, every time a HomeKit enabled app opens (including Siri), the app should fetch new results from the accessory and update the database. In this case I would need to simply implement a method for the homebridge accessories to fetch their current state.

Thanks

**Comment by snowdd1** [comment]
Hi, 

this is possible and several plugin already do that, one of them is my homebridge-knx plugin.

You simply need an event listener that reacts to changes (or commands in your case) and sets the value of the characteristic. Any app that is open and supports events (Eve and myTouchHome do, e.g.) will instantaneously update their display. 
Even better, if an app or Siri asks for the value you do not need to fetch a new state in that moment, because your characteristic is already up-to-date.

I do (pseudo-code):
````javascript
event_register_function (event, function(value) {
    characteristic.setValue(value, undefined, 'myContext');
    // setValue(value, peer, context) 
    //    context is important to avoid loops, you have to check for your own context
    //    in your characteristic.on('set', ...) event listeners. If it is your own context, do nothing!
}
````

for actual code example, see here:

https://github.com/snowdd1/homebridge-knx/blob/master/index.js#L517

Good luck!
Raoul

**Comment by bgottsch** [comment]
@snowdd1 that's exactly what I was looking for. Thanks
