### ISSUE TITLE
Newb question

### ISSUE THREAD

**Issue by Floppybobby** [nfarina/homebridge#609]
I can start homebridge using the command 'homebridge', but that quits homebridge after closing the SSH session. I tried sudo /etc/init.d/homebridge start, but that gives me the error 'sudo: /etc/init.d/homebridge: command not found'.

**Comment by toshibochan** [comment]
Look this site! 
http://www.kramnameloc.com/homebridge-pi-switch

**Comment by snowdd1** [comment]
@Z0mb4y  Can you elaborate a little on your environment?
Are you using a raspberry with a raspbian wheezy, as toshibochan assumed?
Or might you have an actual raspbian (Jessie) with systemd that does not use the init.d things at all?
Or are you on a Mac?
So many questions...

**Comment by desvdp** [comment]
@Z0mb4y Hi, that's quite normal behaviour: when you start a program in a shell (such as an SSH session), the program will become a sub-process of that shell. When you close the shell, all sub-processes will be closed along with it. In order to keep it running you have to "decouple" it, for example by making it a "service". Given you're ssh-ing into your system I presume you're on a headless Linux box (such as a RPi). While other options might exist I suggest you have a look at this excellent writeup, as it's probably the best way to go anyway ...  [https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a] ()

**Comment by Z0mb4y** [comment]
Im using Raspbian installed using Noobs. Not quite sure if it's raspbian wheezy.

**Comment by andy-81** [comment]
@Z0mb4y 
You can find out the version of raspbian your using by typing "lsb_release -a" into the terminal window. This will give you which release your using. 
Also if you don't want to run home bridge as a service you can also use screen to allow you to detach and reattach allowing you to close the terminal/close ssh connection. You will need to install screen first of all using "apt-get install screen" and then once installed simple type "screen" at the terminal prompt run what you want to run and then press ctrl+d to detach from the screen. You can then reattach to the screen by typing "screen -r" from another connection. 
Running it as a service as toshibochan suggests is in the long run the best option however running it in a screen can help you with this and other projects you may do with raspbian.

**Comment by Z0mb4y** [comment]
@desvdp Thanks. I got it working but I had to set the permissions of '/var/homebridge' first.
