### ISSUE TITLE
Need to ask twice before Siri can find devices

### ISSUE THREAD

**Issue by M230** [nfarina/homebridge#611]
When homebridge has run for a day or so and I ask siri to "turn off the bedroom lights" on the first try siri will reply something like "I couldn't find any lights". I have to ask again before it will work.

**Comment by toshibochan** [comment]
What homebridge you using?

**Comment by M230** [comment]
0.3.3

**Comment by peterchrisben** [comment]
I can confirm this issue. Same problem here.

**Comment by maddox** [comment]
This has been happening to me for as long as I've used Homebridge.

The thing I'm not clear about is, is this a Hombridge issue? Or is this just how HomeKit works :/

**Comment by sooth** [comment]
We were never able to come to much of an answer on #404

**Comment by maddox** [comment]
So is this just the experience of everyone?

**Comment by rehafer** [comment]
This has been happening to me through all my updates. It feels like a time out problem, likely involving iCloud and reloading data, but I'm not sure. ICloud is a good suspect because it's often the culprit in Apple problems.

**Comment by jer78** [comment]
I also used to have this problem, but haven't in weeks now. Not sure if it's because of 9.3.2 or the fact that I had to rebuild HomeKit from scratch because it stopped sharing with my wife's phone and couldn't successfully re-invite her. 

I also used to have the "could not set the <scene name> scene" response from Siri, but I realized I was over-loading the devices on a scene. Turns out HomeKit can only take 50 requests per scene and each Hue lightbulb takes 4! So that added up pretty fast. Once I figured out a work-around, not it successfully says it set the scene.

**Comment by stipus** [comment]
I have the same problem here. After a while, I sometimes get a sorry on the first try, then Siri correctly executes the command on the second try.
However, I don't think it's related to Homebridge, as I also have a HomeKit compatible Philips Hue bridge, and the problem occurs with both HomeBridge devices and Philips bulbs.

**Comment by morpheus12** [comment]
I'm using homebridge with homematic and harmony plugin. All over i controlled about 70 items with it.
Same Problem here. After about 10-15min the first attempt crashs with "no response" or similiar and the second attemp works fine.

Disconnecting the iOS Device from WLAN an reconnect it provides nearly 99% all functions on first time. I think the iOS Device disconnect itself from WLAN for saving power.
