### ISSUE TITLE
start on reboot

### ISSUE THREAD

**Issue by salimyzadeh** [nfarina/homebridge#62]
do you know the best way to start homebridge on reboot on the raspberry pi. I tried using npm forever, but ran into stability issues

**Comment by madmod** [comment]
Can you be more specific about your stability issues? Are there any errors output by homebridge? PM2 is a good alternative but it can be a bit more complicated to setup. I think the issue is more likely to be network or hardware related than forever specific. I personally use forever to run several production servers for months at a time without issue.

**Comment by salimyzadeh** [comment]
if i simply use forever start app.js all is fine, but once i reboot the system the forever service is no longer running. I got it working by creating a bash script that executes on reboot

#!/bin/sh
#/etc/init.d/nodeup

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  cd /home/pi/homebridge &&
  #exec forever --sourceDir=/home/pi/homebridge -p /home/pi/pid app.js
  forever start app.js
  ;;
stop)
  #exec forever stop --sourceDir=/home/pi/homebridge app.js
  forever stop app.js
 
  ;;
*)
  echo "Usage: /etc/init.d/nodeup {start|stop}"
  exit 1
  ;;
esac
 
exit 0


save the file as nodeup.sh 
sudo chmod 755 /etc/init.d/nodeup.sh
sudo chmod +x nodeup.sh
sudo update-rc.d nodeup.sh defaults

and hombridge now starts on reboot

**Comment by Kolbi** [comment]
@nfarina maybe this startup script could be added to https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi , if it's working?
