### ISSUE TITLE
Accidentaly deleted Homebridge

### ISSUE THREAD

**Issue by Floppybobby** [nfarina/homebridge#620]
So I accidentally deleted Homebridge in the Home app. I got it to show up again by deleteing accessories, persist and changing the PIN, but all my devices are 'Not Reachable' on my phone now.

**Comment by psmith3** [comment]
Make sure that you are connected to your home wifi network and not on the cellular network or away from home. Stop the server and delete the persist folder. Remove the accessory from the Home app and then kill the app. Start the server and then open the Home app and search for the accessory on your iPhone. You need an Apple TV running on your home network that is logged into your iCloud account to be able to leave your home network. Sorry if this is all obvious.

**Comment by Z0mb4y** [comment]
@Psmith3 I was in my home network, but I'll try deleting the persist folder again.

**Comment by Z0mb4y** [comment]
Using 'homebridge', but running with systemd gives the error: 

 systemctl status homebridge.service
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2016-04-30 17                         :18:09 CEST; 8s ago
  Process: 989 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited                         , status=1/FAILURE)
 Main PID: 989 (code=exited, status=1/FAILURE)
