### ISSUE TITLE
Raspberry Pi Zero or 3?

### ISSUE THREAD

**Issue by Ricardo1980** [nfarina/homebridge#649]
Hello!
I bought a raspberry pi 3 to use with homebridge.
However, I wonder if it is possible to run homebridge in the raspberry pi zero, which is smaller and even cheaper (just 5 dollars).
Is that possible?
Thanks.

**Comment by PeteLawrence** [comment]
The Pi Zero should be powerful enough to run homebridge (I run Raspbian Jessie and Homebridge on an old Pi 1 which I believe has roughly the same specs).  If you went down the Pi Zero route you'll need to add a wifi dongle, and micro USB to USB adapter in order to get it hooked up to the Internet, whereas the Pi 3 has wifi built in.  You may also need a Usb hub and/or HDMI adapter if you don't want to run it totally headlessly.  Once you factor these in you'll be looking at a much smaller price difference.

**Comment by cflurin** [comment]
Just for fun I've installed homebridge on a pi zero.

You additionally need:

1 x MicroUSB > USB adapter 
1 x WiFi adapter
1 x Micro USB Power Supply

1. Install raspbian jessie on an e.g. Raspberry B+ and add vncserver, netatalk and configure the WiFi for the access to the router.
2. Insert the SD card into the pi zero and boot.
3. Install homebridge and plugins using a VNC-Viewer.

That's it.

**Comment by Ricardo1980** [comment]
That is really cool!
Will try to use it for my next project, thanks!

**Comment by apwelsh** [comment]
Any reason for VNC-Viewer?  I realize Jessie boots to a GUI by default now, but it would seem this is one of those scenarios where it would make sense to change the default to boot to command line and to use SSH when you need to manage the system.

**Comment by cflurin** [comment]
@apweish: It's up to you, sure you can use SSH. I am using several Pi's with the same jessie installation. So its easier for me to manage all them with my Mac mini > Share Screen. BTW SD Card Copier e.g. only works with the GUI.

**Comment by apwelsh** [comment]
Thanks for the info.  I'm considering using a raspberry pi.

**Comment by marcotini** [comment]
Why you need VNC? Homebridge is usable with terminal.
