### ISSUE TITLE
How should I add dependencies when developing plugins?

### ISSUE THREAD

**Issue by Ricardo1980** [nfarina/homebridge#657]
Hello!
I'm trying to create a plugin (switch type) and I would like to use a module called command-queue.
I added it to my package.json:

![captura de pantalla 2016-06-10 a las 20 27 26](https://cloud.githubusercontent.com/assets/738681/15976432/a73d6946-2f4a-11e6-832f-650b84533771.png)

In my index.js I have: var CommandQueue = require("command-queue");

but it seems when I try to load my plugin I recieve an error saying that the module cannot loaded.
Am I doing anything wrong? Thanks.

![captura de pantalla 2016-06-10 a las 20 27 43](https://cloud.githubusercontent.com/assets/738681/15976480/eee9a89a-2f4a-11e6-9d95-ecf9232a682f.png)

**Comment by Ricardo1980** [comment]
I have the same problem with node-hue-api.
The weird thing is that I only see those problems in my raspberry pi 3. But when I execute homebridge with my plugins in my mac, everything works fine.
What am I missing in my raspberry? Thanks.

**Comment by digiltd** [comment]
Just checking, but are you running `npm install` in the directory of the custom plugin?

**Comment by Kranzy** [comment]
I get a similar issue with accessories not registered by any plugin.

I am trying to add additional plugins in the package.json file.
` {
 	"scripts": {
 		"install": "npm install -g homebridge-synology homebridge-sonos --unsafe-perm",
 		"install": "npm install -g homebridge-onkyo-avr"
 	}
 }
`
That is a sample file i have been using and it only ever loads the last plugin in the list (onkyo in this instance)

I am running homebridge in a docker container on synology nas.

**Comment by digiltd** [comment]
@Kranzy What are you trying to achieve and are you adding that to the homebridge package.json?

It looks like you are trying to create a custom install script for your own use, is that correct?

**Comment by Kranzy** [comment]
@digiltd I am trying to create a custon install script for my own use. 

It is in a package.json file located in the homebridge folder. The script is run but only the last in the list. I think it is because there are duplicate keys. Im just not sure how to extend the plugins I can use.

**Comment by digiltd** [comment]
@Kranzy I am still confused. The package.json is for the homebridge package on npm. Anything you get from npm is configured in the package.json. This includes dependancies and there is a built in way you you to define them without adding a bash script (see https://docs.npmjs.com/getting-started/using-a-package.json).

What you are trying install with your script lines are not dependencies and unless you are packaging up something for npm there really no need to be messing with package.json. You stress levels will thank you :)

If you wanted to automate an install you can use a simple bash command that sequences up commands

Adding `&&` between each command you want will do the trick. But I would be careful with an automated install as it is harder to debug, instead install each plugin in turn and make sure each one works before adding the next

```
$ npm install -g homebridge-synology && npm install -g homebridge-sonos --unsafe-perm && npm install -g homebridge-onkyo-avr
```

**Comment by Ricardo1980** [comment]
@digiltd Thanks for the suggestion. I never called "npm install". Actually, in my MAC my custom plugins work and never use it. In a few hours I will try that in my raspberry. Thanks.
BTW, is it possible to write that in the "Plugin Development" section of the main screen if that is really needed? Thanks!

**Comment by Kranzy** [comment]
@digiltd I originally started using this as a guide. https://github.com/psmith3/synology-docker-homebridge/tree/master/config-sample and looking at the package.json 
the package.json file looked like how extra packages were installed. 

I was able to get it working using https://hub.docker.com/r/cbrandlehner/homebridge/ 

I was under the impression that with it being a docker container running on the synology nas that if the nas is restarted that when the docker is re-launched that the plugins would need to be re-installed as if it was a fresh start.

**Comment by digiltd** [comment]
@Kranzy Hmmm, yeah sorry, I know nothing about Docker installs work and less about how they work on Synergy. It looks like the package.json might be there for Docker rather than npm. 

You might have more luck with the issue on the  https://github.com/psmith3/synology-docker-homebridge repo. I assume you followed guide here : http://chris.brandlehner.at/Brandlehner/cab_blog.nsf/d6plinks/CBRR-A6XQUY

It looks like you have to add the desired plugins here also https://github.com/psmith3/synology-docker-homebridge/blob/master/Dockerfile but I am plucking at straws.

I know it is not the ideal solution, but perhaps start to consider the possibility of getting a cheap Pi2 (or Pi3 as they have built in wifi and bluetooth). Then there will be lots of people to help you with your install :)

**Comment by digiltd** [comment]
@Ricardo1980 I am guessing when you installed the packages originally on your Mac you would have used something very similar to `npm install -g command-queue` or maybe without the global `-g` switch.

When you install from npm it downloads the files that are unique to the package and the dependencies are listed in the package.json.

Part of the npm install process is to read that list and install the dependencies. 

Because you are not using npm you need to manually go into the folder and run `npm install` this will install the dependencies as listed in package.json

If you are not sure how npm or the general concept of package management it might be worth having a quick read of the getitng started which explains it very well https://docs.npmjs.com/getting-started/what-is-npm

**Comment by Ricardo1980** [comment]
Thanks @digiltd, it is working perfectly from my raspberry pi! It is so cool...
You have no idea how many hours I spent, even I reinstalled everything.
Apart form "npm install", I was having this problem:
"iOS device has gotten your Homebridge username (looks like a MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your username in the "bridge" section of config.json to be some new value."
