### ISSUE TITLE
Is there a way to use an accessory as variable?

### ISSUE THREAD

**Issue by dpyy** [nfarina/homebridge#666]
I want to create a trigger for when I leave the house AND when my wife leave the house.

This isn't possible with homekit. 

I'm thinking of hacking this by using a variable. When I leave the house, turn the "fake accessory" off. Then when my wife leaves the house, the trigger check for this accessory as a condition. It will only take action if the accessory is already off, otherwise do nothing. 

Would this work? If so, how do I create an accessory like that?

**Comment by jer78** [comment]
One way to do it is use Life360 and IFTTT. It's an app that has geofencing features for "when last family member leaves" or "first family member to come home" when paired with IFTTT. I use it with my Ecobee and then if Ecobee is set to away mode it can trigger other scenes. However, you could also use it for Hue light bulbs or other HomeKit devices you already have. It's a fairly easy way to do what you're asking.

**Comment by garywkfung** [comment]
What do you call from IFTTT? Can you make IFTTT call a HomeKit scene?

**Comment by jer78** [comment]
IFTTT can't connect to HomeKit but if you have a HomeKit device that also is on IFTTT you can do it in a roundabout way. HomeKit triggers on events can activate a scene.

**Comment by garywkfung** [comment]
I don't have any IFTTT hardware. Is there a homebridge plugin that can listen to IFTTT?

**Comment by kaiatkins** [comment]
I use https://www.npmjs.com/package/homebridge-people with home bridge

**Comment by garywkfung** [comment]
@kaiatkins thanks for the link but that solution seems such a hack. The delay is so long and not to mention it wont be consistent if you are not always on the network. 

Honestly, there are a ton of apps that can program geolocations that can trigger HomeKit. We just need a homebridge plugin to have a way to save state so we can do conditional geofences.

**Comment by DerEisvogel** [comment]
If you are all using iOS devices simply set up triggers to enable or disable a dummy switch.

Dummy Switch could look like this (not tested, but should work):
```
var Service;
module.exports = function (homebridge) {
	Service = homebridge.hap.Service;
	homebridge.registerAccessory("homebridge-dummy", "Dummy", Dummy);
};

class Dummy {
	constructor(log, config) {
		this.log = log;
		this.name = config.name;
	}
	getServices() {
		return [new Service.Switch()];
	}
}
```
I think there alreay is a dummy switch plugin available, but it resets the state after a second or so.

**Comment by garywkfung** [comment]
So I create a dummy variable in homebridge. But I found another roadblock, it turns out you can't have triggers from two different icloud accounts (mine and my wife's). So I can change the variable when I leave my home, but my wife can't change the variable when she leaves. Any ideas?

How can it be this difficult to use homekit triggers with 2 persons?

**Comment by creinhart** [comment]
This is most likely because currently other users in Homekit don't get admin access. So they can't setup triggers on their phones for geolocation. This is a problem I ran into last fall when I bought two iHome smartplugs for the purpose of multi user geolocation. My plan was when I would leave home, 1 switch would turn off and when my wife would leave home then the other switch would turn off. When both switches were off it would trigger the Hue lights to turn off. However, I could never get this to work because I couldn't setup geolocation through Homekit on my wives phone.

However, now with iOS10 since Homekit triggers run on the Apple TV and now that you can grant admin access to other users, I'm going to revisit this and test it out.

**Comment by garywkfung** [comment]
When iOS 10 is out, the dummy variable approach will work (both my suggestion and yours). 

However, that's still another 3 months away. I was thinking maybe a faster way to get to what we want is to set the state of an accessory in homebridge via some API. Because you can easily trigger API calls with IFTTT using geofences. But the problem is I can't find a way to get something like IFTTT to change the state of an accessory.

**Comment by creinhart** [comment]
Well you could always start using the ios10 beta. That's what we're doing.

I just took the Dummy Switch plugin and edited the index to get rid of the timeout so now it acts like a normal toggle switch. I have two of them running in homebridge: one for me and one for my wife. Later I'll test and see if she can make a location based trigger on her phone since she should have admin rights and then this should work.
