### ISSUE TITLE
Homebridge not opening port

### ISSUE THREAD

**Issue by lukeg01** [nfarina/homebridge#677]
Hello,

Since my device wasn't discovering any devices I ran the Fing app to scan services, however there was no active service on port 51826.
bonjour discovery doesn't detect anything either.
I don't have a persist folder.

npm 2.14.2 
Node v4.0.0
Osmc (Jessy based) on raspberry pi 3

Weird thing is that netstat command does show that the raspberry is listening on that port.

Really hope this can be fixed
-------------edit--------------------
After a reboot the item does show up on bonjour discovery but still nothing on iOS, can't find a persist folder anywhere (used 'find' )

Might be relevant that the automatic install installed it at:
`~/.npm-packages/.npm-packages/lib/node_modules/homebridge`

edit : 
after reinstalling homebridge I noticed, I don't get the no config error!?!?

**Comment by kemathy** [comment]
Hey, 

I'm facing quite a same error, as Homebridge binds well on :::51826 (ipv6), but not on 0.0.0.0:51826, even if there's no other process already using this port... And there's no error message regarding a port-binding problem at homebridge startup.

It's quite strange :-)
Thanks,

Kevin

**Comment by apwelsh** [comment]
have you reviewed this: http://stackoverflow.com/questions/25439158/avahi-daemon-gets-stuck-registering-a-service-im-publishing-with-avahi-publish

It sounds like these suggestions might be of help for getting avahi to publish.

As fir the port binding failure, i would reboot, run netsrat -an | grep ':51826'
If you see any port binding, it will interfere.

**Comment by krys1976** [comment]
Since last update of homebridge, it isn't working anymore due to ipv6-only startup of listening ports as kemathy has describben already. Comment of apweish is misleading, as this has been working in prior versions well.

**Comment by apwelsh** [comment]
Comment is about how to isolate the issue to ensure it isnt binding becaus eif code as opposed to exiating bindings, nothing more.

**Comment by krys1976** [comment]
@apwelsh a fresh started machine without any auto-starting daemons, doesn't have prior/existing bindings to that port on ipv4. On netstat -tulpn | grep ':51826' you'll find only one opened port, it's the ipv6  to all interfaces, even if sysctl had disabled ipv6 on kernel level.

**Comment by kemathy** [comment]
Totally agree with krys1976
I had ipv6 disabled on my system, but homebridge only opens tcp6 socket at startup, and no other port.
And, yes, I checked before if there was no other process already bound on 51826, for ipv4 or ipv6...
So strange!

Thanks for help,
Kevin

**Comment by cmera** [comment]
This may be an issue with how hap-nodejs is creating the listener port.  

According to some threads I read it appears avahi will first try to publish on ipv6 interfaces when available, otherwise it will go to ipv4 interfaces.   

On Linux systems, a short term workaround is to disable ipv6 within avahi daemon in /etc/avahi/avahi-daemon.conf with command below followed by a system reboot.

<code>sed -i '/^use-ipv6=/s/=.*/=no/' /etc/avahi/avahi-daemon.conf</code>

**Comment by kemathy** [comment]
@cmera Thanks for the workaround ;-) 
Actually, I'll not be able to test if this fix is OK, because I re-installed from scratch my Rpi, and Homebridge works again :-/ 
But, in case it's broken one more time, I'll try your command !

**Comment by nicolasd1980** [comment]
I seem to be having that issue as well and @cmera's workaround didn't help

**Comment by etf5000** [comment]
Try deleting your persist and accessories directory in .homebridge.  They automatically regenerate when you start homebridge again.  Seemed to work for me.

**Comment by JekaKey** [comment]
Try to change port in config.json to other, for example to 51824.

**Comment by erfinb** [comment]
Where do we change this in the config.json?

**Comment by SonicRevolutions** [comment]
Did anyone manage to find a fix for this issue? I've tried all the suggested solutions above but without luck. Avahi advertises homebridge on the IPv4 address but the port still only opens on IPv6.

**Comment by SonicRevolutions** [comment]
Fixed it, seems it was an avahi config issue. Sometime ago I set the host-name domain-name and browse-domains parameters making it act weird. Disabling them made avahi and homebridge work again.

**Comment by scotbrew** [comment]
If HAP (_hap._tcp) is showing up correctly using a Bonjour Discovery app, then you may need to **flush your iPhone HomeKit pairings** and **make the homebridge config unique**.  Before running homebridge on a raspberry pizero w, homebridge was running from a different machine.  As a result, the iPhone was confused and would not see the new server.  

I have since changed the **config.json** file to use a distinct "name", "username", and "pin" for clarity.  I also reset the HomeKit cache on my iPhone -- search for "**How to Reset Your HomeKit Devices and Configuration**" for details.

All is working for me now as expected.
