### ISSUE TITLE
No error message for missing config.json

### ISSUE THREAD

**Issue by webdeck** [nfarina/homebridge#696]
I was helping someone troubleshoot their configuration and was scratching my head, until I realized they had put their config.json in the wrong directory.

It turns out, homebridge doesn't give an error if it can't load config.json.  I thought it used to give an error, but the current version definitely doesn't.

**Comment by KhaosT** [comment]
Yeah, after adding support for plugin 2.0 system, the configuration file is now optional.

**Comment by toshibochan** [comment]
How to add accessories whit out config.json?

**Comment by robertvorthman** [comment]
I was confused by this too until I read the source code (server.js) and found that the line of code (163) that warns about a missing config is commented out.  The readme should be updated.

I was running homebridge with sudo because I needed elevated privileges to run homebridge-amazondash and it took me a long time to realize that Homebridge was actually not finding my config.json file because it was looking in the root folder (because of sudo) instead of my home folder.  If the config.json warning had been there I would have realized the issue earlier.  By the way, the Amazon Dash plugin is awesome for turning on my coffee maker.

https://github.com/nfarina/homebridge/blob/0af8a43dc9da8f4aa59984a609f531fa7d384919/lib/server.js#L163

**Comment by johnypony3** [comment]
Yeah that looks fine, how about logs?

Homebridge logs to two places:

1. /var/log/homebridge.log
2. /var/log/homebridge.err

I suggest you look in them to see if anything jumps out at you.

**PROTIP**: unix has the `tail` command, it makes it really nice to see logs in real time.

Assuming you have homebridge running, from that server run one of the following commands to see what is getting logged live.

```
tail -f /var/log/homebridge.log
tail -f /var/log/homebridge.err
```
