### ISSUE TITLE
HomeBridge starting problem

### ISSUE THREAD

**Issue by FlyersPh9** [nfarina/homebridge#698]
I am in the process of installing HomeBridge on a Raspberry Pi B+ for the first time.  The only plugin I have installed is [homebridge-smartthings](https://www.npmjs.com/package/homebridge-smartthings).  When attempting to start HomeBridge I get the following warning & error messages:

**Warning:**
`*** WARNING *** Please fix your application to use the native API of Avahi!`

**Error:**

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:351:14)
```

Any advice on how to proceed?

**Comment by robbiet480** [comment]
Something is already running on port 51826. Looks like it may be trying to bind to your IPv6 interface too because it has two colons.

**Comment by CelticWebSolutions** [comment]
I think mine is connecting to IPV6 too, how can we stop that from happening?

**Comment by thejacko12354** [comment]
Did you start it as root or as a normal user?
Because on my raspberry it only runs when started as root

**Comment by FlyersPh9** [comment]
@robbiet480, any advice on how to fix either of the problems you mentioned?  I'm fairly new to this and don't know where to start looking.
@thejacko12354, I just tried running `sudo homebridge` and am still getting the same error.

**Comment by anrob** [comment]
Open activity Monitor
Search for Homebridge
Kill Process 

Hope that works for you

**Comment by kemathy** [comment]
Isn't it quite similar to this issue https://github.com/nfarina/homebridge/issues/677 ?
I face the same problem, even if I don't have any other process already bound to port 51826, and even with IPv6 disabled in the OS 😣

**Comment by Nnk2** [comment]
I have this same error since a few days (all was running well before, and I have not made any changes on my rpi). However, changing the port does not solve the issue, so I do not think this is the root cause. In my case changing the port just give a dns name error now (I already posted that error in #725 )

**Comment by Nnk2** [comment]
Full reload of OS fixed if for me: ( same as #725 )

**Comment by kemathy** [comment]
I'll give it a try this evening, as I can re-install my Rpi without any collateral damages :-) But it's a quite violent way to fix this problem !

**Comment by Nnk2** [comment]
@kemathy:
Agreed; but since I could rule-out a corrupt ad card, nor find the root-cause I figured this was the less evil option :-(

**Comment by ozaoral** [comment]
I ran into this problem as well, after reinstalling my Pi with a fresh homebridge configuration. I was able to install and set-up everything and it worked well. Then I followed the tutorial to set-up the autostart (https://timleland.com/setup-homebridge-to-start-on-bootup/) as as soon as I rebooted the Pi for the first time, I started to get this error. 
I tried many things and then removed the bootup services. Since then, Homebridge worked well again. So I created the boot services again and paid a little more attention this time :)) 

**Problem 1: wrong folders** 
- stick to the instructions and gists here: https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/
- pay attention to the folders in which you installed homebridge: if you followed the easier node installation using apt.get as described in the main tutorial in this repo (https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup), you need to change the homebridge.service contents as described in the gist (leave out "local" in ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS)

**Problem 2: permissions** 
- when launching homebridge as a service (not manually), it is necessary to pay more attention to the permissions
- I had iKettle plugin for CMDswitch2 installed to the home folder of Pi user ... I moved it manually, changed the config.json and it works now

**Problem 3: issues related to plugins** 
- on top of all of this, I had an issue with one of the plugins as well
- when multiple issues cross in your home setup, it is not always easy to find the solution (mainly in cases when a problem with plugin is able to influence homebridge so badly, that also other things quit working)

Hope this helps at least to some of you guys!
