### ISSUE TITLE
iOS 10 Homekit - Custom Lightbulb Hue service not detected

### ISSUE THREAD

**Issue by Luc-S** [nfarina/homebridge#734]
I know iOS 10 is still in beta and maybe I should just wait a couple of months but I was wondering if someone can help me with a small problem I'm having using the iOS 10 Homekit app combined with Homebrige;

I have build a custom plugin containing 1 platform and 4 accessories. All accessories configured which are temperature/humidity sensors, alarm and multiple MiLight smart lightbulbs work fine with the Elgato Eve iPhone app. Homekit on iOS 10 works awesome too however it can't seem to detect the hue (color) service of the lightbulbs, it only allows me to set brightness.

I can't seem to understand why this is because the Elgato Eve app gives me the color option for the lightbulbs and controls it perfectly fine. It's not a huge deal but Siri really makes a mess setting a scene in which hue is configured.

I can post some code if needed but because the hue service works with the Eve app I figured it may not be code related.

**Comment by AlexGustafsson** [comment]
I've had problems with Philips Hue as well using the Home app (public beta 3) so I assume that there are still some problems to be solved in iOS 10.

**Comment by pdlove** [comment]
in public beta 5 my smart things plugin for home bridge is working beautifully for color.
I assume you're using the LightBulb service and the hue characteristics?

**Comment by Luc-S** [comment]
I'm currently on public beta 4 so there's still hope :) Yes I am using the the hue characteristic.

The only difference in my code between the hue and brightness characteristic is that I have a function defined for 'getting' the brightness state;

  this.lightbulbService
    .getCharacteristic(Characteristic.Hue)
    .on('set', this.setHue.bind(this));

  this.lightbulbService
    .getCharacteristic(Characteristic.Brightness)
    .on('set', this.setBrightness.bind(this))
    .on('get', this.getBrightnessState.bind(this));

Which I don't have implemented for the hue. Maybe it's required for the home app to request the state of hue as well? This will take some time to try out because I have no idea on how to pass back a color to the callback function, is it rgb, hex, etc.?

**Comment by stephan-01010011** [comment]
I have the same problem with iOS 10 public beta 7. The **HomeKit Accessory Simulator** (part of Hardware IO Tools for Xcode 7.3) works fine. The corresponding color setting is available in the native Home app.
Unfortunately this is neither the case with a lightbulb service and the corresponding hue characteristic in the **homebridge master** branch nor in **KhaosT/HAP-NodeJS 0.3.2**. I think the problem could be teared down to **KhaosT/HAP-NodeJS 0.3.2**, because it is a dependency of **homebridge**.
The **Elgato Eve** app handles the _lightbulb_ defined in **homebridge** and **HomeKit Accessory Simulator** equal. Both _services_ list the hue _characteristic_. In general it could be said that this is some iOS beta issue, but why is it handled correctly by the **HomeKit Accessory Simulator**?
I have compared the hue _characteristic_ UUIDs of **KhaosT/HAP-NodeJS 0.3.2** and **HomeKit Accessory Simulator**. They are equal and therefore correct.
Is somebody able to help?

**Comment by KhaosT** [comment]
Home app require all three color related characteristics (HSB) to exist to show the color palette. Please try adding saturation characteristic and see if it works.

**Comment by Luc-S** [comment]
Awesome! That was it KhaosT, thank you very much!
