### ISSUE TITLE
Siri no longer working

### ISSUE THREAD

**Issue by SJNix** [nfarina/homebridge#735]
Currently using iOS public beta 4, but it wasn't working on iOS public beta 3, but was working previously.

For example if I say "turn on the kitchen table light", she responds "sorry, I don't understand the word 'table'".

I've tried deleting my persist folder and readding my home bridge from scratch, to no avail.

Any ideas?

**Comment by robertvorthman** [comment]
This might not have anything to do with Homebridge, it might just be Apple refining how Siri converts speech into HomeKit actions.  Sometimes Siri says she doesn't understand a command to turn off an iDevice switch, which has native HomeKit support not part of Homebridge, but other times Siri controls the light fine with the exact same command.  I'm running iOS 10 beta.

I used to be able to say "open the garage door" which worked fine.  Then Siri started to unlock my deadbolt which is in the room named garage, instead of opening the garage door.  I had to say "open the garage door opener".  Now "open the garage door" works again.  I have noticed other HomeKit commands have been changing too, like having to say the word brightness or not when specifying a light's percentage.

**Comment by kolossboss** [comment]
I experienced the same problem.
Siri Commands that worked without problems for months, do not longer work. Siri replys "pls reword your command"

Rooms and Scenes are working fine.

I dont know if this is a Homebridge problem or Apple, but non Homebridge Devices are working fine.

**Comment by Noun0** [comment]
Same problem here.
I've tried to reinstall homebridge and deleting persist folder too but without success.

It worked few weeks ago. Siri answers "I don't understand the word television" when i try to turn on the TV.

**Comment by NewFolk** [comment]
Same too me. it`s look like siri does not understand rooms name on Russian. Like Kitchen - "Кухня"
Domoticz + https://github.com/PatchworkBoy/homebridge-eDomoticz 
iOS 9.3.4
rPi3
Eve + Insteon app work Ok

I tried to clear persist and reset home kit on iPhone. 
After re-add devices it works only about 1 hour.

**Comment by RecognitionDesigns** [comment]
I've had the same issue with Siri recently. 
Not able to understand the word 'room', 'tv', 'telly' and probably some more when she has perfectly understood in the past. 
This was with Homebridge running and now with Homebridge not part of my HomeKit setup (moved house so starting from scratch).
I put it down to Siri servers updating known words and commands. Hopefully will get better with the release of ios10.

**Comment by jer78** [comment]
Apple definitely changed something on their end. I also had a harmony plugin with activities like Apple TV, TV etc. Since they are in rooms, I have found that saying "turn on the Bedroom Apple TV" does work. I sent in a iOS bug report from the iOS 10 beta about a month ago. Hopefully they change it back for the release of iOS 10 official release.

**Comment by robertvorthman** [comment]
It seems like Apple is refining Siri on the server-side.  Lately I have noticed Siri is a little smarter.  For a while she could not understand a scene name "Watch TV" but now it works fine again.

**Comment by rudyv** [comment]
Unfortunately I have exactly the same effect for a few weeks, I have my shutters which are named "rollen" and Siri still sees them, even in the latest IOS 10.0.1 GM download. However, my garagedoor is not reacting anymore. When I push the button in the new home application it works and not with Siri. So should I consider to name my garagedoor differently or did someone alreadt found a solution to this ?

**Comment by jclarke0000** [comment]
I had issues with this about a month ago.  There was definitely a change on Apple's side.  What you need to do is explicitly name the device for how you will speak the command (e.g.: The name you will use with Siri).  I had named my lights for the location they were installed.  For example, "Dining Room Table."  I used to be able to say "Turn on the Dining Room Table Lights."  After whatever Apple changed, that command stopped working, but I discovered that if I said "Turn on the Dining Room Table," the command worked.  So my solution was to add the word "Lights" to the name.  Now the that light has the Siri name "Dining Room Lights."  The old command "Turn on the Dining Room Lights" once again works as it used to.

This has nothing to do with HomeBridge.  I had this problem with my Lutron Casetta lights, which are already HomeKit enabled, in addition to other devices enabled through Homebridge.
