### ISSUE TITLE
Status on supporting the new HomeKit additions in iOS 10

### ISSUE THREAD

**Issue by AlexGustafsson** [nfarina/homebridge#737]
iOS 10 introduces several additions to HomeKit. More specifically these:
### Platform:
- Using AppleTV or newer iPads to act as a hub to access the home remotely
- Automation (events and timers)
- Access control for shared users
### Accessories
- Air Treatment Accessories
  - Air Conditioners / Heaters
  - Air Purifiers
  - Humidifiers
- Camera Accessories
  - Display live streams
  - Display still images
  - Control the camera settings
  - Control the speaker and microphone
  - Rich notifications
- Doorbell
  - Generates an event
  - Volume control
  - Visual indicator control
- Doorbell Camera (Combination of the above two)

Source: https://developer.apple.com/videos/play/wwdc2016/710/
- What are the status to support the new additions?
- What steps need to be taken to support them?
- Is it possible to support them?
- How can I help?

**Comment by pdlove** [comment]
They didn't add anything for "Air Treatment Accessories" but did for the others. I think they've added Siri support for the existing services.
I've got the new Services and Characteristics added in my fork of hap-nodejs, but I'm having problems determining the right value for the new permissions to pass through to HomeKit.
I also have no idea what the Camera's tl8v fields should look like.
I'm adding a client to hap-nodejs to compliment the server and allow setting up a proxy to capture the raw decrypted HomeKit feed. This will allow us to see what the Simulated camera passes.

**Comment by simonrb2000** [comment]
Excellent. Looking forward to asking to see live camera feeds with Siri.


On 11 Aug 2016, at 03:24, pdlove <notifications@github.com<mailto:notifications@github.com>> wrote:


They didn't add anything for "Air Treatment Accessories" but did for the others. I think they've added Siri support for the existing services.
I've got the new Services and Characteristics added in my fork of hap-nodejs, but I'm having problems determining the right value for the new permissions to pass through to HomeKit.
I also have no idea what the Camera's tl8v fields should look like.
I'm adding a client to hap-nodejs to compliment the server and allow setting up a proxy to capture the raw decrypted HomeKit feed. This will allow us to see what the Simulated camera passes.

-

**Comment by Luc-S** [comment]
I only have some experience using the iPad 4 as homekit hub, it works but it's really slow (iPhone 6 and iPad 4 both on beta 4). When opening the homekit app on my iPhone while on 4G not a single accessory responds. I have to manually refresh every accessory and then it updates almost instantly.

**Comment by treeiler** [comment]
@Luc-S I am using the fourth generation Apple TV running the beta os and iOS 10 on all of my devices. It is very snappy for me. I think you might be having latency issues due to your iPad possibly either just losing a network connection or maybe timing out. I have both my Home-bridge server (an older MacBook), and my apple tv's connected via CAT 6. If you have access to an Apple TV you should try it out, it works much faster and is more responsive. I find that when using an iPad as a hub it will work for a period of time and then fail unless constantly plugged into power.

**Comment by jcbriones** [comment]
Can't wait for this.

**Comment by xmuskrat** [comment]
Looking forward to camera support.

**Comment by edgr-sanchez** [comment]
Looking forward to this as well. Been testing iOS 10 since beta 1. Glad it's out to the public now, I absolutely **LOVE** the new Home app. Finally one central app.

**Comment by JangoBritt** [comment]
Are there any retail cameras yet? Has anyone been able to figure out how the camera functionality works with homekit yet? Looking forward to homebridge-ing my baby monitors. Lol

**Comment by JangoBritt** [comment]
homebridge-camera-ffmpeg by @KhaosT, if anyone's not found it yet. Working with Video, not so much for Audio (yet)

**Comment by CoskunSunali** [comment]
Have been looking through all day but no luck so far.

Is there a way I extend (via plugins) Homebridge to stream music/audio to a Bluetooth or WiFi speaker?

A speaker I have on mind is http://www.samsung.com/us/audio/wireless-speakers/home/radiant360-r1-wi-fi-bluetooth-speaker-wam1500-za/

Thank you!

**Comment by AlexGustafsson** [comment]
@CoskunSunali, Homebridge is simply a way to add devices to Apples HomeKit platform. It's not suited for multimedia uses, it's made to control smart devices such as lights, radiators etc. However, one could make a plugin to turn the speaker on and off.

**Comment by JangoBritt** [comment]
Probably not quite what you're looking for, but I use the homebridge-AppleScriptfile plugin to get iTunes on my Mac to play a playlist over airplay to a device or devices

**Comment by CoskunSunali** [comment]
@AlexGustafsson and @JangoBritt , Thank you for your the quick responses. I understand what you mean and what both of you say totally makes sense. I might have gotten the idea a little too wrong :)

I have been thinking of what a plugin related to the speaker mentioned above could actually do, based on your feedback.

I don't think the speaker has a power on/off functionality. It is either connected to a power source or not. It has a "mode" functionality that makes it a "TV connected speaker", "Bluetooth speaker" or "WiFi speaker" but those modes can only be changed by a "tapping" a touch button on the device or by using an app called "Samsung Multiroom" on iOS or Android. So I guess they have a command for it which hopefully I can find by using Wireshark or not - if they encrypted it.

If I set the volume to 100% on the speaker, I can then use the built-in Siri functionality to increase/decrease the volume - I believe. So I should not need an extra "Volume down" or "Volume up" functionality. 

The only improvement I can see is a command, such as "Connect to bluetooth speaker" because iOS does not really want to "auto connect" to this speaker once I turn off the Bluetooth on the phone and back on. Not necessarily turning it on and off but leaving the house and then coming back. It just won't reconnect, I have to go to bluetooth settings and click the device so that iOS reconnects. Do you think I can automate this using a Bluetooth LE plugin such as https://www.npmjs.com/package/homebridge-bluetooth ?

BTW, the speaker does not have AirPlay support, unfortunately. So any idea surrounding that is also welcome.

I guess there are no other uses of this device apart from what I mentioned above, thanks to your comments. It now makes better sense, there is no need to develop a "streaming plugin" as you both said.
