### ISSUE TITLE
Inserting a wait between commands

### ISSUE THREAD

**Issue by chymerix** [nfarina/homebridge#743]
Hi,

Is there a way to insert a wait for a specified period of time between accessory commands?

Use Case: I have home automation that turns on two "HomeKit" devices in succession via IR. I need the second IR command to wait for the first to execute.

Thank you.

**Comment by Ricardo1980** [comment]
I had a similar problem in the past trying to control my pimote sockets.
I tried to use var command-queue to send them a command (a python script), but I was unsuccessful creating this queue of commands.
So I need something similar, time between 2 commands and accumulate them in a queue.

**Comment by chymerix** [comment]
I tried a few things but haven't been able to get this to work:

1. I added sleep functions to the homebridge-http component code, and while this did introduce the expected delays, it did not result in the intended outcome. I suspect the sleep functions are causing the requests to timeout somewhere else in the homebridge layer, but I'm not sure.

2. I tried inserting setTimeout functions into the homebridge-http component code before executing the callbacks, but because this is a non-blocking, call both device turn-on requests were immediately executed.

Running out of ideas. Native command queuing at the homebridge layer with a default accessory parameter for execution delay would be awesome. Also open to any other ideas.

**Comment by nbittmann** [comment]
Hi there just quickly jumping in here as I had a similar issue with cheap RF socket.

I've used the following method quite successful so far not nice but I think this is the only way of preventing a simultaneous execution 


My script which I will change to run as a daemon in the future:

`#!/bin/bash

in="/home/pi/code"
codesend="/home/pi/codesend"


while true;
do

        codes=$(cat $in)
        if [ -n "${codes}" ]; then
        for code in "${codes}";
        do
                $codesend $code
        sed -i '1d' $in
done
fi
done
`

This will run in the background until it's stopped so you might want to redirect all the output to /dev/null in order to use it start the script and run it in background e.g. via nohup then all you want to do is to echo the code into /home/pi/code e.g. for my RF solution `echo 7697411 >> /home/pi/code` and the script will immediately pick it up and execute the codensend command then remove the first line from the file.


Hope that makes sense.


Please note you will need to change the codesend tool to your IR based tool not sure how that looks like but I guess similar.

Any question please feel free to reach out.
