### ISSUE TITLE
Running Homebridge at Startup on Windows

### ISSUE THREAD

**Issue by millerstevew** [nfarina/homebridge#776]
How do I run Homebridge at startup on Windows? The wikis describe several methods of doing this on macOS and Linux, but I can't seem to figure this out on Windows. 

Follow up question, once I have a means of running Homebridge at startup on Windows, how might I restart Homebridge without restarting my computer. (I'm assuming I won't have an open terminal window in which I can press ctrl+c.) 

Thanks in advance for the help.

**Comment by gleep52** [comment]
No one has provided input on this huh?  I'm looking into it myself.

**Comment by millerstevew** [comment]
Correct. Ultimately, I found the Windows version of homebridge unreliable, which admittedly could be me, so I installed Ubuntu in a VirtualBox VM. (I had to bridge the network connection to my Windows host.) And now things run flawlessly.

**Comment by gleep52** [comment]
I finally got everything working perfectly now.  I have this VM set to autologin via registry patch, and then put a shortcut in "Shell:startup" folder which points to git-cmd.exe with the command parameters of "-cd-to-home homebridge".  That launches it on startup after it auto logs in... haven't had it fail for a single command except on LTE.  Still trying to figure that one out.  We have an ATV4, but even after signing out and back in it still doesn't work via LTE.  *shrugs* not a biggie though.

**Comment by bittles** [comment]
Just saw this while looking for another issue.  I have a HTPC running Windows with homebridge, domoticz, and HA-bridge.  I use a small program I found named RestartOnCrash that launches with Windows, then is set up to launch those home automation programs if their processes aren't found running.  Set it to look for node.exe, then run node homebridge from homebridge/bin directory.  Found it when I was having random crashes with an older version of homebridge and domoticz, which I've since resolved with upgrading homebridge and building domoticz from source with a later version, but it is still useful for launching on startup and when editing my config.json.  Just close homebridge and it'll automatically relaunch with my new config.json.
