### ISSUE TITLE
No response after a couple minutes. Restarting Homebridge and its fine

### ISSUE THREAD

**Issue by jameswill377** [nfarina/homebridge#782]
Hello

Im on pi3 and followed the guide. everything went well. I only have 2 sonos devices that I have currently added to homebridge because I'm new to all this. 

Basically, the speakers show up on my home app and after a couple minutes, it will say NO RESPONSE. I got to my Pi3 and restart home bridge through ssh by typing homebridge and the speakers work again and show up on my home app. however, after a few minutes, it will say NO RESPONSE and doesn't work. This cycle goes on.  please help me trouble shoot this.

my config is:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",


"accessories": [{
        "accessory": "Sonos",
        "name": "Bedroom Speakers",
        "room": "Bedroom"
 }, {
        "accessory": "Sonos",
        "name": "Kitchen Speakers",
        "room": "Kitchen"
    }]
```

}

**Comment by tmur11** [comment]
@jameswill377 try running homebridge on another device with more resources like a mac to rule out memory issues.

**Comment by gijoecool** [comment]
@jameswill377 the homebridge-sonos plugin is very flakey, I think your results are common. For this reason I've personally removed it from my homebridge setup.

**Comment by jameswill377** [comment]
Hello All

Update:

I managed to make it work. Basically, I was using my MAC to ssh into my raspberry pi and as soon as i terminate my connection from my mac to my pi, the homebridge stops working for me.

Instead, I decided to use the raspberry pi itself and when I keep the terminal window open on my pi, homebridge works well.

I havent setup homebridge to launch at  boot but Im happy with this setup and Im not that good with these things so I do not wish to play around with a working setup. Currently, im enjoying the basic control that homebridge offers of my sonos speakers.

Thanks again to nfarina

**Comment by apwelsh** [comment]
To run the application in the background, and not terminate it when you break the terminal connection, you can use IO Redirectors, and background directives of the command-line:

homebridge > homebridge.out 2>&1 0 < /dev/null &

This redirects stdin (0) to the null device, so it will not be attempting to get keyboard input from the terminal session. And it redirects stderr (2) to stdout (1), and redirects stdout to the file named homebridge.out in the current directory.

The way I prefer to do it though is with screen.  Screen is a *nix utility for creating virtual screens that you can switch between and detach from or reattach to.  To start homebridge in a screen session, I use:

screen homebridge

it will run as normal (or so it appears) now, form here you can use CTRL-A the CTRL-D to detach from the screen.  from here, you can log out of the terminal and the application still runs inside it's virtual screen.

To reconnect to the screen use:
screen -R

If it reports that there is no screen to reattach to, then the process died for some reason.  Otherwise, it will reconnect, and you will be presented with the current screen of the application.

**Comment by jameswill377** [comment]
Thanks Apwelsh

Its interesting that you mention screen. After posting my previous comment, I was looking into if i can use VNC to log remotely into the pi and that way I can work on it without connecting it to my monitor.

I came across a mac app called Screens to VNC via tightvnc into the pi and its working great.

I think I prefer this option. 

Cheers

**Comment by apressly** [comment]
I am having the same issue and need some help. 
1.I have home bridge running on either screen or terminal on a mac mini that is always on.
2. My apple tv is set to never sleep
3. I set up a ping for every 30 min to ping my apple tv and verify its not sleeping
4. I see the home bridge is running fine on the mac but after less than 30 minutes if I look at my iPhones or apple watch home kit says "no response" or "updating" and then "no response".

Quoting the home bridge process and re-running it fixes the issue but I am not always near my computer nor want to do that.

my set up is home bridge with Node: v4.6.0 and NPM: 2.15.9 with the following plugins:
a. Harmony hub
b. Nest
c. Chamberlain MyQ garage door.

I am not sure if there is any fix but I was wondering if there is a way to run this such that it can be automatically quit and re run every so often if there is no fix.
