### ISSUE TITLE
Homebridge on Windows10/MacOS X can't obtain IP Address

### ISSUE THREAD

**Issue by lucaraccis** [nfarina/homebridge#788]
Hi guys, 
I'm having issues with the execution of Homebridge.
Last week I've installed it in a VM with Windows 10 in my work pc, and worked well.
Now I've tried with my W10 PC and my network at home and it doesn't work, iOS can't find Homebridge. 
I've run Nestat to check if homebridge is communicating right but I've see that him can't obtain ip address, remains stuck in 0.0.0.0. 
I've tried to install on my iMac and still doesn't work.
Today I've tried to run the first install in the VM with Win10 and also this still not work.
Any idea?
I've tried to change the port but anything changes...
![hombdrige](https://cloud.githubusercontent.com/assets/15911336/18741010/125c3492-80ad-11e6-9027-b703490cdcfe.PNG)

**Comment by KhaosT** [comment]
``0.0.0.0`` is expected, as it means homebridge is listening on all interfaces on port 51826. Since you're using homebridge in a VM, please make sure you set the appropriate NAT setting in your VM configuration, otherwise, bonjour may not work as expected. If you are sure the NAT setting is correct, please try to use a bonjour browser on iOS device and see if you can see the homebridge's advertised hap service.

**Comment by lucaraccis** [comment]
Thanks @KhaosT  for the reply.
I've reinstalled Bonjour SDK and now the service is running. When I search for bonjour devices with the pc hosting homebridge and with the iphone, I see the _HAP_.tcp, but in the Home App... Nothing :(
