### ISSUE TITLE
Auto Start On Windows

### ISSUE THREAD

**Issue by TheChallinor** [nfarina/homebridge#797]
Any ideas on how to get Homebridge to auto start on windows?

No documentation anywhere ( assuming its possible )

**Comment by bittles** [comment]
Couldn't find a way to do this a clean way, but I ended up using a program called Restart on Crash that monitors if node.exe is running.  If not, homebridge launches.  Also have it monitoring my domoticz to help take care of any random crashes.
Link:
http://w-shadow.com/blog/2009/03/04/restart-on-crash/

**Comment by TheChallinor** [comment]
@bittles That's awesome, thats for posting that. Did you just add C:\Program Files (x86)\nodejs\node.exe to restart-on-crash??

**Comment by SpeedFire0** [comment]
It is possible. I think I found a good solution

1. Simply download this shortcut created by me https://drive.google.com/open?id=0B5t14AxB7bL0VEY0N3ZNSmNsTWs

Or you can create it by yourself. Create a shortcut with the following link:
`"C:\Program Files\Git\git-cmd.exe" CD /D "%APPDATA%\npm\node_modules\homebridge\bin" & node homebridge`
- "C:\Program Files\Git\git-cmd.exe" - is the path where your GIT was installed
-  CD /D "%APPDATA%\npm\node_modules\homebridge\bin" - opens in GIT Cmd your homebridge folder
- node homebridge - runs Homebridge
I've also changed the icon to Homekit icon so it looks a bit nicer

2. Press Win+R and enter "shell:startup" -> OK. 
(This will open your windows startup folder - C:\Users\[YOUR_USER_NAME]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)

3. Paste the downloaded shortcut here

Done

**Comment by TheChallinor** [comment]
@bittles I tried that program but sadly it didn't work by just selecting to run node.exe as I'm guessing it needed the code prompts entering somewhere to get it to run first.

\AppData\Roaming\npm\node_modules\homebridge\bin

node homebridge

**Comment by tjq100** [comment]
I just tracked this down and got it to work.  Since I borrowed from some of the posts on this page, I figured I'd share my solution for others who happen upon this.  

I used NSSM (The non-sucking service manager) to create a proper Windows service that starts even without logging into the machine.  Here's the steps:  

This is for a Windows 7 machine but I suspect it would work the same with 8 and 10.

1.  Get NSSM (https://nssm.cc/)
2.  Unzip the files into a directory (I just put the files into c:\nssm)
3, Launch a Command Prompt with administrative rights (click start, find  "all programs">accessories>"Command Prompt".  Right click and then click "Run as Administrator"
4.  Navigate to c:\nssm\win32 (or win64 if you are running 64 bit)
5. Type:   nssm install <name of service>.  For example:   nssm install HomeBridge
6. A screen will come up.  
    a. In the "Path" box click the dots and navigate to your instance of Git-CMD. For me that was:   C:\Program Files (x86)\Git\git-cmd.exe
    b. In the startup director (which should autofill) you just put the directory for the Git-CMD.  For me that was:  C:\Program Files (x86)\Git
   c.  For Arguments, you have to add everything Git-CMD needs to run.  Such as:   CD /D "C:\Users\<USERNAME>\AppData\Roaming\npm\node_modules\homebridge\bin" & node homebridge      (of course replace <USERNAME> and adjust the rest of that path name as needed to match where you have everything.  
7.  Select the "Login" tab.  Change it to "this account" and enter your username and password (or the credentials that you want the service to use).  I suspect you could have it run under the system account but I didn't want to mess with that so I'm not sure how or if it will work.  I left everything else as a default setting. 
8.  Click the "Install Service" button.  
9. I don't think it starts the service right away.  To actually launch the service, press the Start button and type "services" and press enter to bring up the Services manager.  Find "HomeBridge" or whatever you named it in the list.  Right click and select "run".  

Before I set up the service, I used the comment above from SpeedFire0 to make sure I have all the paths and whatnot sorted out.  Take what he's done and add it to a bat file that you double click to start windows.  Once that works, follow my steps to set up the service.  This is important as the "service" approach does not provide a console window from which you can trouble shoot from. But HomeBridge will start any time the computer boots up even without someone logging in.

**Comment by ltnhat96vn** [comment]
Hey I manage to did this by using @SpeedFire0 's suggestion.
- The basic thing is to put the shortcut in the "shell:startup" folder as instructed by SpeedFire0;
- The crucial thing is setting up the shortcut. And here is how I did it:
         The `Target` box is: `"C:\Program Files (x86)\Git\git-cmd.exe" --cd-to-home homebridge`
         The `Start in` box is: `%HOMEDRIVE%%HOMEPATH%`
And you're done!
It works for me so I hope it works for you guys as well.

**Comment by gee4vee** [comment]
Thank you tjq100! NSSM worked beautifully. By the way, if anyone else tries it, you do have to set up the service to log in with your own account. I tried first with the local system account and the Home app showed Homebridge as not responding. As soon as I switched to my user account Homebridge responded! I see all my Nest devices in Home.

**Comment by L3x1c0n** [comment]
@TheChallinor @bittles Restart on Crash (http://w-shadow.com/blog/2009/03/04/restart-on-crash/) worked great for me and was super easy to setup and not only restarts homebridge when it crashes but also auto launches on windows start.  

I had it monitor: "C:\Program Files (x86)\nodejs\node.exe"
Execute a command selected as: "node homebridge" 
Working directory: C:\Users\xxxx\\AppData\Roaming\npm\node_modules\homebridge\bin

<img width="326" alt="screen shot 2017-10-29 at 11 04 27 am" src="https://user-images.githubusercontent.com/5210577/32140589-536d11da-bc99-11e7-9022-38c2154fcaef.png">

**Comment by TheChallinor** [comment]
I used @SpeedFire0 solution and it works like a dream!
