### ISSUE TITLE
homebridge for fan using relay

### ISSUE THREAD

**Issue by toshibochan** [nfarina/homebridge#801]
not issue is request.
please anyone can make homebridge for control fan using relay and raspberry pi. 
i want connect relay to the fan remote control.

i find this 2 examples
https://www.youtube.com/watch?v=bFAyaKc0ChU
https://github.com/jasoncodes/homebridge-tosr0x-fan

**Comment by murch1** [comment]
The best you can hope for, at this stage, is to hack the "homebridge-rasppi-gpio-garagedoor" to suit your needs.

https://www.npmjs.com/package/homebridge-rasppi-gpio-garagedoor

**Comment by rxseger** [comment]
@toshibochan I'm using something like this to control a relay using Raspberry Pi GPIO:

<img width="768" alt="screen shot 2016-10-09 at 7 49 55 pm" src="https://cloud.githubusercontent.com/assets/19723062/19225961/9580ef52-8e59-11e6-8df0-20d1167ad615.png">

the GPIO output pin can then be simply toggled on or off to control the AC outlet (fan, light etc.). You have several options here:

* [homebridge-gpio](https://www.npmjs.com/package/homebridge-gpio)
* [homebridge-gpio-wpi](https://www.npmjs.com/package/homebridge-gpio-wpi)
* [homebridge-gpio-cmd](https://www.npmjs.com/package/homebridge-gpio-cmd)

I'm using the latter, posted more details about how I set this up (doing almost exactly what you want to do except I'm using the relay to control a lightbulb instead of a fan, although fan control also opens up some interesting opportunities for presenting a Fan service instead of Switch, with adjustable PWM-based speed control and RPM tachometer, etc.) in: [Home automation with Raspberry Pi + Homebridge](https://medium.com/@rxseger/home-automation-with-raspberry-pi-homebridge-f5ad9c4942c5#.1u1am1xd5)

**Comment by toshibochan** [comment]
I'm using homebridge-gpio-wpi for turn ON and off my garden lights. I can use for control fan but I wish some make new homebridge using gpio just for fan. Because fan have 3 or more speed, if I use homebridge-gpio-wpi I have to make many switches for control each speed. The video I posted is different have one switch for turn ON and OFF and speed control.

**Comment by toshibochan** [comment]
Oh and I want control  ceiling fan.

**Comment by lagunacomputer** [comment]
http://www.instructables.com/id/HomeKit-Enabled-Arduino-ESP8266-Self-Powered-110v-/
