### ISSUE TITLE
The Plaftorm Poll

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#834]
Hi all,

Curious to know what most people are installing on.
1. Mac OS
2. RaspBerry Pi (dedicated to homebridge, or running other stuff)
3. Linux based Computer
4. Windows PC

For me, it's a Mac Mini, but after a recent re-install that didn't go well, I'm considering buying a Raspberry Pi. Does the RPi give better reliability?

**Comment by petkoe** [comment]
For Dev and Test a Mac OS
For Running an Rasp Pi 2

**Comment by RXM307** [comment]
RPi 2 here, works well, also have a linux based instance but only for testing

**Comment by gijoecool** [comment]
I have one RPi 3, one RPi 2, and I'm gonna test with a Linux computer this weekend (issues suggest that RPi doesn't have the power to handle the homebridge-camera-ffmpeg plugin).

**Comment by webdeck** [comment]
Mac OS - El Capitan on a Mac Mini

**Comment by maplesteve** [comment]
macOS Sierra on a Mac Mini

**Comment by Starbix** [comment]
Debian Linux PC which is also a Plex server

**Comment by hyperbart** [comment]
Linux VM Ubuntu here but thinking about putting it into production on an rPi...

**Comment by tannebil** [comment]
El Capitan VM running under Parallels and El Capitan on a Mac Mini

**Comment by amareto** [comment]
Trying to run it inside a docker container in a Synology virtual NAS

**Comment by gijoecool** [comment]
@amareto, any luck?

**Comment by amareto** [comment]
@gijoecool not yet, I have the container running and I see the pairing code but I add the homebridge inside the Home App

**Comment by snowdd1** [comment]
Raspberry Pi 2 for testing
and another
Raspberry Pi 2 production env. (almost exclusively running homebridge) 
both running Raspbian Lite editions

**Comment by iomax** [comment]
RP2 running OSMC.

**Comment by rmarinho** [comment]
MacOS for testing, 
Raspberry pi for homebridge.

**Comment by matevzg** [comment]
RP3 for production.

**Comment by jonathanweinberg** [comment]
Docker on Windows for testing.
Raspberry Pi 3 for prod.

**Comment by danielsen2009** [comment]
Sierra for testing, Pi3 for production.

**Comment by JangoBritt** [comment]
Thanks for all the responses! it seems like Pi is the favourite overall...

Out of curiosity, for those who have multiple platforms, do you find that the Pi is the more stable of them?

My main problem at the moment is that very often (like more than 50% of the time) my Homebridge is unreachable. Now, I've got a BT Home Hub 5, which is notoriously crap for Bonjour (mDNS) so I think that's the problem. I've switched off (changed the SSID of my 2.4GHz Network, to try and get everything on the 5GHz network, but I think my Mac is still wired (ie. trying to bridge the router's radios, which is the problem), and I can't figure out how to route HomeBridge only down my WiFi IP.

is there a 5GHz WiFi Raspberry Pi? Would that solve my problem?

**Comment by snowdd1** [comment]
My Pi2 runs 24/7 for 10 months now, being cabled to Ethernet and an APS power source. Homebridge never failed during that time.
Only with introduction of iOS10, I needed to rebuild my home on my iPad to be able to reach it from outside.

**Comment by mbnn** [comment]
Synology SPK package would be awesome! :)

**Comment by justme-1968** [comment]
as a workaround: it works perfectly fine inside the debian chroot spk for synology.

**Comment by EMCSizl** [comment]
Docker on Synology.  

@amareto @gijoecool  I pulled /root outside of docker and mount it under /etc/homebridge instead of just mounting .homebridge.  in this way I can update run.sh  with any debuging info I want, allowing me to see what is going on.

so my volume flag looks like "-v /etc/homebridge/root:/root/ "
you need to remove the the ADD commands from the docker file since these will be in the mounted directory

ADD run.sh /root/run.sh
ADD config.json /root/.homebridge/config.json

when I run up homebridge, I send the output to a log in my run.sh with something like
homebridge >> /root/homebridge.log


Recent updates to DSM have updated docker to 1.11.x that allows attaching to the container, but log files are easier to watch with "tail"

Also forced an update to NPM versions in my docker file, just prior to installing homebridge...
RUN npm install npm -g


Also I have noticed that homebridge seems to be fussy about the order you add other modules.  you may need to experiment but I found HB would not run if installed in this order

homebridge then homebridge-http then homebridge-bigAssFans

however installing in this order worked fine.

homebridge then homebridge-bigAssFans then homebridge-http 


cheers
