### ISSUE TITLE
Configuring plugins with configurationRequestHandler

### ISSUE THREAD

**Issue by suderman** [nfarina/homebridge#836]
I'm new to Homebridge and would like to write my own plugin using the dynamic platform API. I've been studying the [SamplePlatform](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js). 

One thing I can't figure out his how to invoke the [`SamplePlatform.prototype.configurationRequestHandler`](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L98) method, which is supposed to happen when a user tries "to config your plugin". The example includes several UI Types with [respDict](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L120) objects. I've been running the SamplePlatform in my homebridge config, created a fake bulb, but I don't see what I'm supposed to tap in the Home app to config the plugin, and trigger these UI examples.

I must be missing something. Or perhaps the example plugin isn't complete enough to invoke the `configurationRequestHandler`? Thanks to anyone who can point me in the right direction.

**Comment by KhaosT** [comment]
@suderman the ``configurationRequestHandler`` gives the plugin developer a way to present UI on supported iOS app to configure the plugin. Since it is a custom protocol built on top of HAP, it requires the HomeKit app to support it. Currently you can see the UI in the [sample app](https://github.com/KhaosT/HesperusBridgeConfigurator) or [Hesperus](https://itunes.apple.com/us/app/hesperus/id969348892?mt=8).

**Comment by suderman** [comment]
Ah, that's what I was missing. Thank you!
