### ISSUE TITLE
Homebridge runs for a few minutes then doesn't respond 

### ISSUE THREAD

**Issue by TheChallinor** [nfarina/homebridge#849]
Having a strange albeit very annoying issue whereas Homebridge runs for a few minutes ( Windows 10 pro 64bit ). It seems to work as soon as soon as you run the node homebridge command for a few minutes then I get the not responding error on the home app.

**Comment by apressly** [comment]
I'm having the same issue.. and reported it but no one is responding with a fix :(

**Comment by BeardedSimmo** [comment]
Me too.  I can't seem to pin-point when it's crashing.  It does however seem to have started since I've upgraded to iOS10 and am now using the (Apple) 'Home' app.  I'm using the 'People', 'eDomoticz', and 'http' plugin's on a Windows 10 64 bit mini pc with no sleep/hibernate settings.  It's really frustrating!  It freezes until I CTRL-C it then it works again, requiring a second CTRL-C to SIGTERM it.

**Comment by TheChallinor** [comment]
It's driving me nuts!

I've noticed that my nest updates the cmd line with code so its talking to the home bridge server and just not the home app.

**Comment by nebdy** [comment]
Plus 1

Works lovely then after a while siri responds with "Sorry Ben I didn't hear back"

A quick reboot works but not a great work around

**Comment by BeardedSimmo** [comment]
What plugins are you guys using?  Maybe we could diagnose together using a process of elimination!

**Comment by woobione** [comment]
I'm having the same problem and the connection drops after a seemingly random time. Sometimes it runs for a few hours and sometimes only minutes. I have my raspberry restarting two times a day (when I most likely use it) to go around it for now - but that's a temporary solution.

I run homebridge-telldus for telldus live and homebridge-harmony for my Harmony Hub.
Homebridge is running on a raspberry pi 3rd gen. Other devices in my network is a philips hue hub and an apple tv. And from what I can see there is no correlation to what app I use on my iphone except for that apples home app won't work at all with homebridge atm. Siri works fine however.

Hope that helps.

**Comment by lagunacomputer** [comment]
sudo systemctl status -l homebridge

to see if its crashing because of bad text in config.json

**Comment by apressly** [comment]
I will try that tonight.. I am using homebridge with Harmony hub,Mq garage door opener, and nest.

**Comment by apressly** [comment]
sudo systemctl status command did not work... command not found :(

**Comment by BeardedSimmo** [comment]
Still no good for me either.  Having tested every switch/device individually in my system (80 plus devices) from Domoticz to try 'lock' the system I'm non the wiser.  It all runs well for me until I stop changing the device states / using homebridge then it simply freezes (after a few minutes) and requires a restart.  Would there be anyone with more techinical knowledge than me on here, who may be able to identify what causes it to simply freeze after a period of inactivity?  Is there a way I can produce and submit a log file from my system?

**Comment by BeardedSimmo** [comment]
Looking through the comments it seems that we're all using the 'Harmony' plugin (or in my case using Harmony as 'Hardware' in Domoticz).  There's been some firmware updates to the hubs recently.  I wonder if that's causing the problems?

**Comment by misanthrophy** [comment]
I am using the Harmony plugin too. Experiencing the same issue. After a while Homebridge does not respond. I then have to kill Homebridge over the terminal and start it again. As the homebridge plugin 0.2.0 does not work for me and some other people. I am running 0.1.0 of harmonys homebridge plugin.

**Comment by Kolbi** [comment]
Tried "sudo systemctl status -l homebridge" but nothing suspicious.

**Comment by TheChallinor** [comment]
Hey,

I'm just using IFTTT maker channel and nest and I'm getting this issue. 

Moved json config to my Mac from Windows PC and still getting same problems. 

Out of interest are any of you guys using Apple TV / iPad as home hub?

**Comment by BeardedSimmo** [comment]
Applt TV3 for me.  Worked fine and dandy until iOS10.  I'm beginning to think that it may be that!

**Comment by gijoecool** [comment]
@BeardedSimmo, you are correct. Apple TV (gen 3) is no longer supported as a HomeKit hub as of iOS 10.

**Comment by gijoecool** [comment]
Oops, I guess my last post isn't entirely correct.
[(https://support.apple.com/en-us/HT207057)]

**Comment by BeardedSimmo** [comment]
Just trying a complete - blitz and reinstall of homebridge.  Hope it works.

**Comment by apressly** [comment]
Update I got mine working... there were 2 issues:
1. My Q -> use Liftmaster 2 plugin
2. Homekit on spouses phone, -delete "default home" 

 1) I got rid of myQ and using Liftmaster 2 plugin.. now with harmony, liftmaster 2, wink and nest.. all is working.

. Also i had to use    this for wink:
"client_id": "quirky_wink_android_app",
"client_secret": "e749124ad386a5a35c0ab554a4f2c045",

2) The iphone that has the homekit sign in which is attached to the apple tv 4 is the main phone, you need to invite your spouse or kids on their phones and give them all access. They need to delete the default "Home" in their app and use the family home that was set up on the original phone

**Comment by riccardogermano** [comment]
Hello. I had the same issue described on this and other couple of posts for many days. 
As others, I tried to reboot the server (in my case is a Mac), reboot router, etc. and even though connectivity came back afterwards, didn't last for more than a few minutes/seconds. 
I got it fixed by just setting dynamically the IP (IPV4) on the server which had a static address before. I reserved the same IP I had on the DHCP options and even though from a networking prospective nothing changed, somehow this actually fixed the issue. It's been a couple of hours now since all accessories look reachable and responsive. DNS stayed the same, 
Hopefully this workaround, if applicable, might work for others.

**Comment by TheChallinor** [comment]
@riccardogermano Tried this and still no luck, seems to be working on my iMac inside the house, nest is still unreliable. 

Won't run on Windows 10 Pro machine anymore, despite it running on there for a couple of weeks ( this is my main home server ). No accessories show up anymore

**Comment by apressly** [comment]
Just to be clear all the steps i took:

Quit homebridge from console
Uninstalled all plugins from console
Delete bridge from Home app on iphone
On Mac Delete persist and accessory files

Next install one plugin at a time to make sure the plugins are good. 

Every time I installed a plugin I  Quit home bridge, updated the config file delete the bridge in home app and delete persist and accessory files then restarted a fresh home bridge in console and re-added bridge in on home app. I would wait a day or at least a couple hours to make sure its still responding, turned off wifi, turned on wifi to make sure I could access on network and off network.

I installed harmony hub, let it run , Then installed nest , then liftmaster2, then wink

**Comment by riccardogermano** [comment]
@apressly,
 You gave me a hint. My hb failed again and after reading your last comment, realized that the root cause of my issue was the MYQ plugin. Event though I knew it wasn't officially supported, I was testing it since the functionality was working. But in my case since after disabling it, for about a day, I haven't lost connectivity.
The liftmaster might not work for me since I have a Chamberlain opener.
Not sure about other plugins causing the behavior but at least the chamberlain-MYQ looks to be causing it.
Thank you.

**Comment by apressly** [comment]
@riccardogermani I have a chamberlain opener too but LiftMaster works for me . I downloaded the liftmaster app on iOS to verify the login works and it does . Try it and see if it works :)

**Comment by riccardogermano** [comment]
That's great! I didn't know that, thanks! I'll give a try to the liftmaster plugin then. The credentials are working fine.

On Oct 25, 2016, at 10:24 PM, apressly <notifications@github.com<mailto:notifications@github.com>> wrote:


@riccardogermani I have a chamberlain opener too but LiftMaster works for me . I downloaded the liftmaster app on iOS to verify the login works and it does . Try it and see if it works :)

-

**Comment by BeardedSimmo** [comment]
Well, in relation to my problem (Homebridge suddenly 'stopping' for no reason and required a restart) I think I've cracked it.  After a complete uninstall, upgrade of Win 10 and rebuild of the entire Homebridge system and associated plugins my system ran perfectly and without issue UNTIL...........

I realised than after @gijoecool s post above regarding Apple TV3 and inability to automate through iOS10 was the cause of my Homebridge stopping/freezing. Previously my iOS9/Elgato Eve setup ran perfectly through my ATV3 and the automations / rules that I had setup ran perfectly.  These carried forward after upgrading to iOS10 in the Homebridge database but only since re-building my system I lost the ability to create any 'automations' in the 'Home' app.  I tried to cheat and added some automation through the 'Eve' app and of course these carried through to 'Home' but as soon as they triggered the system locked again, requiring a reboot!  I have since removed them and the Homebridge has run for 24 hrs without a hiccup.

It seems that I'm about to have my hand forced into buying an ATV4 (not good value in the UK from a cost/content perspective!) or newer iPad (mine will only run iOS9) if I want to retain Automations through Homebridge.  Thanks a bunch, Apple!

**Comment by Kolbi** [comment]
@BeardedSimmo interesting. I'm also using a ATV3 and tried some automation with iOS9. They are currently disabled but not removed. Have to do some tests to verify...

**Comment by BeardedSimmo** [comment]
@Kolbi it would be interesting to see if anyone with this problem solves it by simply disabling automations in iOS10 (if they're using an ATV3).  From my experience they don't need to be deleted necessarily, just disabled.  Saves re-writing them all in the future!

**Comment by woobione** [comment]
I have an Apple TV 4th gen and this still happens, for the record.

**Comment by BeardedSimmo** [comment]
@woobione  - Might be worth just disabling your automations / rules regardless, to see if it's an issue with the automations themselves rather than the ATV.  ('Scenes' seem OK BTW).

**Comment by woobione** [comment]
I have removed my automations and then re-added them without result. However, I have never tried not having automations at all since that is basically the reason I have homebridge and an Apple TV. My automations today is "Arriving Home", "Leaving Home" and "Wake Up".

**Comment by TheChallinor** [comment]
Mine now has been running well for over a week, I changed the MAC address of the Homebridge and also the pairing Pin and its been running fine ever since. 

One note however is that the Home app took a few attempts to find and pair with the Homebridge. Discovery app on iOS confirmed the necessary processes were running but Home app failed to find it for a while. 

It also took a good few times logging in and out on ATV3 iCloud account before remote access would kick in. Now if only would add a menu to tell you if your logged into Home on not on your Apple TV3, obviously won't because of the 4 but would still be handy all the same.

**Comment by netdudeuk** [comment]
Hi

I have the same issue with Homebridge running on a Pi Zero.

I run it manually in a shell window.

Software starts up ok with only a GPIO light switch and the Pi Zero temperature -
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:33",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Config file",

    "accessories": [
        {
            "accessory": "GPIO",
            "name": "Desk light",
            "pin": 7
        },
        {
            "accessory": "PiTemperature",
            "name": "Pi Zero Temperature"

        }
    ]
}

I've re-paired but that doesn't fix it.

I'd rather not do a rebuild.

Anything that I can do to capture errors ?  None are shown in the window.

Thanks

**Comment by baelim** [comment]
looks like this is an improper firewall rule issue.  to test this try turning off the firewall and see if you still get the "no response" in your iOS.

the reason homebridge works initially it's because the initial TCP handshake is started by the server.  outbound firewall rules are set to allow by default and for as long as the connection is maintained iOS devices can sent its ack back.  once the handshake is lost however the iOS devices cannot initiate connection because the firewall will block incoming requests by default.  

an inbound rule allowing port 51826 local from all remote ports to pass through should be the solution.

**Comment by netdudeuk** [comment]
Thanks. This does seem to be the case.

I've now noticed though that the iOS app always shows that my 'desk light' is on when the app first starts, even though it isn't meant to be.  The putty shell doesn't show any new  'on' command.

This happens on both the iPhone and iPad.

Any ideas please ?

**Comment by baelim** [comment]
If I had to guess that's remnants of the firewall/network issue and one that I wouldn't bother too much if it only occurs when you start the script.  If the issue doesn't go away probably you should open a separate thread instead of tagging the issue here.

**Comment by earlthesquirrel** [comment]
Can you guys check to see if it works with commands to lights, but hangs after an attempt to access any sort of lock/door?  I think this might be related to some changes in Wink (and others) where they're trying to prevent voice control of locks (for security purposes... I know Alexa will NOT allow control of a lock, and this has percolated out into other systems..)

**Comment by earlthesquirrel** [comment]
I think it might be connected to this : https://github.com/nfarina/homebridge/issues/1000

**Comment by gijoecool** [comment]
@earlthesquirrel, can you check/post your logs. I know there was an issue in [homebridge-zway](https://github.com/SphtKr/homebridge-zway/issues/74) and [homebridge-smartthings](https://github.com/pdlove/homebridge-smartthings/issues/126) due to a change in the way Siri requests the lock changes.

**Comment by earlthesquirrel** [comment]
I can tell you that the homebridge-wink plugin author just described a patch (I made it manually and it resolved the issue.)  Basically Wink changed the return results from their interface.  I can tell you that I suspect this is related to the Alexia change.  In any case fixing the return value (see https://github.com/KraigM/homebridge-wink/issues/74#issuecomment-277198346) fixes the issue.    Other plugins have had to update for similar issue.   So, if you have Wink (or the plugins listed here : https://github.com/nfarina/homebridge/issues/1000) it's a similar fix for all.

**Comment by wakuwaku** [comment]
Running homebridge on a PI2, it stops working after 30 seconds. 
However, when I run in debug mode (type: sudo homebridge -D) I get this error after crash exit:

> /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
>   dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
>          ^

I resolved it (crash was disappeared ) with the following steps:

> sudo /etc/avahi/avahi-daemon.conf

enable dbus
> [server]
> enable-dbus=yes
> 
Then remove all avahi related packages

> sudo apt-get remove avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev

Then install them again
> sudo apt-get install avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev

After reboot of the PI, homebridge is running and stable.  
Hope this works for you as well.

**Comment by thetom89** [comment]
Hi, I'm having a similar issue.  HomeKit works perfectly with my LifX bulbs.  After a time, I get no response from my bulbs in HomeKit.  Homebridge is still running in Terminal, and if I switch on and off the bulb at the source, I can see that it is still communicating with Homebridge.  There must be a problem with HomeKit talking to homebridge.  Would anyone please be able to point me in the right direction?

**Comment by earlthesquirrel** [comment]
The issue we fixed was related actually to one device (or device type).
When that device sent data, that wedged the homebridge/wink plugin and thus
the entire homebridge.

The fix I got made it so that it handled the data properly.  For Wink, I
believe one value went from 0/1 to true/false... but you'd have to check
the code fix to see for sure.

Earl

**Comment by nickw444** [comment]
Seems this issue also plagues [brutella/hc](https://github.com/brutella/hc) https://github.com/brutella/hc/issues/31.

**Comment by guillaumesoul** [comment]
I have the same issue (conf : raspbian jessie, domoticz, homebridge-eDomoticz)

**Comment by nickw444** [comment]
This _should_ be resolves as of merging the Dnssd branch. Have you updated the library?

**Comment by guillaumesoul** [comment]
Installation is just 3 days ago, do I still have to update the library? also read that harmony hub could have an influence on homebridge crash, I will try to remove harmony and see if it's more stable without

**Comment by nickw444** [comment]
Apologies; thought this comment was in the brutella/hc repo. If you are interested in trying out an alternative bridge, maybe check it out 🙂

**Comment by HelloNewW** [comment]
Having a similar issue. 
Razberry works perfectly with my Fibaro device but with homebridge 
It can take 3 min until it find my device(updating... forever)  .
Sometimes get no response in HomeKit.
No body has the some issue?
IOS 11.3

**Comment by jungopro** [comment]
I do! I do!
