### ISSUE TITLE
Homebridge not starting (no errors)

### ISSUE THREAD

**Issue by boikedamhuis** [nfarina/homebridge#866]
Since today Homebridge won't start anymore. As soon as I add platforms or accessories to the config.json Homebridge won't boot completely anymore. 
![schermafbeelding 2016-10-21 om 22 46 22](https://cloud.githubusercontent.com/assets/6382277/19611071/356258be-97e0-11e6-9843-a1d594afaff1.png)

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file con$

"accessories": [
    {
        "accessory": "WeMo",
        "name": "Coffee Maker"
    }
],

"platforms": [
    {
        "platform" : "PhilipsHue",
        "name" : "Hue"
    }
]
```

}
`

When I remove data from config.json it starts normally... 
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    } 

}`

![schermafbeelding 2016-10-21 om 22 45 09](https://cloud.githubusercontent.com/assets/6382277/19611050/0738540c-97e0-11e6-880c-d54706ba3e8b.png)

What's the problem?

**Comment by kevinsegal** [comment]
I had this same problem about 2 weeks ago. Running latest and latest stable node/npm. Issue for me was the same (startup fails and logs no error), I was trying to connect to my ZWay device and network of Z-Wave devices (as a platform).  I tried many things and eventually figured out that Homebridge was crashing because it didn't seem to process certain accessories properly -- it would successfully register all my devices until it reached one of my contact sensors and then it'd quit.  I removed all of my contact sensors from the Zwave network and tried booting Homebridge, and that was successful -- and it has been running since then.  Seems to be a bug in recognizing/registering accessories, only happened to me once I updated to latest release.

**Comment by gshewan** [comment]
@boikedamhuis Try pasting your config.json [here](http://jsonlint.com/#) and clicking [Validate JSON], but to me it looks like an issue the "description" line, try removing the entire line, you don't need it anyway.

**Comment by Neelrp12** [comment]
Try using this config.json


{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [{
		"accessory": "WeMo",
		"name": "Coffee Maker"
	}],

	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Hue"
	}]
}

**Comment by KhaosT** [comment]
What do you mean by wont start? The screenshot you post is running ``rfrx.py`` instead of homebridge.

Best Wishes,
Tian

**Comment by jg506** [comment]
I agree with @kevinsegal. Homebridge will freeze or crash when managing accessory with certain or unexpected states. In my case "jammed" state which is frequently is state of my front door lock, consitently reproduced this issue. I had to remove the lock accessory and had no issue since. Took about a month to find root cause.
