### ISSUE TITLE
Does homebridge support Philips Hue without additional hardware? 

### ISSUE THREAD

**Issue by Rubytastic2** [nfarina/homebridge#871]
Does HomeBridge support philips hue lights without the philips hardware bridge?
I could not find this information since there are several philips hue plugins for homebridge but its not really clear if you need the hardware unit from philips. I would like to use the homebridge software and be able to control the lights without additional philips hardware.
If would be nice if siri support would also be available

Are there any informations on how to set this up?
Kind regards

**Comment by klaasjoerg** [comment]
Hi, well you need definetively some certain kind of hardware, because hue lamps to no communicate via standard TCPIP or WLAN protocols but is based on the "zigbee" wireless standard.
So you basically have two popular choices:
- a.) Simply use the hue-bridge from philips, which is often part of a bundled package and does the translation between zigbee-wireless and your lan.
or
- b.) Buy a raspberry pi including zigbee hook-on board or so, to be able to communicate with the bulbs.

However in both cases you need a piece of hardware somehow, that does the translation between zigbee-protocol and the usual tcpip-stuff....  

Personally I would recommend the philips bridge. It's stable. Doesn't cost much and has a open API so, to finally answer your last question:
Yes, you can install homebridge tools (or zwave stuff for home-automation) or both to do your own things. And yes: You can adress the bulbs via siri. But that's already the case if you only use the philips hue-bridge and ios app.

Hope this helps a bit.

**Comment by Rubytastic2** [comment]
Great thank you for the explanation. 
Going for the starterkit then!
