### ISSUE TITLE
add characteristic.username

### ISSUE THREAD

**Issue by justme-1968** [nfarina/homebridge#89]
i think it would be good to have a characteristic.username that can be set from a platform module and is then used with accessory_Factor.Accessory instead of the one create by createUsername.

this would allow to keep the id tied to a specific device even if the user visible name changes.

**Comment by nfarina** [comment]
So this question is very relevant to #58 - it would be great if we had something like `username` for every accessory that remained stable so that we can associate HomeKit "IDs" with it.

Currently I was planning on just using he "display name" (or "user visible name" as you suggest) instead of username, for the following reasons:

  1) HomeKit seems to require that Accessory "display name" is unique inside a home
  2) I'm having difficulty imagining developers of HomeBridge plugins being able to create and maintain a consistent "other string" that remains unique across user visible name change.

**Comment by justme-1968** [comment]
for the FHEM platform shim that i'm currently working on i have access to the device internals and most of the devices do have some sort of physical serial number or id. this is true for homematic, MAX, HUE and SONOS devices and some more, for FS20 and intertechno the device rf address can be used in combination with the device type. for other devices i will create a unchanging address on device creation in FHEM that will remain constant across renames and restarts.

the current HUE shim should be able to do the same.  

#58 will be very welcome for the FHEM shim. if i export all devices in my installation the current way of doing this runs out of port numbers :)

**Comment by justme-1968** [comment]
ps: you can find the current version of the FHEM shim here: https://github.com/justme-1968/homebridge/blob/master/platforms/FHEM.js

i will do some more cleanups and then it would be good to merge it to your repository.

**Comment by nfarina** [comment]
Excellent points, and very good to know. I'm currently going the direction of requiring a globally-unique UUID for every Accessory - which can be deterministically generated based on an arbitrary string if needed (like serial number as you mention).

**Comment by justme-1968** [comment]
that sounds good.

**Comment by nfarina** [comment]
Closing this as we now only have one single username associated with the Bridge; Accessories don't need to generate their own anymore.
