### ISSUE TITLE
One accessory blocks the whole homebridge

### ISSUE THREAD

**Issue by patricks** [nfarina/homebridge#948]
Since I use homebridge now for many month I have many different devices connected to it (ble-thermostat, hue-lights, netatmo stations). Now I have some problem. The ble-thermostat plugin connections via bluetooth to the thermostats do get/set the temperature and this takes a long time (> 5 seconds) to get the first response.

While this happens other devices are also not responsible, so it takes me now very long, to just switch a light. Which is annoying, because I only use HomeKit for controlling the lights 😉. Or is this just a problem from the original iOS 10 HomeKit implementation?

Wouldn't it be in general better to handle every accessory / platform separate?

Is there any workaround for this? Should I start homebridge 2 times, with different configs? Is this possible?

**Comment by KhaosT** [comment]
Ideally if the plugin is taking that long to process the request, it should invoke the callback immediately instead of wait until the request actually sent. This is a protocol limitation of HAP, which only allows one concurrent request per connection and the request is blocking.

If you can contact the plugin developer, please ask him to consider invoking callback handler immediately while actually sending the request. Otherwise, you can try to run two or more homebridge instances with different configurations. Please check [here](https://github.com/nfarina/homebridge/blob/master/lib/cli.js) for more details.

**Comment by Danouchka** [comment]
Hi I have same issue

my Bravia plugin is blocking the whole homebridge starting phase because it cannot connect to my TV
[BraviaPlatform] Error:  Error: connect ENETUNREACH 192.168.1.81:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.1.81',
  port: 80
}

**Comment by NorthernMan54** [comment]
@Danouchka This is an issue for the plugin developer, please raise your issue there
