### ISSUE TITLE
Multiple homekit bridges

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#985]
It is possible to have homebridge use multiple homekit bridges (other than running multiple instances of homebridge with different config.json files)?

I've created a plug-in for Philips Hue, https://github.com/ebaauw/homebridge-hue, that in addition to lights also exposes groups, sensors, schedules, and rules from the Hue bridge.  I run into the homekit limit of 99 bridged accessories per bridge.

**Comment by KhaosT** [comment]
Yes, check homebridge --help

Best Wishes,
Tian Zhang

**Comment by ebaauw** [comment]
Thanks, Tian.

Yes, I had seen that.  My question (sorry, I'm not a native speaker): can my plug-in make homebridge expose multiple bridges to homekit dynamically, when it needs to expose more than 99 accessories?  Without the need to configure multiple instances of homebridge statically.

**Comment by KhaosT** [comment]
No, currently there is no way for plugin to do that. HomeKit doesn't expect bridged accessories to be changed frequently so having homebridge to manage multiple instances of HAP endpoints meaning it needs to track all the accessories in the past in order to determine which accessory should goes to where.

**Comment by ebaauw** [comment]
Thanks.
