### ISSUE TITLE
Cannot run Homebridge on RPI3 (Jessie)

### ISSUE THREAD

**Issue by clegendre** [nfarina/homebridge#998]
Hello,

I'm on RPI 3 with node 5.12 installed and the latest version of homebridge.
I'm unable to start homebridge and get stuck with the following error:

```
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
throw ex;
^
Error: /usr/lib/arm-linux-gnueabihf/libavahi-client.so.3: unexpected PLT reloc type 0x36
at Error (native)
at Object.Module._extensions..node (module.js:440:18)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
throw ex;
^
```

I tried to rebuild mdns, without success.

Any idea ? Is homebridge not compatible with Jessie ?

Thank you,

**Comment by ehusar** [comment]
Yes, it works on Jessie.  I have done two installs now on Jessie without issue.  What guild did you follow for the install?

**Comment by psdtech** [comment]
Could you document your steps on a virgin Jessie  :)

**Comment by ehusar** [comment]
The instructions on this site have worked of me overtime. I have not deviated from this at all.

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

Pay attention to every step.  Make one mistake and it could impact the setup.  It will eventually tell you to follow the READ ME file so jump out to that when it says and then back to the tutorial.

Let us know if you have issues or anything strange happens.

**Comment by ehusar** [comment]
Also, for the auto boot instructions as the end I have used the init.d version and it has worked of me every time.  I did one of the other options without any luck on why first install.

**Comment by erfinb** [comment]
I followed all of the instructions using the "Running Homebridge on Bootup (systemd)" version as outlined by the link on the page: https://timleland.com/setup-homebridge-to-start-on-bootup/

and I get the following error:

pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-01-05 21:39:44 CST; 3s ago
 Main PID: 6556 (homebridge)
   CGroup: /system.slice/homebridge.service
           ├─6556 homebridge
           ├─6563 /bin/sh -c /bin/echo -n "$(npm -g prefix)/lib/node_modules"...
           └─6564 npm
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-01-05 21:39:44 CST; 4s ago
 Main PID: 6556 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─6556 homebridge
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-01-05 21:39:44 CST; 5s ago
 Main PID: 6556 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─6556 homebridge
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-01-05 21:39:50 CST; 558ms ago
  Process: 6556 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 6556 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-01-05 21:39:50 CST; 2s ago
  Process: 6556 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 6556 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-01-05 21:40:00 CST; 131ms ago
 Main PID: 6590 (node)
   CGroup: /system.slice/homebridge.service
           └─6590 node /usr/local/bin/homebridge -U /var/homebridge

I have checked and the portion referencing "Process: 5993 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS " has an actual file at that location, it's a shortcut pointing to that file elsewhere.  I'm at a loss at this point as I have even wiped the raspberry pi twice now...

**Comment by psdtech** [comment]
Installed, its working, problems with autostart

Get this:
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.
insserv: Script homebridge is broken: incomplete LSB comment.
insserv: missing valid name for `Provides:' please add.


Here's my init.d config fig
#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge"
user="pi"


The link to homebridge lives in /usr/bin/homebridge  NOT /usr/local/bin/homebridge  Only thing I have changed.

**Comment by pr3sidentspence** [comment]
I got this after doing an apt upgrade tonight.

**Comment by patrickbusch** [comment]
You should add something to provides, e.g. 


> Provides: Homebridge service

**Comment by FradSer** [comment]
> You should add something to provides, e.g.
> `Provides: Homebridge service`

Works for me. Thank you @patrickbusch
